"""The FOMO keypoint detection model."""

from luxonis_ml.typing import Params
from typing_extensions import override

from luxonis_train.config.predefined_models.base_predefined_model import (
    SimplePredefinedModel,
)


class FOMOModel(SimplePredefinedModel):
    """FOMO, which predicts one point for each object instead of a box.

    The model is small and fast, and it suits a device that cannot run a
    detection head.

    Throughput:
        Frames per second at 384x512.

        - ``light``: 140 on RVC2, 243 on RVC4
        - ``heavy``: 34 on RVC2, 230 on RVC4

    Notes:
        A larger ``object_weight`` in ``loss_params`` raises the recall and
        also the number of false positives. ``use_nms`` in ``head_params``
        removes some false positives, and also some true positives when two
        objects sit close together.

        A lower ``attach_index`` in ``head_params`` reads an earlier stage
        of the backbone, which gives a larger heatmap and a better position,
        at the cost of speed.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        The ``model`` section of a config:

        .. code-block:: yaml

            model:
              predefined_model:
                name: FOMOModel
                params:
                  variant: light

    Components:
        - Nodes: ``EfficientRep`` -> ``FOMOHead``
        - Losses: ``FOMOLocalizationLoss``
        - Metrics: ``ConfusionMatrix``
        - Visualizers: ``FOMOVisualizer``
        - Main metric: ``ConfusionMatrix``
        - Variants: ``light``, ``heavy``

    """

    def __init__(self, **kwargs):
        super().__init__(
            **{
                "backbone": "EfficientRep",
                "head": "FOMOHead",
                "loss": "FOMOLocalizationLoss",
                "metrics": "ConfusionMatrix",
                "confusion_matrix_available": True,
                "visualizer": "FOMOVisualizer",
            }
            | kwargs
        )

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Params]]:
        return "light", {
            "light": {
                "backbone": "EfficientRep",
                "head_params": {
                    "n_conv_layers": 2,
                    "conv_channels": 16,
                },
                "backbone_variant": "n",
            },
            "heavy": {
                "backbone": "MobileNetV2",
                "head_params": {
                    "n_conv_layers": 2,
                    "conv_channels": 16,
                },
            },
        }
