"""The unsupervised anomaly detection model."""

from luxonis_ml.typing import Params
from typing_extensions import override

from luxonis_train.config.predefined_models.base_predefined_model import (
    SimplePredefinedModel,
)


class AnomalyDetectionModel(SimplePredefinedModel):
    """Unsupervised anomaly detection, after `DRAEM
    <https://arxiv.org/abs/2108.07610>`_.

    The model trains on images with no anomaly. Train it with
    `LuxonisLoaderPerlinNoise
    <luxonis_train.loaders.LuxonisLoaderPerlinNoise>`. With the
    probability ``noise_prob``, the loader blends an image from a texture
    dataset into a training image inside a Perlin noise mask. That mask
    marks the anomaly. The backbone reconstructs the clean image. The
    head reads the reconstruction and the input image together and
    segments the anomaly. The loss compares the reconstruction with the
    clean image, and the predicted segmentation with the mask.

    Throughput:
        Frames per second at 256x256.

        - ``light``: 10 on RVC2, 170 on RVC4
        - ``heavy``: 0.5 on RVC2, 61 on RVC4

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        The ``model`` section of a config:

        .. code-block:: yaml

            model:
              predefined_model:
                name: AnomalyDetectionModel
                params:
                  variant: light

    Components:
        - Nodes: `RecSubNet` -> `DiscSubNetHead`
        - Losses: `ReconstructionSegmentationLoss`
        - Metrics: `JaccardIndex`
        - Visualizers: `SegmentationVisualizer`
        - Main metric: `JaccardIndex`
        - Variants:

          - ``light``
          - ``heavy``

    """

    def __init__(self, **kwargs):
        """Initialize the model with its default components.

        A ``metrics_params`` given here replaces the whole default two-
        class configuration.

        """
        super().__init__(
            **{
                "backbone": "RecSubNet",
                "head": "DiscSubNetHead",
                "loss": "ReconstructionSegmentationLoss",
                "metrics": "JaccardIndex",
                "confusion_matrix_available": False,
                "metrics_params": {
                    "num_classes": 2,
                    "task": "multiclass",
                },
                "visualizer": "SegmentationVisualizer",
            }
            | kwargs
        )

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Params]]:
        """Get the default variant name and the available variants.

        The default is ``light``. Each variant sets ``backbone_variant``
        and ``head_variant`` to one size: ``"n"`` for ``light`` and
        ``"l"`` for ``heavy``.

        Returns:
            ``tuple[str, dict[str, Params]]``: ``"light"`` and the two
            variants with their constructor arguments.

        Example:
            >>> default, variants = AnomalyDetectionModel.get_variants()
            >>> default
            'light'
            >>> variants["heavy"]
            {'backbone_variant': 'l', 'head_variant': 'l'}

        """
        return "light", {
            "light": {
                "backbone_variant": "n",
                "head_variant": "n",
            },
            "heavy": {
                "backbone_variant": "l",
                "head_variant": "l",
            },
        }
