"""The unsupervised anomaly detection model."""

from luxonis_ml.typing import Params
from typing_extensions import override

from luxonis_train.config.predefined_models.base_predefined_model import (
    SimplePredefinedModel,
)


class AnomalyDetectionModel(SimplePredefinedModel):
    """Unsupervised anomaly detection, after `DRAEM
    <https://arxiv.org/abs/2108.07610>`_.

    The model trains on images with no anomaly. A backbone reconstructs the
    image, and the head segments the anomaly from the difference between the
    two. Train it with `LuxonisLoaderPerlinNoise
    <luxonis_train.loaders.LuxonisLoaderPerlinNoise>`, which pastes noise
    from a texture dataset to make the anomalies.

    Throughput:
        Frames per second at 256x256.

        - ``light``: 10 on RVC2, 170 on RVC4
        - ``heavy``: 0.5 on RVC2, 61 on RVC4

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        The ``model`` section of a config:

        .. code-block:: yaml

            model:
              predefined_model:
                name: AnomalyDetectionModel
                params:
                  variant: light

    Components:
        - Nodes: `RecSubNet` -> `DiscSubNetHead`
        - Losses: `ReconstructionSegmentationLoss`
        - Metrics: `JaccardIndex`
        - Visualizers: `SegmentationVisualizer`
        - Main metric: `JaccardIndex`
        - Variants:

          - ``light``
          - ``heavy``

    """

    def __init__(self, **kwargs):
        super().__init__(
            **{
                "backbone": "RecSubNet",
                "head": "DiscSubNetHead",
                "loss": "ReconstructionSegmentationLoss",
                "metrics": "JaccardIndex",
                "confusion_matrix_available": False,
                "metrics_params": {
                    "num_classes": 2,
                    "task": "multiclass",
                },
                "visualizer": "SegmentationVisualizer",
            }
            | kwargs
        )

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Params]]:
        return "light", {
            "light": {
                "backbone_variant": "n",
                "head_variant": "n",
            },
            "heavy": {
                "backbone_variant": "l",
                "head_variant": "l",
            },
        }
