"""Draws bounding boxes, class labels, and scores."""

import logging

import torch
from torch import Tensor
from torchvision.utils import draw_bounding_boxes

from luxonis_train.tasks import Tasks

from .base_visualizer import BaseVisualizer
from .utils import (
    Color,
    draw_bounding_box_labels,
    get_color,
    get_prediction_labels,
)


class BBoxVisualizer(BaseVisualizer):
    r"""Visualize bounding box predictions and targets.

    .. figure::
       https://raw.githubusercontent.com/luxonis/luxonis-train/e542cf0efa20a0fc5c781ff505d699031cb0d228/media/example_viz/bbox.png
       :width: 700px
       :height: 350px
       :loading: embed

       The left image shows the targets. The right image shows the
       predictions.

    Inputs:
        - ``prediction_canvas``, ``target_canvas`` (``Tensor``):
          :math:`\left[B, 3, H, W\right]`
        - ``predictions`` (``list[Tensor]``): :math:`\left[M_i,
          6\right]` per image, ``[x1, y1, x2, y2, conf, class]``, pixels
        - ``targets`` (``Tensor | None``): :math:`\left[N, 6\right]`,
          ``[batch, class, x, y, w, h]``, ``xywh`` normalized

    Outputs:
        - ``Tensor | tuple[Tensor, Tensor]``: :math:`\left[B, 3, H,
          W\right]`, a pair when targets are given

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        Draws boxes with ``torchvision`` and local label/color helpers.
        The visualizer stores the ``fill``, ``font``, and ``font_size``
        options but does not use them.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientBBoxHead
              inputs: [RepPANNeck]
              visualizers:
                - name: BBoxVisualizer

    Compatible with:
        - Used by: `DetectionModel`
        - Nodes:

          - `EfficientBBoxHead`
          - `PrecisionBBoxHead`

    """

    supported_tasks = [Tasks.BOUNDINGBOX]

    def __init__(
        self,
        labels: dict[int, str] | list[str] | None = None,
        draw_labels: bool = True,
        draw_scores: bool = False,
        colors: dict[str, Color] | list[Color] | None = None,
        fill: bool = False,
        width: int | None = None,
        font: str | None = None,
        font_size: int | None = None,
        **kwargs,
    ):
        """Initialize the visualizer and resolve the class names and
        colors.

        Args:
            labels (dict[int, str] | list[str] | None): Class names to
                draw. A dictionary maps a class index to a name. A list
                maps by position. When ``None`` or empty, the names come
                from the ``classes`` of the node, so the visualizer then
                needs a ``node``.
            draw_labels (bool): Whether to draw the class name next to
                each box. Defaults to ``True``.
            draw_scores (bool): Whether to write the confidence of each
                predicted box, with two decimals, in its label. Applies
                to the predictions only. Without ``draw_labels``, the
                label is the confidence alone. Defaults to ``False``.
            colors (dict[str, Color] | list[Color] | None): Box colors.
                A dictionary maps a class name to a color. A list maps
                by class index. When ``None``, each class gets a
                distinct color from `get_color`, seeded with its index.
            fill (bool): The drawing methods do not read it. Defaults to
                ``False``.
            width (int | None): Line width of the boxes, in pixels. When
                ``None`` or ``0``, the width is one percent of the
                smaller canvas side, rounded down, and at least ``1``.
            font (str | None): The drawing methods do not read it.
                Defaults to ``None``.
            font_size (int | None): The drawing methods do not read it.
                Defaults to ``None``.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseVisualizer`, such as ``scale`` and ``node``.

        """
        super().__init__(**kwargs)
        if isinstance(labels, list):
            labels = dict(enumerate(labels))

        self._label_dict = labels or self.classes.inverse

        if colors is None:
            colors = {
                label: get_color(i) for i, label in self._label_dict.items()
            }
        if isinstance(colors, list):
            colors = {
                self._label_dict[i]: color for i, color in enumerate(colors)
            }
        self._colors = colors
        self._fill = fill
        self._width = width
        self._font = font
        self._font_size = font_size
        self._draw_labels = draw_labels
        self._draw_scores = draw_scores

    def draw_targets(self, canvas: Tensor, targets: Tensor) -> Tensor:
        """Draw the target boxes of a batch on copies of the canvas
        images.

        The boxes of image ``i`` are the rows of ``targets`` whose first
        column equals ``i``. `draw_bounding_box_labels` converts them
        from normalized ``xywh`` to pixel ``xyxy`` with the canvas size.
        Each box gets the color of its class, and its class name when
        ``draw_labels`` is set.

        Args:
            canvas (``Tensor``): ``uint8`` images of shape
                ``[B, 3, H, W]``. The method does not modify it.
            targets (``Tensor``): Boxes of shape ``[N, 6]`` with rows
                ``[batch_index, class, x, y, w, h]``. The coordinates
                are ``xywh`` normalized to ``[0, 1]``.

        Returns:
            ``Tensor``: A new tensor of the same shape as ``canvas`` with
            the boxes drawn.

        Example:
            >>> import torch
            >>> visualizer = BBoxVisualizer(
            ...     labels=["cat"], colors=["red"], draw_labels=False
            ... )
            >>> canvas = torch.zeros(1, 3, 8, 8, dtype=torch.uint8)
            >>> targets = torch.tensor([[0, 0, 0.25, 0.25, 0.5, 0.5]])
            >>> viz = visualizer.draw_targets(canvas, targets)
            >>> viz.shape
            torch.Size([1, 3, 8, 8])
            >>> bool((viz[0, 0] == 255).any()), bool((viz[0, 1] == 255).any())
            (True, False)

        """
        viz = torch.zeros_like(canvas)

        for i in range(len(canvas)):
            target = targets[targets[:, 0] == i]
            target_classes = target[:, 1].int()
            cls_labels = (
                [self._label_dict[int(c)] for c in target_classes]
                if self._draw_labels and self._label_dict is not None
                else None
            )
            cls_colors = (
                [
                    self._colors[self._label_dict[int(c)]]
                    for c in target_classes
                ]
                if self._colors is not None and self._label_dict is not None
                else None
            )

            *_, H, W = canvas.shape
            width = self._width or max(1, int(min(H, W) / 100))
            viz[i] = draw_bounding_box_labels(
                canvas[i].clone(),
                target[:, 2:],
                width=width,
                labels=cls_labels,
                colors=cls_colors,
            ).to(canvas.device)

        return viz

    def draw_predictions(
        self, canvas: Tensor, predictions: list[Tensor], scale: float = 1.0
    ) -> Tensor:
        """Draw the predicted boxes of a batch on copies of the canvas
        images.

        Each box gets the color of its class. `get_prediction_labels`
        builds its label from the class name, when ``draw_labels`` is
        set, and from the confidence, when ``draw_scores`` is set.

        When ``torchvision`` raises ``ValueError`` for an image, the
        method logs a warning and continues with the input canvas as
        the output. It discards the images drawn before the failure,
        and draws the remaining images into ``canvas`` in place.

        Args:
            canvas (``Tensor``): ``uint8`` images of shape
                ``[B, 3, H, W]``.
            predictions (``list[Tensor]``): One tensor per image, of
                shape ``[M_i, 6]`` with rows
                ``[x1, y1, x2, y2, conf, class]``. The coordinates are
                pixels of the unscaled image.
            scale (float): Multiplier for the box coordinates. Pass the
                factor that scaled the canvas. Defaults to ``1.0``.

        Returns:
            ``Tensor``: The images with the boxes drawn, of the same
            shape as ``canvas``. A new tensor, except after a failure,
            when it is ``canvas`` itself.

        Example:
            >>> import torch
            >>> visualizer = BBoxVisualizer(
            ...     labels=["cat"], colors=["red"], draw_labels=False
            ... )
            >>> canvas = torch.zeros(1, 3, 8, 8, dtype=torch.uint8)
            >>> boxes = [torch.tensor([[2.0, 2.0, 6.0, 6.0, 0.9, 0.0]])]
            >>> viz = visualizer.draw_predictions(canvas, boxes)
            >>> bool((viz[0, 0] == 255).any()), bool((viz[0, 1] == 255).any())
            (True, False)

        """
        viz = torch.zeros_like(canvas)

        for i in range(len(canvas)):
            prediction = predictions[i]

            boxes = prediction[:, :4].clone()
            if scale != 1.0:
                boxes *= scale

            prediction_classes = prediction[..., 5].int()
            cls_labels = get_prediction_labels(
                prediction,
                self._label_dict,
                self._draw_labels,
                self._draw_scores,
            )
            cls_colors = (
                [
                    self._colors[self._label_dict[int(c)]]
                    for c in prediction_classes
                ]
                if self._colors is not None and self._label_dict is not None
                else None
            )

            *_, H, W = canvas.shape
            width = self._width or max(1, int(min(H, W) / 100))
            try:
                viz[i] = draw_bounding_boxes(
                    canvas[i].clone(),
                    boxes,
                    width=width,
                    labels=cls_labels,
                    colors=cls_colors,
                )
            except ValueError as e:
                logging.getLogger(__name__).warning(
                    f"Failed to draw bounding boxes: {e}. Skipping visualization."
                )
                viz = canvas
        return viz

    def forward(
        self,
        prediction_canvas: Tensor,
        target_canvas: Tensor,
        predictions: list[Tensor],
        targets: Tensor | None,
    ) -> tuple[Tensor, Tensor] | Tensor:
        """Draw the predicted boxes, and the target boxes when given.

        Args:
            prediction_canvas (``Tensor``): ``uint8`` images of shape
                ``[B, 3, H, W]`` to draw the predictions on.
            target_canvas (``Tensor``): ``uint8`` images of shape
                ``[B, 3, H, W]`` to draw the targets on.
            predictions (``list[Tensor]``): One tensor per image, of
                shape ``[M_i, 6]`` with rows
                ``[x1, y1, x2, y2, conf, class]`` in pixels.
                `draw_predictions` scales them by the ``scale`` factor.
            targets (``Tensor | None``): Boxes of shape ``[N, 6]`` with
                rows ``[batch_index, class, x, y, w, h]``, ``xywh``
                normalized to ``[0, 1]``. ``None`` when the batch has no
                ``boundingbox`` labels.

        Returns:
            ``tuple[Tensor, Tensor] | Tensor``: The pair
            ``(targets, predictions)`` of drawn images when ``targets``
            is not ``None``; otherwise only the predictions image. Each
            image has the shape of its canvas.

        Example:
            >>> import torch
            >>> visualizer = BBoxVisualizer(labels=["cat"], colors=["red"])
            >>> canvas = torch.zeros(1, 3, 8, 8, dtype=torch.uint8)
            >>> boxes = [torch.tensor([[2.0, 2.0, 6.0, 6.0, 0.9, 0.0]])]
            >>> visualizer(canvas, canvas, boxes, None).shape
            torch.Size([1, 3, 8, 8])
            >>> targets = torch.tensor([[0, 0, 0.25, 0.25, 0.5, 0.5]])
            >>> len(visualizer(canvas, canvas, boxes, targets))
            2

        """
        predictions_viz = self.draw_predictions(
            prediction_canvas, predictions, scale=self._scale
        )
        if targets is None:
            return predictions_viz

        targets_viz = self.draw_targets(target_canvas, targets)
        return targets_viz, predictions_viz
