"""Draws the predicted class name, the label class name, and a bar plot
of the class probabilities.
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import Tensor

from luxonis_train.tasks import Tasks

from .base_visualizer import BaseVisualizer
from .utils import (
    dynamically_determine_font_scale,
    figure_to_torch,
    numpy_to_torch_img,
    torch_img_to_numpy,
)


class ClassificationVisualizer(BaseVisualizer):
    r"""Visualize classification predictions and optional labels.

    .. figure::
       https://raw.githubusercontent.com/luxonis/luxonis-train/e542cf0efa20a0fc5c781ff505d699031cb0d228/media/example_viz/class.png
       :width: 700px
       :height: 262px
       :loading: embed

       The image shows the target class and the predicted class. The
       plot shows the predicted probability of each class.

    Inputs:
        - ``prediction_canvas``, ``target_canvas`` (``Tensor``):
          :math:`\left[B, 3, H, W\right]`
        - ``predictions`` (``Tensor``): :math:`\left[B,
          n_{classes}\right]` logits
        - ``target`` (``Tensor | None``): :math:`\left[B,
          n_{classes}\right]` one-hot, or multi-hot with ``multilabel``

    Outputs:
        - ``Tensor | tuple[Tensor, Tensor]``: :math:`\left[B, 3, H,
          W\right]`, with a probability plot when ``include_plot`` is
          set

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        Renders predicted and target class names with OpenCV and can add
        a Matplotlib probability bar plot.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              visualizers:
                - name: ClassificationVisualizer

    Compatible with:
        - Used by: `ClassificationModel`
        - Nodes:

          - `ClassificationHead`
          - `TransformerClassificationHead`

    """

    supported_tasks = [Tasks.CLASSIFICATION]

    def __init__(
        self,
        include_plot: bool = True,
        font_scale: float | None = None,
        color: tuple[int, int, int] = (255, 0, 0),
        thickness: int = 2,
        multilabel: bool = False,
        **kwargs,
    ):
        """Initialize the visualizer and store the text and plot
        options.

        Args:
            include_plot (bool): Whether `forward` also returns a bar
                plot of the class probabilities as a second image.
                Defaults to ``True``.
            font_scale (float | None): Font scale of the OpenCV text.
                When ``None``, `dynamically_determine_font_scale`
                derives the scale from the image size. The text lines
                then sit at 15 and 25 percent of the image height. A
                value of ``0`` selects the same line positions, but
                keeps the font scale ``0`` and sets the thickness to
                ``1``. Any other value applies as given, together with
                ``thickness``, and puts the text lines at ``y = 50`` and
                ``y = 75`` pixels.
            color (tuple[int, int, int]): RGB color of the text.
                Defaults to ``(255, 0, 0)``, red.
            thickness (int): Thickness of the text strokes. With a
                derived font scale below ``1``, the thickness becomes
                ``1``. Defaults to ``2``.
            multilabel (bool): Whether the task is multi-label. When
                ``True``, the text lists every class whose raw value is
                greater than ``0.5``, and the plot shows sigmoid
                probabilities. When ``False``, the text shows the class
                with the highest value, and the plot shows softmax
                probabilities. Defaults to ``False``.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseVisualizer`, such as ``scale`` and ``node``.

        """
        super().__init__(**kwargs)
        self._include_plot = include_plot
        self._font_scale = font_scale
        self._color = color
        self._thickness = thickness
        self._multilabel = multilabel

    def _get_class_name(self, pred: Tensor) -> str:
        """Return the class name, or names, that ``pred`` selects.

        With ``multilabel``, joins the names of every class whose value
        is greater than ``0.5`` with ``", "``. Otherwise returns the
        name of the class with the highest value.

        Args:
            pred (``Tensor``): Values of shape ``[n_classes]``.

        Returns:
            str: The selected class names.

        """
        if self._multilabel:
            idxs = (pred > 0.5).nonzero(as_tuple=True)[0].tolist()
            return ", ".join([self.classes.inverse[idx] for idx in idxs])
        return self.classes.inverse[int(pred.argmax().item())]

    def _generate_plot(
        self, prediction: Tensor, width: int, height: int
    ) -> Tensor:
        """Render a bar plot of the class probabilities as an image.

        Applies sigmoid with ``multilabel`` and softmax otherwise. The x
        axis lists the class names of the node.

        Args:
            prediction (``Tensor``): Logits of shape ``[n_classes]``.
            width (int): Width of the image, in pixels.
            height (int): Height of the image, in pixels.

        Returns:
            ``Tensor``: A ``uint8`` image of shape ``[3, height, width]``.

        """
        prediction = prediction.to(torch.float32)
        if self._multilabel:
            pred = prediction.sigmoid().detach().cpu().numpy()
        else:
            pred = prediction.softmax(-1).detach().cpu().numpy()
        fig, ax = plt.subplots(figsize=(width / 100, height / 100))
        ax.bar(np.arange(len(pred)), pred)
        ax.set_xticks(np.arange(len(pred)))
        ax.set_xticklabels(self.classes.keys(), rotation=90)
        ax.set_ylim(0, 1)
        ax.set_xlabel("Class")
        ax.set_ylabel("Probability")
        ax.grid(True)
        return figure_to_torch(fig, width, height)

    def forward(
        self,
        prediction_canvas: Tensor,
        target_canvas: Tensor,
        predictions: Tensor,
        target: Tensor | None,
    ) -> Tensor | tuple[Tensor, Tensor]:
        """Write the class names on the images and plot the
        probabilities.

        For each image, the method writes ``Pred: <name>`` on a copy of
        the target canvas image. When ``target`` is given, it writes
        ``GT: <name>`` above it. Both lines use ``color`` and the font
        scale and thickness that ``font_scale`` selects. With
        ``include_plot``, it also renders a bar plot of the class
        probabilities at the size of the prediction canvas.

        Args:
            prediction_canvas (``Tensor``): Images of shape
                ``[B, 3, H, W]``. The method reads only its shape,
                dtype, and device, for the plots.
            target_canvas (``Tensor``): Images of shape ``[B, 3, H, W]``
                to write the text on.
            predictions (``Tensor``): Logits of shape ``[B, n_classes]``.
            target (``Tensor | None``): One-hot labels of shape
                ``[B, n_classes]``, or multi-hot with ``multilabel``.
                ``None`` when the batch has no ``classification``
                labels; then the method writes no ``GT`` line.

        Returns:
            ``Tensor | tuple[Tensor, Tensor]``: With ``include_plot``,
            the pair ``(text_images, plots)``, both of shape
            ``[B, 3, H, W]``. Otherwise only the text images.

        """
        overlay = torch.zeros_like(target_canvas)
        plots = torch.zeros_like(prediction_canvas)
        for i in range(len(overlay)):
            prediction = predictions[i]
            arr = torch_img_to_numpy(target_canvas[i].clone())
            height, width = arr.shape[:2]

            if not self._font_scale:
                font_scale, thickness = dynamically_determine_font_scale(
                    height, width, self._thickness, self._font_scale
                )
                base_y: int = int(height * 0.15)
                line_spacing: int = int(height * 0.1)

                y_gt, y_pred = base_y, base_y + line_spacing
            else:
                font_scale, thickness = self._font_scale, self._thickness
                y_gt, y_pred = 50, 75

            curr_class = self._get_class_name(prediction)
            if target is not None:
                gt = self._get_class_name(target[i])
                arr = cv2.putText(
                    arr,
                    f"GT: {gt}",
                    (5, y_gt),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    font_scale,
                    self._color,
                    thickness,
                )
            arr = cv2.putText(
                arr,
                f"Pred: {curr_class}",
                (5, y_pred),
                cv2.FONT_HERSHEY_SIMPLEX,
                font_scale,
                self._color,
                thickness,
            )

            overlay[i] = numpy_to_torch_img(arr)

            if self._include_plot:
                plots[i] = self._generate_plot(
                    prediction,
                    prediction_canvas.shape[3],
                    prediction_canvas.shape[2],
                )

        if self._include_plot:
            return overlay, plots
        return overlay
