"""Projects the embeddings of a batch to two dimensions with PCA and
draws them colored by identity label.
"""

from collections.abc import Callable

import numpy as np
import seaborn as sns
from loguru import logger
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA
from torch import Tensor

from luxonis_train.tasks import Tasks

from .base_visualizer import BaseVisualizer
from .utils import figure_to_torch


class EmbeddingsVisualizer(BaseVisualizer):
    r"""Visualize embedding spaces as two-dimensional plots.

    Inputs:
        - ``prediction_canvas``, ``target_canvas`` (``Tensor``):
          :math:`\left[B, 3, H, W\right]`
        - ``predictions`` (``Tensor``): :math:`\left[B, D\right]`
          embeddings
        - ``target`` (``Tensor``): :math:`\left[B\right]` identity
          labels

    Outputs:
        - ``tuple[Tensor, Tensor]``: :math:`\left[1, 3, 512, 512\right]`
          KDE and scatter plots of the 2-D PCA

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        Projects embeddings with PCA, filters z-score outliers, and
        renders Seaborn plots as tensors.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``GhostFaceNetHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: GhostFaceNetHead
              inputs: [GhostFaceNet]
              visualizers:
                - name: EmbeddingsVisualizer

    Compatible with:
        - Used by: `EmbeddingsModel`
        - Nodes: `GhostFaceNetHead`

    """

    supported_tasks = [Tasks.EMBEDDINGS]

    def __init__(self, z_score_threshold: float = 3, **kwargs):
        """Initialize the visualizer and store the outlier threshold.

        Args:
            z_score_threshold (float): Limit for the absolute z-score of
                a projected point. `forward` keeps a point only when the
                absolute z-score of each of its two coordinates is below
                the limit. The z-scores use the mean and the standard
                deviation of the batch on each axis. Defaults to ``3``.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseVisualizer`, such as ``scale`` and ``node``.

        """
        super().__init__(**kwargs)
        self._z_score_threshold = z_score_threshold

    def _get_color(self, label: int) -> tuple[float, float, float]:
        """Return the color of a label from `BaseVisualizer.colormap`,
        scaled to ``[0, 1]``.

        Args:
            label (int): Identity label.

        Returns:
            tuple[float, float, float]: RGB components for Matplotlib.

        """
        r, g, b = self.colormap[label]
        return r / 255, g / 255, b / 255

    def forward(
        self,
        prediction_canvas: Tensor,
        target_canvas: Tensor,
        predictions: Tensor,
        target: Tensor,
    ) -> tuple[Tensor, Tensor]:
        """Project the embeddings to two dimensions and plot them.

        The method replaces ``NaN`` and infinite values with ``0``. When
        ``predictions`` is a CPU tensor, this replacement writes into
        it. Then it fits a two-component PCA with ``random_state=42``.
        When the explained variance of the second component is below
        ``1e-12``, the embeddings are effectively one-dimensional. The
        method then fixes the sign of the first projected coordinates.
        It computes their dot product with the row sums of the
        embeddings and flips the coordinates when the product is
        negative. Next, `_filter_outliers` drops the points whose
        absolute z-score reaches ``z_score_threshold`` on either axis.
        Finally it renders a KDE plot and a scatter plot with
        `kde_plot` and `scatter_plot`. The method ignores both
        canvases.

        Logs the number of dropped outliers at the ``INFO`` level.

        Args:
            prediction_canvas (``Tensor``): Ignored.
            target_canvas (``Tensor``): Ignored.
            predictions (``Tensor``): Embeddings of shape ``[B, D]``.
            target (``Tensor``): The ``id`` metadata label of each
                embedding, of shape ``[B]``. The method casts it to
                ``int``.

        Returns:
            ``tuple[Tensor, Tensor]``: The KDE plot and the scatter plot,
            each a ``uint8`` image of shape ``[1, 3, 512, 512]``.

        """
        embeddings_np = predictions.detach().cpu().numpy()
        embeddings_np[np.isnan(embeddings_np) | np.isinf(embeddings_np)] = 0.0
        ids_np = target.detach().cpu().numpy().astype(int)

        pca = PCA(n_components=2, random_state=42)
        embeddings_2d = pca.fit_transform(embeddings_np)
        if (
            pca.explained_variance_.shape[0] > 1
            and pca.explained_variance_[1] < 1e-12
        ):
            # Stabilize PCA sign when embeddings are effectively 1-D.
            ref = embeddings_np.sum(axis=1)
            if np.dot(embeddings_2d[:, 0], ref) < 0:
                embeddings_2d[:, 0] *= -1
        embeddings_2d, ids_np = self._filter_outliers(embeddings_2d, ids_np)

        kdeplot = self.plot_to_tensor(embeddings_2d, ids_np, self.kde_plot)
        scatterplot = self.plot_to_tensor(
            embeddings_2d, ids_np, self.scatter_plot
        )

        return kdeplot, scatterplot

    def _filter_outliers(
        self, points: np.ndarray, ids: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        """Drop the points whose absolute z-score reaches the threshold
        on any axis.

        The z-scores use the mean and the standard deviation of the
        points on each axis. An axis with a standard deviation of ``0``
        gives ``NaN`` z-scores, and then the method drops every point.
        Logs the number of dropped points at the ``INFO`` level.

        Args:
            points (``np.ndarray``): Projected points of shape ``[N, 2]``.
            ids (``np.ndarray``): Labels of shape ``[N]``.

        Returns:
            ``tuple[np.ndarray, np.ndarray]``: The kept points and their
            labels.

        """
        mean = np.mean(points, axis=0)
        std_dev = np.std(points, axis=0)
        z_scores = (points - mean) / std_dev

        mask = (np.abs(z_scores) < self._z_score_threshold).all(axis=1)
        logger.info(f"Filtered out {len(points) - mask.sum()} outliers")
        return points[mask], ids[mask]

    @staticmethod
    def plot_to_tensor(
        embeddings_2d: np.ndarray,
        ids_np: np.ndarray,
        plot_func: Callable[[plt.Axes, np.ndarray, np.ndarray], None],
    ) -> Tensor:
        """Render a plot of the projected embeddings as an image tensor.

        Creates a ``10 x 10`` inch figure and limits both axes to the
        range of the points. Then it calls ``plot_func`` on the axes,
        hides the axes, and converts the figure with `figure_to_torch`.

        Args:
            embeddings_2d (``np.ndarray``): Projected points of shape
                ``[N, 2]``. May be empty; then the axis limits stay at
                their defaults.
            ids_np (``np.ndarray``): Labels of shape ``[N]``.
            plot_func (``Callable[[plt.Axes, np.ndarray, np.ndarray], None]``):
                Draws on the axes it receives, for example `kde_plot` or
                `scatter_plot`.

        Returns:
            ``Tensor``: A ``uint8`` image of shape ``[1, 3, 512, 512]``.

        Example:
            >>> import numpy as np
            >>> def no_op(ax, points, labels):
            ...     pass
            >>> EmbeddingsVisualizer.plot_to_tensor(
            ...     np.zeros((0, 2)), np.zeros(0, dtype=int), no_op
            ... ).shape
            torch.Size([1, 3, 512, 512])

        """
        fig, ax = plt.subplots(figsize=(10, 10))
        if embeddings_2d.size > 0:
            ax.set_xlim(embeddings_2d[:, 0].min(), embeddings_2d[:, 0].max())
            ax.set_ylim(embeddings_2d[:, 1].min(), embeddings_2d[:, 1].max())

        plot_func(ax, embeddings_2d, ids_np)
        ax.axis("off")

        tensor_image = figure_to_torch(fig, width=512, height=512).unsqueeze(0)
        plt.close(fig)
        return tensor_image

    def kde_plot(
        self, ax: plt.Axes, emb: np.ndarray, labels: np.ndarray
    ) -> None:
        """Draw one filled KDE per label on the axes.

        Each label gets its color from `BaseVisualizer.colormap`. The
        KDE uses ``bw_adjust=1.5`` and ``alpha=0.9``.
        ``warn_singular=False`` silences the Seaborn warning for a label
        whose points cannot form a density.

        Args:
            ax (``plt.Axes``): Axes to draw on.
            emb (``np.ndarray``): Projected points of shape ``[N, 2]``.
            labels (``np.ndarray``): Label of each point, of shape
                ``[N]``.

        """
        for label in np.unique(labels):
            subset = emb[labels == label]
            color = self._get_color(label)
            sns.kdeplot(
                x=subset[:, 0],
                y=subset[:, 1],
                color=color,
                alpha=0.9,
                bw_adjust=1.5,
                fill=True,
                warn_singular=False,
                ax=ax,
            )

    def scatter_plot(
        self, ax: plt.Axes, emb: np.ndarray, labels: np.ndarray
    ) -> None:
        """Draw all points on the axes, colored by label.

        Uses ``s=300``, ``alpha=0.9``, and no legend. The palette maps
        each label to its color in `BaseVisualizer.colormap`.

        Args:
            ax (``plt.Axes``): Axes to draw on.
            emb (``np.ndarray``): Projected points of shape ``[N, 2]``.
            labels (``np.ndarray``): Label of each point, of shape
                ``[N]``.

        """
        unique_labels = np.unique(labels)
        palette = {label: self._get_color(label) for label in unique_labels}
        sns.scatterplot(
            x=emb[:, 0],
            y=emb[:, 1],
            hue=labels,
            palette=palette,
            alpha=0.9,
            s=300,
            legend=False,
            ax=ax,
        )
