"""The RepPAN neck of YOLOv6, which merges the backbone features top
down and then bottom up.
"""

from typing import Literal

from loguru import logger
from luxonis_ml.typing import Kwargs
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.base_node import BaseNode
from luxonis_train.utils import make_divisible
from luxonis_train.variants import add_variant_aliases

from .blocks import CSPDownBlock, CSPUpBlock, RepDownBlock, RepUpBlock


class RepPANNeck(BaseNode):
    """RepPAN neck of YOLOv6 that fuses features across scales.

    The neck reads all outputs of the input node and uses the last
    ``n_heads`` feature maps. A top-down path carries the features of
    the coarse maps to the finer maps. A bottom-up path then carries
    the fused features back to the coarse maps. The neck returns one
    fused map for each of the ``n_heads`` scales.

    Inputs:
        - ``inputs`` (``list[Tensor]``): ``[B, C_i, H_i, W_i]`` per
          map, finest first; each of the last ``n_heads - 1`` maps has
          half the height and width of the map before it

    Outputs:
        - ``features`` (``list[Tensor]``): ``n_heads`` maps, finest
          first, with the height and width of the last ``n_heads``
          inputs; strides 8, 16, 32 after `EfficientRep` with
          ``n_heads=3``

    References:
        - Source: Reimplemented from `YOLOv6: A Single-Stage Object
          Detection Framework for Industrial Applications
          <https://arxiv.org/abs/2209.02976>`_.
        - License: Apache-2.0 (this project)

    Notes:
        Each top-down step is a `RepUpBlock` or a `CSPUpBlock`. It
        upsamples the current map and fuses it with the next finer
        input. Each bottom-up step is a `RepDownBlock` or a
        `CSPDownBlock`. It downsamples the current map. Then it fuses
        the result with the ``1x1`` convolution output that the top-down
        path kept at the same scale. The ``block`` argument selects the
        type of the steps.

    Variants:
        - ``"n"``:
            - Default: yes
            - Aliases: ``"nano"``
            - Parameters:
                - ``depth_multiplier``: ``0.33``
                - ``width_multiplier``: ``0.25``
                - ``block``: ``"RepBlock"``
        - ``"s"``:
            - Default: no
            - Aliases: ``"small"``
            - Parameters:
                - ``depth_multiplier``: ``0.33``
                - ``width_multiplier``: ``0.50``
                - ``block``: ``"RepBlock"``
        - ``"m"``:
            - Default: no
            - Aliases: ``"medium"``
            - Parameters:
                - ``depth_multiplier``: ``0.60``
                - ``width_multiplier``: ``0.75``
                - ``block``: ``"CSPStackRepBlock"``
                - ``e``: ``2 / 3``
        - ``"l"``:
            - Default: no
            - Aliases: ``"large"``
            - Parameters:
                - ``depth_multiplier``: ``1.0``
                - ``width_multiplier``: ``1.0``
                - ``block``: ``"CSPStackRepBlock"``
                - ``e``: ``1 / 2``

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: RepPANNeck
              inputs: [EfficientRep]
              variant: n

    Compatible with:
        - Attach index: ``"all"``, every output of the input node
        - Used by:

          - `DetectionModel`
          - `InstanceSegmentationModel`
          - `KeypointDetectionModel`

        - Pretrained weights: available through ``weights: download``

    """

    in_channels: list[int]
    in_width: list[int]
    in_height: list[int]

    def __init__(
        self,
        n_heads: Literal[2, 3, 4] = 3,
        channels_list: list[int] | None = None,
        n_repeats: list[int] | None = None,
        depth_multiplier: float = 0.33,
        width_multiplier: float = 0.25,
        block: Literal["RepBlock", "CSPStackRepBlock"] = "RepBlock",
        e: float | None = None,
        weights: str = "yolo",
        **kwargs,
    ):
        """Build the fusion steps for ``n_heads`` scales.

        The neck reads the channels and the sizes of its inputs from
        ``input_shapes``, or from ``in_sizes`` when it is set. It logs a
        warning when the height or the width of ``original_in_shape`` is
        not divisible by ``32``.

        In this description, ``channels_list`` and ``n_repeats`` hold
        the values after the multipliers scale them. For three heads,
        the two lists describe the four steps in this order:

        - top-down step 1: ``channels_list[0]`` output channels and
          ``n_repeats[0]`` blocks;
        - top-down step 2: ``channels_list[1]`` output channels and
          ``n_repeats[1]`` blocks;
        - bottom-up step 1: ``channels_list[2]`` channels after the
          downsampling, ``channels_list[3]`` output channels, and
          ``n_repeats[2]`` blocks;
        - bottom-up step 2: ``channels_list[4]`` channels after the
          downsampling, ``channels_list[5]`` output channels, and
          ``n_repeats[3]`` blocks.

        The outputs thus have ``channels_list[1]``, ``channels_list[3]``,
        and ``channels_list[5]`` channels.

        Two heads keep only top-down step 1 and bottom-up step 2. The
        outputs then have ``channels_list[0]`` and ``channels_list[5]``
        channels.

        Four heads add a third top-down step with
        ``channels_list[1] // 2`` output channels and ``n_repeats[1]``
        blocks. They also add a first bottom-up step with
        ``channels_list[1] // 2`` channels after the downsampling,
        ``channels_list[1]`` output channels, and ``n_repeats[2]`` blocks.
        The outputs then have ``channels_list[1] // 2``,
        ``channels_list[1]``, ``channels_list[3]``, and
        ``channels_list[5]`` channels.

        Args:
            n_heads (``Literal[2, 3, 4]``): Number of scales that the neck
                fuses and returns. It is usually equal to the ``n_heads``
                of the head after the neck. Defaults to ``3``.
            channels_list (list[int] | None): Six channel counts for the
                steps, before ``width_multiplier`` scales them. Extra
                items have no effect. ``None`` or an empty list selects
                ``[256, 128, 128, 256, 256, 512]``.
            n_repeats (list[int] | None): Four numbers of RepVGG-style
                blocks for the steps, before ``depth_multiplier`` scales
                them. ``None`` or an empty list selects
                ``[12, 12, 12, 12]``.
            depth_multiplier (float): Factor for each ``n_repeats`` value
                above ``1``. The neck rounds the result with the Python
                ``round``, with a minimum of ``1``. Values of ``1`` or
                less do not change. Defaults to ``0.33``.
            width_multiplier (float): Factor for each ``channels_list``
                value. The neck rounds the result up to a multiple of
                ``8``. Defaults to ``0.25``.
            block (``Literal["RepBlock", "CSPStackRepBlock"]``): Type of
                the steps. ``"RepBlock"`` builds `RepUpBlock` and
                `RepDownBlock`. ``"CSPStackRepBlock"`` builds `CSPUpBlock`
                and `CSPDownBlock`. The neck does not check the value,
                so any other string also builds the CSP steps. Defaults
                to ``"RepBlock"``.
            e (float | None): Fraction of the output channels in each path
                of a `CSPStackRepBlock`. The neck reads it only when
                ``block`` is ``"CSPStackRepBlock"``. ``None`` or ``0``
                selects ``0.5``. Defaults to ``None``.
            weights (str): Source or initialization method of the weights,
                as in `BaseNode`. ``"download"`` loads the COCO checkpoint
                from `get_weights_url`. The download needs a variant,
                because the URL holds the variant name. Defaults to
                ``"yolo"``.
            **kwargs (``Any``): Keyword arguments for `BaseNode`, such as
                ``input_shapes`` and ``original_in_shape``.

        Raises:
            ValueError: When ``attach_index`` is ``"all"`` and an input
                map has the wrong size. Each of the last ``n_heads - 1``
                maps must have half the height and the width of the map
                before it. Also when ``n_heads`` is not ``2``, ``3``, or
                ``4``.
            RuntimeError: When ``kwargs`` has no ``original_in_shape``,
                or has neither ``input_shapes`` nor ``in_sizes``.

        """
        super().__init__(weights=weights, **kwargs)

        self._validate_input_shapes(n_heads)

        self._n_heads = n_heads

        channels_list, n_repeats = self._scale_channels_and_repeats(
            channels_list, n_repeats, width_multiplier, depth_multiplier
        )
        channels_list, n_repeats = self._fit_to_n_heads(
            channels_list, n_repeats
        )

        self.up_blocks, up_out_channel_list, last_out_channels = (
            self._build_up_blocks(n_heads, block, channels_list, n_repeats, e)
        )
        self.down_blocks = self._build_down_blocks(
            n_heads,
            block,
            channels_list,
            n_repeats,
            up_out_channel_list,
            last_out_channels,
            e,
        )

    def _validate_input_shapes(self, n_heads: int) -> None:
        if (
            self.original_in_shape[-1] % 32 != 0
            or self.original_in_shape[-2] % 32 != 0
        ):
            logger.warning(
                "Image dimensions should be divisible by 32,"
                f"but got {self.original_in_shape}. "
                "This may cause 'RepPANNeck' to crash."
            )

        for i in range(1, n_heads):
            if (
                self.in_width[-i] * 2 != self.in_width[-i - 1]
                or self.in_height[-i] * 2 != self.in_height[-i - 1]
            ) and self.attach_index == "all":
                # TODO: fix the attach_index and this condition
                raise ValueError(
                    f"Expected width and height of feature map at index "
                    f"{len(self.in_width) - i} to be half of those at "
                    f"index {len(self.in_width) - i - 1}. "
                    f"Image shape {self.original_in_shape} must be "
                    "divisible by 32 to avoid 'RepPANNeck' crashing."
                )

    @staticmethod
    def _scale_channels_and_repeats(
        channels_list: list[int] | None,
        n_repeats: list[int] | None,
        width_multiplier: float,
        depth_multiplier: float,
    ) -> tuple[list[int], list[int]]:
        channels_list = channels_list or [256, 128, 128, 256, 256, 512]
        n_repeats = n_repeats or [12, 12, 12, 12]
        channels_list = [
            make_divisible(ch * width_multiplier, 8) for ch in channels_list
        ]
        n_repeats = [
            (max(round(i * depth_multiplier), 1) if i > 1 else i)
            for i in n_repeats
        ]
        return channels_list, n_repeats

    def _build_up_blocks(
        self,
        n_heads: int,
        block: str,
        channels_list: list[int],
        n_repeats: list[int],
        e: float | None,
    ) -> tuple[nn.ModuleList, list[int], int]:
        up_blocks = nn.ModuleList()

        in_channels = self.in_channels[-1]
        out_channels = channels_list[0]
        in_channels_next = self.in_channels[-2]
        curr_n_repeats = n_repeats[0]
        up_out_channel_list = [in_channels]  # used in DownBlocks

        for i in range(1, n_heads):
            curr_up_block = (
                RepUpBlock(
                    in_channels=in_channels,
                    in_channels_next=in_channels_next,
                    out_channels=out_channels,
                    n_repeats=curr_n_repeats,
                )
                if block == "RepBlock"
                else CSPUpBlock(
                    in_channels=in_channels,
                    in_channels_next=in_channels_next,
                    out_channels=out_channels,
                    n_repeats=curr_n_repeats,
                    e=e or 0.5,
                )
            )
            up_out_channel_list.append(out_channels)
            up_blocks.append(curr_up_block)
            if len(up_blocks) == (n_heads - 1):
                up_out_channel_list.reverse()
                break

            in_channels = out_channels
            out_channels = channels_list[i]
            in_channels_next = self.in_channels[-1 - (i + 1)]
            curr_n_repeats = n_repeats[i]

        return up_blocks, up_out_channel_list, out_channels

    def _build_down_blocks(
        self,
        n_heads: int,
        block: str,
        channels_list: list[int],
        n_repeats: list[int],
        up_out_channel_list: list[int],
        in_channels: int,
        e: float | None,
    ) -> nn.ModuleList:
        down_blocks = nn.ModuleList()
        channels_list_down_blocks = channels_list[(n_heads - 1) :]
        n_repeats_down_blocks = n_repeats[(n_heads - 1) :]

        downsample_out_channels = channels_list_down_blocks[0]
        in_channels_next = up_out_channel_list[0]
        out_channels = channels_list_down_blocks[1]
        curr_n_repeats = n_repeats_down_blocks[0]

        for i in range(1, n_heads):
            curr_down_block = (
                RepDownBlock(
                    in_channels=in_channels,
                    downsample_out_channels=downsample_out_channels,
                    in_channels_next=in_channels_next,
                    out_channels=out_channels,
                    n_repeats=curr_n_repeats,
                )
                if block == "RepBlock"
                else CSPDownBlock(
                    in_channels=in_channels,
                    downsample_out_channels=downsample_out_channels,
                    in_channels_next=in_channels_next,
                    out_channels=out_channels,
                    n_repeats=curr_n_repeats,
                    e=e or 0.5,
                )
            )
            down_blocks.append(curr_down_block)
            if len(down_blocks) == (n_heads - 1):
                break

            in_channels = out_channels
            downsample_out_channels = channels_list_down_blocks[2 * i]
            in_channels_next = up_out_channel_list[i]
            out_channels = channels_list_down_blocks[2 * i + 1]
            curr_n_repeats = n_repeats_down_blocks[i]

        return down_blocks

    def forward(self, inputs: list[Tensor]) -> list[Tensor]:
        """Fuse the last ``n_heads`` feature maps top down, then bottom up.

        The top-down path starts at the coarsest map, ``inputs[-1]``.
        Each top-down step fuses the current map with the next finer
        input and keeps the output of its ``1x1`` convolution. The
        bottom-up path starts at the finest fused map. Each bottom-up
        step fuses the current map with the kept output at the next
        coarser scale. The neck ignores the inputs before the last
        ``n_heads`` maps.

        Args:
            inputs (``list[Tensor]``): Feature maps of shape
                ``[B, C_i, H_i, W_i]``, finest first. The channels must
                match the input sizes that the constructor got. Each of
                the last ``n_heads - 1`` maps has half the height and the
                width of the map before it.

        Returns:
            ``list[Tensor]``: ``n_heads`` fused maps, finest first. Each
            map has the height and the width of the input at its scale. For
            three heads, the maps have ``channels_list[1]``,
            ``channels_list[3]``, and ``channels_list[5]`` channels, after
            ``width_multiplier`` scales them. The constructor docstring
            gives the channels for two and four heads.

        Example:
            >>> import torch
            >>> from luxonis_train.nodes import RepPANNeck
            >>> shapes = [(1, 16, 32, 32), (1, 32, 16, 16), (1, 64, 8, 8)]
            >>> inputs = [torch.zeros(shape) for shape in shapes]
            >>> kwargs = {
            ...     "input_shapes": [{"features": [x.shape for x in inputs]}],
            ...     "original_in_shape": torch.Size([3, 256, 256]),
            ... }
            >>> [tuple(out.shape) for out in RepPANNeck(**kwargs)(inputs)]
            [(1, 32, 32, 32), (1, 64, 16, 16), (1, 128, 8, 8)]

            With two heads, the neck ignores the first map:

            >>> neck = RepPANNeck(n_heads=2, **kwargs)
            >>> [tuple(out.shape) for out in neck(inputs)]
            [(1, 64, 16, 16), (1, 128, 8, 8)]

        """
        x = inputs[-1]
        up_block_outs: list[Tensor] = []
        for up_block, input_ in zip(
            self.up_blocks, inputs[-2::-1], strict=False
        ):
            conv_out, x = up_block(x, input_)
            up_block_outs.append(conv_out)

        outs = [x]
        for down_block, up_out in zip(
            self.down_blocks, reversed(up_block_outs), strict=True
        ):
            x = down_block(x, up_out)
            outs.append(x)
        return outs

    @override
    def get_weights_url(self) -> str:
        return f"{{github}}/reppanneck_{self.variant[0]}_coco.ckpt"

    @override
    @staticmethod
    def get_variants() -> tuple[str, dict[str, Kwargs]]:
        """Return the default variant ``"n"`` and the four size variants.

        The ``"n"`` and ``"s"`` variants build ``"RepBlock"`` steps. The
        ``"m"`` and ``"l"`` variants build ``"CSPStackRepBlock"`` steps.
        Each variant sets ``depth_multiplier``, ``width_multiplier``, and
        ``block``. The ``"m"`` and ``"l"`` variants also set ``e``.
        `add_variant_aliases` adds the aliases ``"nano"``, ``"small"``,
        ``"medium"``, and ``"large"``. Each alias refers to the same
        dictionary as its short name.

        Returns:
            ``tuple[str, dict[str, Kwargs]]``: The name ``"n"``, and a
            dictionary that maps each variant name and alias to its
            constructor keyword arguments.

        Example:
            >>> from luxonis_train.nodes import RepPANNeck
            >>> default, variants = RepPANNeck.get_variants()
            >>> default, sorted(variants)
            ('n', ['l', 'large', 'm', 'medium', 'n', 'nano', 's', 'small'])
            >>> variants["large"] is variants["l"]
            True
            >>> variants["m"]["block"], round(variants["m"]["e"], 3)
            ('CSPStackRepBlock', 0.667)

        """
        return "n", add_variant_aliases(
            {
                "n": {
                    "depth_multiplier": 0.33,
                    "width_multiplier": 0.25,
                    "block": "RepBlock",
                },
                "s": {
                    "depth_multiplier": 0.33,
                    "width_multiplier": 0.50,
                    "block": "RepBlock",
                },
                "m": {
                    "depth_multiplier": 0.60,
                    "width_multiplier": 0.75,
                    "block": "CSPStackRepBlock",
                    "e": 2 / 3,
                },
                "l": {
                    "depth_multiplier": 1.0,
                    "width_multiplier": 1.0,
                    "block": "CSPStackRepBlock",
                    "e": 1 / 2,
                },
            }
        )

    def _fit_to_n_heads(
        self, channels_list: list[int], n_repeats: list[int]
    ) -> tuple[list[int], list[int]]:
        """Adapt the scaled step lists to ``n_heads``.

        Two heads keep the items ``0``, ``4``, and ``5`` of
        ``channels_list`` and the items ``0`` and ``3`` of ``n_repeats``.
        Three heads keep both lists unchanged. Four heads insert a
        top-down step and a bottom-up step. Their channel counts come from
        ``channels_list[1]``. Their block counts repeat the items ``1``
        and ``2`` of ``n_repeats``.

        Args:
            channels_list (list[int]): Channel counts after
                ``width_multiplier`` scales them.
            n_repeats (list[int]): Block counts after ``depth_multiplier``
                scales them.

        Returns:
            tuple[list[int], list[int]]: The adapted ``channels_list``
            and ``n_repeats``.

        Raises:
            ValueError: When ``n_heads`` is not ``2``, ``3``, or ``4``.

        """
        if self._n_heads == 2:
            channels_list = [channels_list[i] for i in [0, 4, 5]]
            n_repeats = [n_repeats[0], n_repeats[3]]
        elif self._n_heads == 3:
            return channels_list, n_repeats
        elif self._n_heads == 4:
            channels_list = [
                channels_list[0],
                channels_list[1],
                channels_list[1] // 2,
                channels_list[1] // 2,
                channels_list[1],
                channels_list[2],
                channels_list[3],
                channels_list[4],
                channels_list[5],
            ]
            n_repeats = [n_repeats[i] for i in [0, 1, 1, 2, 2, 3]]
        else:
            raise ValueError(
                f"Specified number of heads ({self._n_heads}) not supported."
                "The number of heads should be 2, 3 or 4."
            )

        return channels_list, n_repeats
