"""The instance keypoint detection model."""

from luxonis_ml.typing import Params
from typing_extensions import override

from luxonis_train.config.predefined_models.base_predefined_model import (
    SimplePredefinedModel,
)


class KeypointDetectionModel(SimplePredefinedModel):
    """Instance keypoint detection, which predicts a box and its
    keypoints together.

    Throughput:
        Frames per second at 384x512.

        - ``light``: 45 on RVC2, 137 on RVC4
        - ``medium``: 24 on RVC2, 120 on RVC4
        - ``heavy``: 7 on RVC2, 101 on RVC4

    Notes:
        Set ``per_class_metrics`` to log ``kpt_map``, ``kpt_mar``, and
        ``kpt_f1`` for each class.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        The ``model`` section of a config:

        .. code-block:: yaml

            model:
              predefined_model:
                name: KeypointDetectionModel
                params:
                  variant: light

    Components:
        - Nodes: `EfficientRep` -> `RepPANNeck` -> `EfficientKeypointBBoxHead`
        - Losses: `EfficientKeypointBBoxLoss`
        - Metrics:

          - `ConfusionMatrix`
          - `MeanAveragePrecision`
          - `ObjectKeypointSimilarity`

        - Visualizers: `KeypointVisualizer`
        - Main metric: `MeanAveragePrecision`
        - Variants:

          - ``light``
          - ``medium``
          - ``heavy``

    """

    def __init__(self, **kwargs):
        super().__init__(
            **{
                "backbone": "EfficientRep",
                "neck": "RepPANNeck",
                "head": "EfficientKeypointBBoxHead",
                "loss": "EfficientKeypointBBoxLoss",
                "metrics": [
                    "ObjectKeypointSimilarity",
                    "MeanAveragePrecision",
                ],
                "confusion_matrix_available": True,
                "main_metric": "MeanAveragePrecision",
                "visualizer": "KeypointVisualizer",
            }
            | kwargs
        )

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Params]]:
        return "light", {
            "light": {
                "backbone_params": {"weights": "download"},
                "backbone_variant": "n",
                "neck_params": {"weights": "download"},
                "neck_variant": "n",
            },
            "medium": {
                "backbone_params": {"weights": "download"},
                "backbone_variant": "s",
                "neck_params": {"weights": "download"},
                "neck_variant": "s",
            },
            "heavy": {
                "backbone_params": {"weights": "download"},
                "backbone_variant": "l",
                "neck_params": {"weights": "download"},
                "neck_variant": "l",
            },
        }
