"""The instance segmentation model."""

from luxonis_ml.typing import Params
from typing_extensions import override

from luxonis_train.config.predefined_models.base_predefined_model import (
    SimplePredefinedModel,
)


class InstanceSegmentationModel(SimplePredefinedModel):
    """Instance segmentation, which predicts a mask for each detected
    object.

    Throughput:
        Frames per second at 384x512.

        - ``light``: 39 on RVC2, 223 on RVC4
        - ``medium``: 19 on RVC2, 184 on RVC4
        - ``heavy``: 7 on RVC2, 107 on RVC4

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        The ``model`` section of a config:

        .. code-block:: yaml

            model:
              predefined_model:
                name: InstanceSegmentationModel
                params:
                  variant: light

    Components:
        - Nodes: `EfficientRep` -> `RepPANNeck` -> `PrecisionSegmentBBoxHead`
        - Losses: `PrecisionDFLSegmentationLoss`
        - Metrics: `ConfusionMatrix`, `MeanAveragePrecision`
        - Visualizers: `InstanceSegmentationVisualizer`
        - Main metric: `MeanAveragePrecision`
        - Variants: ``light``, ``medium``, ``heavy``

    """

    def __init__(self, **kwargs):
        super().__init__(
            **{
                "backbone": "EfficientRep",
                "neck": "RepPANNeck",
                "head": "PrecisionSegmentBBoxHead",
                "loss": "PrecisionDFLSegmentationLoss",
                "metrics": "MeanAveragePrecision",
                "confusion_matrix_available": True,
                "visualizer": "InstanceSegmentationVisualizer",
            }
            | kwargs
        )

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Params]]:
        return "light", {
            "light": {
                "backbone_params": {"weights": "download"},
                "backbone_variant": "n",
                "neck_params": {"weights": "download"},
                "neck_variant": "n",
            },
            "medium": {
                "backbone_params": {"weights": "download"},
                "backbone_variant": "s",
                "neck_params": {"weights": "download"},
                "neck_variant": "s",
            },
            "heavy": {
                "backbone_variant": "l",
                "backbone_params": {"weights": "download"},
                "neck_variant": "l",
                "neck_params": {"weights": "download"},
            },
        }
