"""The factory that returns the confusion matrix for the task of a
node.
"""

from luxonis_train.nodes.base_node import BaseNode
from luxonis_train.registry import METRICS
from luxonis_train.tasks import Tasks

from .detection_confusion_matrix import DetectionConfusionMatrix
from .fomo_confusion_matrix import FomoConfusionMatrix
from .instance_segmentation_confusion_matrix import (
    InstanceSegmentationConfusionMatrix,
)
from .recognition_confusion_matrix import RecognitionConfusionMatrix


@METRICS.register()  # type: ignore
class ConfusionMatrix:
    """Factory class for Confusion Matrix metrics.

    Creates the appropriate Confusion Matrix based on the task of the node.

    Inputs:
        - the attached node and the metric parameters

    Outputs:
        - the confusion matrix metric for the node's task

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        Registry-facing factory that returns the concrete confusion
        matrix implementation for the attached node task.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              metrics:
                - name: ConfusionMatrix

    Compatible with:
        - Used by: ``ClassificationModel``, ``DetectionModel``, ``FOMOModel``,
          ``InstanceSegmentationModel``, ``KeypointDetectionModel``,
          ``SegmentationModel``
        - Nodes: ``BiSeNetHead``, ``ClassificationHead``,
          ``DDRNetSegmentationHead``, ``EfficientBBoxHead``,
          ``EfficientKeypointBBoxHead``, ``FOMOHead``, ``PrecisionBBoxHead``,
          ``PrecisionSegmentBBoxHead``, ``SegmentationHead``,
          ``TransformerClassificationHead``, ``TransformerSegmentationHead``

    """

    def __new__(
        cls, node: BaseNode, **kwargs
    ) -> (
        RecognitionConfusionMatrix
        | DetectionConfusionMatrix
        | InstanceSegmentationConfusionMatrix
    ):
        match node.task:
            case None:  # pragma: no cover
                raise ValueError(
                    f"Node {node.name} does not have the 'task' parameter set"
                )
            case Tasks.CLASSIFICATION | Tasks.SEGMENTATION:
                return RecognitionConfusionMatrix(node=node, **kwargs)
            case Tasks.BOUNDINGBOX | Tasks.INSTANCE_KEYPOINTS:
                return DetectionConfusionMatrix(node=node, **kwargs)
            case Tasks.INSTANCE_SEGMENTATION:
                return InstanceSegmentationConfusionMatrix(node=node, **kwargs)
            case Tasks.FOMO:
                return FomoConfusionMatrix(node=node, **kwargs)
            case _:  # pragma: no cover
                raise ValueError(
                    f"'ConfusionMatrix' does not support task '{node.task.name}'"
                )
