"""The confusion matrix for bounding boxes, which matches predictions to
labels by IoU.
"""

import torch
from torch import Tensor
from torchvision.ops import box_convert, box_iou
from typing_extensions import override

from luxonis_train.attached_modules.metrics import BaseMetric
from luxonis_train.tasks import Tasks
from luxonis_train.utils.general import instances_from_batch

from .utils import compute_mcc


class DetectionConfusionMatrix(BaseMetric):
    r"""Confusion matrix for bounding box predictions.

    Inputs:
        - ``boundingbox`` (``list[Tensor]``): :math:`\left[M_i,
          6\right]` per image, ``[x1, y1, x2, y2, conf, class]``, pixels
        - ``target_boundingbox`` (``Tensor``): :math:`\left[N,
          6\right]`, ``[batch, class, x, y, w, h]``, ``xywh`` normalized

    Outputs:
        - ``mcc`` (``Tensor``): scalar MCC of the whole matrix, see
          `compute_mcc`
        - ``confusion_matrix`` (``Tensor``): :math:`\left[n_{classes} +
          1, n_{classes} + 1\right]` counts, rows are targets, last row
          and column are background

    Formula:
        The metric matches the boxes of each image. With the IoU
        threshold :math:`t` from ``iou_threshold``, a target box and a
        prediction match when :math:`\text{IoU} > t`. The class of the
        prediction does not affect the match. Each target box takes the
        first prediction in row order that it matches, not the one with
        the highest IoU. Several target boxes can take the same
        prediction. Then:

        - A target box with a match adds ``1`` to its class row in the
          column of the class of its prediction.
        - A target box without a match adds ``1`` to its class row in
          the background column.
        - A prediction that no target box takes adds ``1`` to the
          background row in its class column.
        - An image without target boxes and without predictions adds
          ``1`` to the cell ``[n_classes, n_classes]``.

        **In an image without target boxes, without predictions, or
        without a match, each class counts at most once.** For example,
        three predictions of class ``0`` in an image without target
        boxes add ``1``, not ``3``, to the background row.

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        The metric ignores the confidence column, so each prediction
        of the node counts. `FomoConfusionMatrix` and
        `InstanceSegmentationConfusionMatrix` extend this class.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientBBoxHead
              inputs: [RepPANNeck]
              metrics:
                - name: DetectionConfusionMatrix

    Compatible with:
        - Nodes:

          - `EfficientBBoxHead`
          - `EfficientKeypointBBoxHead`
          - `PrecisionBBoxHead`
          - `PrecisionSegmentBBoxHead`

    """

    supported_tasks = [
        Tasks.BOUNDINGBOX,
        Tasks.INSTANCE_KEYPOINTS,
        Tasks.INSTANCE_SEGMENTATION,
    ]

    confusion_matrix: Tensor

    def __init__(self, iou_threshold: float = 0.45, **kwargs):
        """Initialize the metric and its ``confusion_matrix`` state.

        The state is a zero ``int64`` tensor of shape
        ``[n_classes + 1, n_classes + 1]``. A distributed run adds the
        states of all processes. The number of classes comes from the
        node, so a metric without a node raises ``RuntimeError``.

        Args:
            iou_threshold (float): The value that the IoU of a target
                box and a prediction must exceed for a match.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseMetric`, such as ``node``.

        """
        super().__init__(**kwargs)
        self.iou_threshold = iou_threshold

        self.add_state(
            "confusion_matrix",
            default=torch.zeros(
                self.n_classes + 1, self.n_classes + 1, dtype=torch.int64
            ),
            dist_reduce_fx="sum",
        )

    @override
    def update(
        self, boundingbox: list[Tensor], target_boundingbox: Tensor
    ) -> None:
        """Match the boxes of one batch and count the result.

        The method converts the target boxes to ``xyxy`` pixels with the
        height and width of `BaseAttachedModule.original_in_shape`. It
        writes the converted boxes into ``target_boundingbox``.
        `BaseMetric.run_update` passes a clone, so the labels of the
        batch do not change. The method then matches the boxes of each
        image, as the class docstring describes.

        Args:
            boundingbox (``list[Tensor]``): The predicted boxes of each
                image, of shape ``[M_i, 6]``, as
                ``[x1, y1, x2, y2, conf, class]`` in pixels. The length
                of the list is the batch size.
            target_boundingbox (``Tensor``): The ``boundingbox`` label of
                the batch, of shape ``[N, 6]``, as
                ``[batch_index, class, x, y, w, h]``. The values are
                normalized, and ``x`` and ``y`` are the top-left corner.

        """
        target_boundingbox[:, 2:] = box_convert(
            target_boundingbox[:, 2:], "xywh", "xyxy"
        )
        target_boundingbox[:, [2, 4]] *= self.original_in_shape[2]
        target_boundingbox[:, [3, 5]] *= self.original_in_shape[1]

        self._update(boundingbox, target_boundingbox)

    @override
    def compute(self) -> dict[str, Tensor]:
        """Return the MCC and the matrix since the last reset.

        Returns:
            ``dict[str, Tensor]``: The dictionary holds:

            - ``"mcc"``: the scalar MCC of the whole matrix, background
              included, see `compute_mcc`.
            - ``"confusion_matrix"``: the ``int64`` counts, of shape
              ``[n_classes + 1, n_classes + 1]``. Rows are target
              classes, columns are predicted classes, and index
              ``n_classes`` is the background.

        Example:
            The batch has one image with one target box of class ``0``.
            The first prediction covers it. The second prediction, of
            class ``1``, matches no target box. A ``SimpleNamespace``
            stands in for the node.

            >>> import torch
            >>> from types import SimpleNamespace
            >>> node = SimpleNamespace(
            ...     task=None,
            ...     n_classes=2,
            ...     original_in_shape=torch.Size([3, 10, 10]),
            ... )
            >>> metric = DetectionConfusionMatrix(node=node)
            >>> target = torch.tensor([[0, 0, 0.0, 0.0, 0.5, 0.5]])
            >>> boxes = [
            ...     torch.tensor([[0, 0, 5, 5, 0.9, 0], [6, 6, 9, 9, 0.8, 1]])
            ... ]
            >>> metric.update(boxes, target)
            >>> metric.compute()["confusion_matrix"].tolist()
            [[1, 0, 0], [0, 0, 0], [0, 1, 0]]

        """
        return {
            "mcc": compute_mcc(self.confusion_matrix.float()),
            "confusion_matrix": self.confusion_matrix,
        }

    def _update(self, predictions: list[Tensor], targets: Tensor) -> None:
        if self.confusion_matrix.is_inference():
            self.confusion_matrix = self.confusion_matrix.clone()

        for pred, target in zip(
            predictions,
            instances_from_batch(targets, batch_size=len(predictions)),
            strict=True,
        ):
            pred_classes = pred[:, 5].int()
            target_classes = target[:, 0].int()

            if target.numel() == pred.numel() == 0:
                self.confusion_matrix[self.n_classes, self.n_classes] += 1

            elif target.numel() == 0:
                # False positives -> GT is background
                self.confusion_matrix[self.n_classes, pred_classes] += 1

            elif pred.numel() == 0:
                # False negatives -> Pred is background
                self.confusion_matrix[target_classes, self.n_classes] += 1

            elif (
                iou := box_iou(target[:, 1:], pred[:, :4]) > self.iou_threshold
            ).any():
                iou_max, pred_max_idx = torch.max(iou, dim=1)
                iou_target_mask = iou_max > self.iou_threshold
                targets_kept = torch.arange(len(target), device=self.device)[
                    iou_target_mask
                ]
                predictions_kept = pred_max_idx[iou_target_mask]

                self.confusion_matrix.index_put_(
                    (
                        target_classes[targets_kept],
                        pred_classes[predictions_kept],
                    ),
                    torch.tensor(1),
                    accumulate=True,
                )

                for target_idx in self._get_unmatched(
                    targets_kept, len(target)
                ):
                    self.confusion_matrix[
                        target_classes[target_idx], self.n_classes
                    ] += 1

                for pred_idx in self._get_unmatched(
                    predictions_kept, len(pred)
                ):
                    self.confusion_matrix[
                        self.n_classes, pred_classes[pred_idx]
                    ] += 1
            else:
                self.confusion_matrix[target_classes, self.n_classes] += 1
                self.confusion_matrix[self.n_classes, pred_classes] += 1

    def _get_unmatched(self, index: Tensor, size: int) -> Tensor:
        return torch.arange(size, device=self.device)[
            torch.isin(
                torch.arange(size, device=self.device),
                index,
                invert=True,
            )
        ]
