"""The confusion matrix for instance segmentation, which reports one
matrix for the boxes and one for the masks.
"""

from torch import Tensor
from typing_extensions import override

from luxonis_train.tasks import Tasks

from .detection_confusion_matrix import DetectionConfusionMatrix
from .recognition_confusion_matrix import RecognitionConfusionMatrix
from .utils import preprocess_instance_masks


class InstanceSegmentationConfusionMatrix(
    DetectionConfusionMatrix, RecognitionConfusionMatrix
):
    r"""Confusion matrices for instance segmentation detection and masks.

    Inputs:
        - ``boundingbox`` (``list[Tensor]``): :math:`\left[M_i,
          6\right]` per image, ``[x1, y1, x2, y2, conf, class]``, pixels
        - ``instance_segmentation`` (``list[Tensor]``):
          :math:`\left[M_i, H, W\right]` per image, binary
        - ``target_boundingbox`` (``Tensor``): :math:`\left[N,
          6\right]`, ``[batch, class, x, y, w, h]``, ``xywh`` normalized
        - ``target_instance_segmentation`` (``Tensor``): :math:`\left[N,
          H, W\right]`, one per target box

    Outputs:
        - ``mcc``, ``confusion_matrix`` (``Tensor``): for the boxes
        - ``seg_mcc``, ``seg_confusion_matrix`` (``Tensor``): for the
          masks

    Formula:
        Updates the detection confusion matrix for boxes and the recognition
        confusion matrix for preprocessed instance masks.

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        Combines ``DetectionConfusionMatrix`` and
        ``RecognitionConfusionMatrix`` results with renamed output keys.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``PrecisionSegmentBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: PrecisionSegmentBBoxHead
              inputs: [RepPANNeck]
              metrics:
                - name: InstanceSegmentationConfusionMatrix

    Compatible with:
        - Nodes: ``PrecisionSegmentBBoxHead``

    """

    supported_tasks = [Tasks.INSTANCE_SEGMENTATION]

    @override
    def update(
        self,
        boundingbox: list[Tensor],
        instance_segmentation: list[Tensor],
        target_boundingbox: Tensor,
        target_instance_segmentation: Tensor,
    ) -> None:
        DetectionConfusionMatrix.update(self, boundingbox, target_boundingbox)
        RecognitionConfusionMatrix.update(
            self,
            *preprocess_instance_masks(
                boundingbox,
                instance_segmentation,
                target_boundingbox,
                target_instance_segmentation,
                self.n_classes,
                *self.original_in_shape[1:],
                device=self.device,
            ),
        )

    @override
    def compute(self) -> dict[str, Tensor]:
        det_result = DetectionConfusionMatrix.compute(self)
        rec_result = RecognitionConfusionMatrix.compute(self)
        det_renamed = {
            "detection_mcc": det_result["mcc"],
            "detection_confusion_matrix": det_result["confusion_matrix"],
        }
        rec_renamed = {
            "segmentation_mcc": rec_result["mcc"],
            "segmentation_confusion_matrix": rec_result["confusion_matrix"],
        }

        return det_renamed | rec_renamed
