"""The PPLCNetV3 backbone used by the OCR model."""

from typing import TypedDict

from torch import Tensor, nn
from typeguard import typechecked
from typing_extensions import override

from luxonis_train.nodes.base_node import BaseNode
from luxonis_train.nodes.blocks import ConvBlock

from .blocks import LCNetV3Layer, scale_up


class PPLCNetV3(BaseNode):
    r"""PPLCNetV3 backbone for text recognition.

    The backbone is a :math:`3 \times 3` convolution with a stride of
    ``2`` and a batch norm, followed by `LCNetV3Layer` layers. Each
    layer is a sequence of `LCNetV3Block` blocks. A block is a depthwise
    and a pointwise `GeneralReparameterizableBlock`, with learnable
    affine maps and ``Hardswish``. The node has two modes:

    - In *recognition* mode, `forward` also pools the output of layer
      ``4`` to a height of ``1`` and a width of ``max_text_len``.
    - In *detection* mode, a :math:`1 \times 1` convolution maps each of
      the four feature maps to a new number of channels.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, H, W\right]`

    Outputs:
        - ``features`` (``list[Tensor]``): the outputs of layers ``1``
          to ``4``, at strides 4, 4, 8, 8 for ``"rec-light"``
        - plus the pooled output of layer ``4``,
          :math:`\left[B, C_4, 1, L\right]` with :math:`L` equal to
          ``max_text_len``, in recognition mode

    References:
        - Source: Adapted from `PaddlePaddle/PaddleOCR
          <https://github.com/PaddlePaddle/PaddleOCR>`_ (Apache-2.0).
          Paper: `PP-LCNet: A Lightweight CPU Convolutional Neural
          Network <https://arxiv.org/abs/2109.15099>`_.
        - License: Apache-2.0

    Notes:
        Layer ``i`` is the layer of ``layer_params[i]``. ``layer_params``
        must hold at least five layers, and `forward` runs only the
        first five. The ``"rec-light"`` variant does not set
        ``max_text_len``, and the argument has no default. Thus a config
        must set it. `OCRRecognitionModel` sets it.

    Variants:
        - ``"rec-light"``:
            - Default: yes
            - Aliases: None
            - Parameters:
                - ``scale``: ``0.95``
                - ``n_branches``: ``4``
                - ``use_detection_backbone``: ``False``
            - Layers:
                - ``0``:
                    - ``kernel_sizes``: ``[3]``
                    - ``out_channels``: ``[32]``
                    - ``strides``: ``[1]``
                    - ``use_se``: ``[False]``
                - ``1``:
                    - ``kernel_sizes``: ``[3, 3]``
                    - ``out_channels``: ``[64, 64]``
                    - ``strides``: ``[2, 1]``
                    - ``use_se``: ``[False, False]``
                - ``2``:
                    - ``kernel_sizes``: ``[3, 3]``
                    - ``out_channels``: ``[128, 128]``
                    - ``strides``: ``[1, 1]``
                    - ``use_se``: ``[False, False]``
                - ``3``:
                    - ``kernel_sizes``: ``[3, 5, 5, 5, 5]``
                    - ``out_channels``: ``[256, 256, 256, 256, 256]``
                    - ``strides``: ``[2, 1, 1, 1, 1]``
                    - ``use_se``: ``[False, False, False, False, False]``
                - ``4``:
                    - ``kernel_sizes``: ``[5, 5, 5, 5]``
                    - ``out_channels``: ``[512, 512, 512, 512]``
                    - ``strides``: ``[1, 1, 1, 1]``
                    - ``use_se``: ``[True, True, False, False]``

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: PPLCNetV3
              variant: rec-light

    Compatible with:
        - Attach index: ``-1``, the last output of the input node
        - Used by: `OCRRecognitionModel`

    """

    in_channels: int

    @typechecked
    def __init__(
        self,
        scale: float,
        n_branches: int,
        use_detection_backbone: bool,
        max_text_len: int,
        layer_params: list["LayerParamsDict"] | None = None,
        **kwargs,
    ):
        r"""Initialize the stem, the layers, and the pooling.

        Args:
            scale (float): The width multiplier. `scale_up` applies it to
                the ``16`` output channels of the stem and to the
                ``out_channels`` of each layer.
            n_branches (int): The number of dense branches of each
                depthwise and pointwise convolution in the layers.
            use_detection_backbone (bool): ``True`` selects detection
                mode. Then :math:`1 \times 1` convolutions with a bias
                map the outputs of layers ``1`` to ``4`` to
                ``int(16 * scale)``, ``int(24 * scale)``,
                ``int(56 * scale)``, and ``int(480 * scale)`` channels.
                ``False`` selects recognition mode.
            max_text_len (int): The output width of the pooling in
                recognition mode. The constructor also builds the pooling
                in detection mode, but `forward` does not run it.
            layer_params (``list[LayerParamsDict] | None``): The
                parameters of the layers, one dictionary for each layer,
                in order. ``None`` or an empty list builds no layers.
                With fewer than five layers, detection mode raises
                ``IndexError`` in the constructor, and recognition mode
                raises ``IndexError`` in `forward`.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseNode`.

        """
        super().__init__(**kwargs)
        layer_params = layer_params or []

        self._scale = scale
        self._use_detection_backbone = use_detection_backbone
        self._n_branches = n_branches

        self.conv = ConvBlock(
            in_channels=self.in_channels,
            out_channels=scale_up(16, self._scale),
            kernel_size=3,
            stride=2,
            padding=1,
            bias=True,
            activation=False,
        )

        blocks: list[LCNetV3Layer] = []
        in_channels = scale_up(16, self._scale)
        for params in layer_params:
            blocks.append(
                LCNetV3Layer(
                    in_channels=in_channels,
                    n_branches=self._n_branches,
                    scale=self._scale,
                    **params,
                )
            )
            in_channels = blocks[-1].out_channels
        self.blocks = nn.ModuleList(blocks)

        if self._use_detection_backbone:
            blocks_out_channels = [blocks[i].out_channels for i in range(1, 5)]

            detection_out_channels = [
                int(c * self._scale) for c in [16, 24, 56, 480]
            ]

            self.detection_blocks = nn.ModuleList(
                [
                    nn.Conv2d(
                        in_channels=in_channels,
                        out_channels=out_channels,
                        kernel_size=1,
                        stride=1,
                        padding=0,
                        bias=True,
                    )
                    for in_channels, out_channels in zip(
                        blocks_out_channels,
                        detection_out_channels,
                        strict=True,
                    )
                ]
            )
        self.avg_pool = nn.AdaptiveAvgPool2d((1, max_text_len))

    def forward(self, x: Tensor) -> list[Tensor]:
        r"""Run the stem and the first five layers on a batch of images.

        Args:
            x (``Tensor``): The input images, of shape ``[B, C, H, W]``.

        Returns:
            ``list[Tensor]``: In recognition mode, five tensors: the
            outputs of layers ``1`` to ``4``, then the output of layer
            ``4`` pooled to ``[B, C_4, 1, max_text_len]``. In detection
            mode, four tensors: the outputs of layers ``1`` to ``4``
            after their :math:`1 \times 1` convolutions.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes.backbones import PPLCNetV3
            >>> shapes = [{"features": [Size([2, 3, 48, 320])]}]
            >>> node = PPLCNetV3(
            ...     input_shapes=shapes, variant="rec-light", max_text_len=40
            ... )
            >>> features = node(torch.zeros(2, 3, 48, 320))
            >>> [tuple(feature.shape) for feature in features]
            [(2, 64, 12, 80), (2, 128, 12, 80), (2, 240, 6, 40),
             (2, 480, 6, 40), (2, 480, 1, 40)]

        """
        out = []
        x = self.conv(x)
        x = self.blocks[0](x)
        x = self.blocks[1](x)

        out.append(x)
        x = self.blocks[2](x)
        out.append(x)
        x = self.blocks[3](x)
        out.append(x)
        x = self.blocks[4](x)
        out.append(x)

        if self._use_detection_backbone:
            for i in range(4):
                out[i] = self.detection_blocks[i](out[i])
            return out

        out.append(self.avg_pool(x))

        return out

    @override
    @staticmethod
    def get_variants() -> tuple[str, dict[str, "PPLCNetVariantDict"]]:
        """Return the default variant name and the only PPLCNetV3 variant.

        ``"rec-light"`` sets ``scale``, ``n_branches``,
        ``use_detection_backbone``, and five layers in ``layer_params``.
        It does not set ``max_text_len``. The ``Variants`` section of
        `PPLCNetV3` lists all values. Each call builds new dictionaries.

        Returns:
            tuple[str, dict[str, PPLCNetVariantDict]]: The name of the
            default variant, ``"rec-light"``, and a dictionary that maps
            it to its constructor arguments.

        Example:
            >>> from luxonis_train.nodes.backbones import PPLCNetV3
            >>> default, variants = PPLCNetV3.get_variants()
            >>> default, len(variants[default]["layer_params"])
            ('rec-light', 5)

        """
        return "rec-light", {
            "rec-light": {
                "scale": 0.95,
                "n_branches": 4,
                "use_detection_backbone": False,
                "layer_params": [
                    {
                        "kernel_sizes": [3],
                        "out_channels": [32],
                        "strides": [1],
                        "use_se": [False],
                    },
                    {
                        "kernel_sizes": [3, 3],
                        "out_channels": [64, 64],
                        "strides": [2, 1],
                        "use_se": [False, False],
                    },
                    {
                        "kernel_sizes": [3, 3],
                        "out_channels": [128, 128],
                        "strides": [1, 1],
                        "use_se": [False, False],
                    },
                    {
                        "kernel_sizes": [3, 5, 5, 5, 5],
                        "out_channels": [256, 256, 256, 256, 256],
                        "strides": [2, 1, 1, 1, 1],
                        "use_se": [False, False, False, False, False],
                    },
                    {
                        "kernel_sizes": [5, 5, 5, 5],
                        "out_channels": [512, 512, 512, 512],
                        "strides": [1, 1, 1, 1],
                        "use_se": [True, True, False, False],
                    },
                ],
            }
        }


class LayerParamsDict(TypedDict):
    """The parameters of one PPLCNetV3 layer in ``layer_params``.

    `PPLCNetV3` passes the keys to `LCNetV3Layer` as keyword arguments,
    together with the input channels, ``n_branches``, and ``scale``. The
    four lists must have the same length. The layer builds one
    `LCNetV3Block` for each position.

    Attributes:
        kernel_sizes (list[int]): The kernel size of the depthwise
            convolution of each block.
        out_channels (list[int]): The output channels of each block,
            before `scale_up` scales them. The last value sets the output
            channels of the layer.
        strides (list[int]): The stride of the depthwise convolution of
            each block.
        use_se (list[bool]): Whether each block has a
            `SqueezeExciteBlock` between its two convolutions.

    """

    kernel_sizes: list[int]
    out_channels: list[int]
    strides: list[int]
    use_se: list[bool]


class PPLCNetVariantDict(TypedDict):
    """The constructor arguments of one PPLCNetV3 variant.

    `PPLCNetV3.get_variants` maps each variant name to one of these
    dictionaries. The ``__init__`` docstring of `PPLCNetV3` describes
    the keys in full. A variant does not set ``max_text_len``.

    Attributes:
        scale (float): The width multiplier of the stem and the layers.
        n_branches (int): The number of dense branches of each
            convolution in the layers.
        use_detection_backbone (bool): Whether the node runs in
            detection mode.
        layer_params (``list[LayerParamsDict]``): The parameters of the
            layers, in order.

    """

    scale: float
    n_branches: int
    use_detection_backbone: bool
    layer_params: list[LayerParamsDict]
