"""The ReXNet-lite backbone and the linear bottleneck it repeats."""

import torch
from torch import Tensor, nn

from luxonis_train.nodes.base_node import BaseNode
from luxonis_train.nodes.blocks import ConvBlock
from luxonis_train.utils import make_divisible


class ReXNetV1_lite(BaseNode):
    r"""Lite ReXNetV1 backbone for lightweight convolutional features.

    ReXNet (Rank Expansion Networks) makes the channel counts of its
    blocks grow linearly with the depth. The lite version has no
    squeeze-and-excitation blocks, and ``ReLU6`` is its only activation.
    The node is a stack of 18 modules: a ``3x3`` stem with stride 2, 16
    `LinearBottleneck` blocks in six stages, and a ``1x1`` convolution.
    With the default parameters, this convolution has 1280 channels.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, H, W\right]`

    Outputs:
        - ``features`` (``list[Tensor]``): one per ``out_indices``; by
          default strides 2, 8, 16, 32 with 16, 56, 120, 1280 channels

    References:
        - Source: Adapted from `clovaai/rexnet
          <https://github.com/clovaai/rexnet>`_ (MIT). Paper:
          `Rethinking Channel Dimensions for Efficient Model Design
          <https://arxiv.org/abs/2007.00992>`_.
        - License: `MIT
          <https://github.com/clovaai/rexnet/blob/master/LICENSE>`_.
          Copyright 2021-present NAVER Corp.

    Notes:
        The stem always expects 3 input channels. It does not read
        ``in_channels``. ``out_indices`` selects outputs by module
        index: ``0`` is the stem, ``1`` to ``16`` are the bottlenecks,
        and ``17`` is the final ``1x1`` convolution.

    Variants:
        None. Configure the node through ``params``.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: ReXNetV1_lite

    Compatible with:
        - Attach index: ``-1``, the last output of the input node

    """

    def __init__(
        self,
        fix_head_stem: bool = False,
        divisible_value: int = 8,
        input_ch: int = 16,
        final_ch: int = 164,
        multiplier: float = 1.0,
        kernel_sizes: int | list[int] = 3,
        out_indices: list[int] | None = None,
        **kwargs,
    ):
        """Build the stem, the 16 bottlenecks, and the final
        convolution.

        The six stages have 1, 2, 2, 3, 3, and 5 bottlenecks. Their first
        bottlenecks have the strides 1, 2, 2, 2, 1, and 2 in stage order.
        The other bottlenecks have the stride 1. The bottlenecks of the
        first stage have no expansion. The other bottlenecks expand the
        channels by a factor of 6.

        The output channels of the bottlenecks grow in 15 equal steps
        from ``input_ch`` to ``input_ch + final_ch``. ``multiplier``
        scales these counts. A ``multiplier`` below ``1`` scales only the
        growth, not ``input_ch``. The stem has 32 channels. A
        ``multiplier`` above ``1`` gives the stem ``32 * multiplier``
        channels and the final convolution ``int(1280 * multiplier)``
        channels, unless ``fix_head_stem`` is ``True``. The constructor
        rounds the channel counts of the stem and the bottlenecks up to a
        multiple of ``divisible_value``.

        Args:
            fix_head_stem (bool): Whether to keep the stem at 32 channels
                and the final convolution at 1280 channels. It changes
                the network only for a ``multiplier`` above ``1``.
            divisible_value (int): The number that the channel counts of
                the stem and the bottlenecks are multiples of.
            input_ch (int): The output channels of the first bottleneck,
                before ``multiplier``.
            final_ch (int): The channel growth from the first to the last
                bottleneck, before ``multiplier``. It is not the channel
                count of the last bottleneck.
            multiplier (float): The scale of the channel counts.
            kernel_sizes (int | list[int]): The size of the depthwise
                kernels. A list gives one size for each of the six
                stages.
            out_indices (list[int] | None): The indices of the modules
                whose outputs `forward` returns. ``0`` is the stem, ``1``
                to ``16`` are the bottlenecks, and ``17`` is the final
                convolution. ``None`` or an empty list selects
                ``[1, 4, 10, 17]``.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseNode`.

        Raises:
            ValueError: When ``kernel_sizes`` is a list that does not
                have exactly six values.

        """
        super().__init__(**kwargs)

        layers = [1, 2, 2, 3, 3, 5]
        strides = [1, 2, 2, 2, 1, 2]

        self._n_convblocks = sum(layers)
        self._out_indices = out_indices or [1, 4, 10, 17]

        strides, ts, kernel_sizes = self._expand_layer_configs(
            layers, strides, kernel_sizes
        )

        inplanes, first_channel = self._compute_stem_channels(
            input_ch, multiplier, fix_head_stem, divisible_value
        )
        in_channels_group, channels_group = self._compute_channel_groups(
            self._n_convblocks,
            first_channel,
            inplanes,
            multiplier,
            final_ch,
            divisible_value,
        )

        pen_channels = (
            int(1280 * multiplier)
            if multiplier > 1 and not fix_head_stem
            else 1280
        )

        features: list[nn.Module] = [
            ConvBlock(
                3,
                first_channel,
                kernel_size=3,
                stride=2,
                padding=1,
                activation=nn.ReLU6(inplace=True),
            )
        ]
        for in_c, c, t, k, s in zip(
            in_channels_group,
            channels_group,
            ts,
            kernel_sizes,
            strides,
            strict=True,
        ):
            features.append(
                LinearBottleneck(
                    in_channels=in_c, channels=c, t=t, kernel_size=k, stride=s
                )
            )
        features.append(
            ConvBlock(
                in_channels=channels_group[-1],
                out_channels=pen_channels,
                kernel_size=1,
                activation=nn.ReLU6(inplace=True),
            )
        )
        self.features = nn.Sequential(*features)

    @staticmethod
    def _expand_layer_configs(
        layers: list[int],
        strides: list[int],
        kernel_sizes: int | list[int],
    ) -> tuple[list[int], list[int], list[int]]:
        if isinstance(kernel_sizes, int):
            kernel_sizes = [kernel_sizes] * 6

        expanded_strides = [
            s if i == 0 else 1
            for layer, s in zip(layers, strides, strict=True)
            for i in range(layer)
        ]
        ts = [1] * layers[0] + [6] * sum(layers[1:])
        expanded_kernel_sizes = [
            ks
            for ks, layer in zip(kernel_sizes, layers, strict=True)
            for _ in range(layer)
        ]
        return expanded_strides, ts, expanded_kernel_sizes

    @staticmethod
    def _compute_stem_channels(
        input_ch: int,
        multiplier: float,
        fix_head_stem: bool,
        divisible_value: int,
    ) -> tuple[float, int]:
        inplanes = input_ch / multiplier if multiplier < 1.0 else input_ch
        first_channel = (
            32 / multiplier if multiplier < 1.0 or fix_head_stem else 32
        )
        first_channel = make_divisible(
            round(first_channel * multiplier), divisible_value
        )
        return inplanes, first_channel

    @staticmethod
    def _compute_channel_groups(
        n_convblocks: int,
        first_channel: int,
        inplanes: float,
        multiplier: float,
        final_ch: int,
        divisible_value: int,
    ) -> tuple[list[int], list[int]]:
        in_channels_group: list[int] = []
        channels_group: list[int] = []
        for i in range(n_convblocks):
            inplanes_divisible = make_divisible(
                round(inplanes * multiplier), divisible_value
            )
            if i == 0:
                in_channels_group.append(first_channel)
                channels_group.append(inplanes_divisible)
            else:
                in_channels_group.append(inplanes_divisible)
                inplanes += final_ch / (n_convblocks - 1 * 1.0)
                inplanes_divisible = make_divisible(
                    round(inplanes * multiplier), divisible_value
                )
                channels_group.append(inplanes_divisible)
        return in_channels_group, channels_group

    def forward(self, inputs: Tensor) -> list[Tensor]:
        """Run all 18 modules and collect the selected outputs.

        Args:
            inputs (``Tensor``): Image batch of shape ``[B, 3, H, W]``.

        Returns:
            ``list[Tensor]``: The outputs of the modules whose index is in
            ``out_indices``, in module order. An index outside ``0`` to
            ``17`` selects nothing. The default indices give the strides
            2, 8, 16, and 32, with 16, 56, 120, and 1280 channels.

        Example:
            >>> import torch
            >>> from luxonis_train.nodes import ReXNetV1_lite
            >>> node = ReXNetV1_lite()
            >>> [tuple(t.shape) for t in node(torch.zeros(1, 3, 64, 64))]
            [(1, 16, 32, 32), (1, 56, 8, 8), (1, 120, 4, 4), (1, 1280, 2, 2)]

        """
        outs: list[Tensor] = []
        for i, module in enumerate(self.features):
            inputs = module(inputs)
            if i in self._out_indices:
                outs.append(inputs)
        return outs


class LinearBottleneck(nn.Module):
    """Inverted residual block of ReXNet with a linear projection.

    When ``t`` is not ``1``, the block first expands the channels with a
    ``1x1`` convolution. It then applies a depthwise convolution and
    projects to ``channels`` with a ``1x1`` convolution. The expansion
    and the depthwise convolution end with ``ReLU6``. The projection has
    no activation. Each convolution has a batch norm.

    When ``stride`` is ``1`` and ``in_channels <= channels``, the block
    adds its input to the first ``in_channels`` output channels. The
    other output channels get no shortcut.

    Attributes:
        use_shortcut (bool): Whether the block adds the shortcut.
        in_channels (int): Number of input channels.
        out_channels (int): Number of output channels.
        out (``nn.Sequential``): The expansion, depthwise, and
            projection layers.

    Example:
        >>> import torch
        >>> block = LinearBottleneck(8, 12, t=6)
        >>> block.use_shortcut
        True
        >>> block(torch.zeros(1, 8, 4, 4)).shape
        torch.Size([1, 12, 4, 4])
        >>> LinearBottleneck(8, 12, t=6, stride=2).use_shortcut
        False

    """

    def __init__(
        self,
        in_channels: int,
        channels: int,
        t: int,
        kernel_size: int = 3,
        stride: int = 1,
    ):
        """Build the expansion, the depthwise, and the projection
        layers.

        Args:
            in_channels (int): Number of input channels.
            channels (int): Number of output channels.
            t (int): Expansion factor. The depthwise convolution has
                ``in_channels * t`` channels. For ``1``, the block has no
                expansion convolution.
            kernel_size (int): Size of the depthwise kernel. The padding
                is ``kernel_size // 2``.
            stride (int): Stride of the depthwise convolution.

        """
        super().__init__()
        self._use_shortcut = stride == 1 and in_channels <= channels
        self._in_channels = in_channels
        self._out_channels = channels
        out: list[nn.Module] = []
        if t != 1:
            dw_channels = in_channels * t
            out.append(
                ConvBlock(
                    in_channels=in_channels,
                    out_channels=dw_channels,
                    kernel_size=1,
                    activation=nn.ReLU6(inplace=True),
                )
            )
        else:
            dw_channels = in_channels
        out.append(
            ConvBlock(
                in_channels=dw_channels,
                out_channels=dw_channels * 1,
                kernel_size=kernel_size,
                stride=stride,
                padding=(kernel_size // 2),
                groups=dw_channels,
                activation=nn.ReLU6(inplace=True),
            )
        )
        out.append(
            ConvBlock(
                in_channels=dw_channels,
                out_channels=channels,
                kernel_size=1,
                activation=None,
            )
        )

        self.out = nn.Sequential(*out)

    def forward(self, x: Tensor) -> Tensor:
        """Apply the layers and add the partial shortcut.

        Args:
            x (``Tensor``): Input of shape ``[B, in_channels, H, W]``.

        Returns:
            ``Tensor``: Output of shape ``[B, channels, H', W']``. The
            stride of the depthwise convolution sets ``H'`` and ``W'``.
            With the shortcut, the first ``in_channels`` channels hold
            the sum of the input and the projection.

        """
        out = self.out(x)

        if self._use_shortcut:
            # NOTE: this results in a ScatterND node which isn't supported yet in myriad
            a = out[:, : self._in_channels]
            b = x
            a = a + b
            c = out[:, self._in_channels :]
            return torch.concat([a, c], dim=1)

        return out
