"""Metrics that check the embedding space of `GhostFaceNetHead`.

`ClosestIsPositiveAccuracy` checks whether the nearest other embedding
has the same identity label. `MedianDistances` reports the median
Euclidean distances between the embeddings. When the head sets
``cross_batch_memory_size``, both metrics also score the embeddings of
earlier batches.

"""

import math
from typing import Annotated

import torch
from torch import Tensor
from typing_extensions import override

from luxonis_train.nodes.heads.ghostfacenet_head import GhostFaceNetHead
from luxonis_train.tasks import Tasks

from .base_metric import BaseMetric, MetricState

# Converted from https://omoindrot.github.io/triplet-loss#offline-and-online-triplet-mining
# to PyTorch from TensorFlow


class ClosestIsPositiveAccuracy(BaseMetric):
    r"""Accuracy of nearest-neighbor identity matches for embeddings.

    Inputs:
        - ``predictions`` (``Tensor``): :math:`\left[B, D\right]`
          embeddings
        - ``target`` (``Tensor``): :math:`\left[B\right]` identity
          labels

    Outputs:
        - ``Tensor``: scalar accuracy in :math:`\left[0, 1\right]`

    Formula:
        The metric computes the Euclidean distance between each pair of
        embeddings. An embedding counts only when at least one other
        embedding has the same label. The accuracy is the number of
        counted embeddings whose nearest other embedding has the same
        label, divided by the number of counted embeddings.

    References:
        - Source: Converted to PyTorch from the TensorFlow code at
          `omoindrot.github.io/triplet-loss
          <https://omoindrot.github.io/triplet-loss>`_.
        - License: Apache-2.0 (this project)

    Notes:
        When the head sets ``cross_batch_memory_size``, the metric keeps
        the newest embeddings of all batches, up to that number. It
        scores nothing until the memory is full. After that, it scores
        all embeddings in the memory again on each batch. The memory
        empties when the metric resets.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``GhostFaceNetHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: GhostFaceNetHead
              inputs: [GhostFaceNet]
              metrics:
                - name: ClosestIsPositiveAccuracy

    Compatible with:
        - Used by: `EmbeddingsModel`
        - Nodes: `GhostFaceNetHead`

    """

    supported_tasks = [Tasks.EMBEDDINGS]
    node: GhostFaceNetHead

    cross_batch_memory: Annotated[list[tuple[Tensor, Tensor]], MetricState()]
    correct: Annotated[Tensor, MetricState()]
    total: Annotated[Tensor, MetricState()]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._cross_batch_memory_size = self.node.cross_batch_memory_size

    @override
    def update(self, predictions: Tensor, target: Tensor) -> None:
        """Add the nearest-neighbor matches of one batch to the counts.

        Without cross-batch memory, the method scores the batch alone.
        With it, the method appends each embedding and its label to the
        memory. It then drops the oldest entries above the memory size.
        While the memory holds fewer entries than the size, the method
        returns and scores nothing. Otherwise it scores all embeddings in
        the memory.

        An embedding counts only when another embedding has the same
        label. ``correct`` grows by the counted embeddings whose nearest
        other embedding has the same label. ``total`` grows by the
        number of counted embeddings.

        Args:
            predictions (``Tensor``): Embeddings of shape ``[B, D]``, the
                main output of the node.
            target (``Tensor``): The ``metadata/id`` label of each
                embedding, of shape ``[B]``.

        """
        embeddings, labels = predictions, target

        if self._cross_batch_memory_size is not None:
            self.cross_batch_memory.extend(
                list(zip(embeddings, labels, strict=True))
            )

            if len(self.cross_batch_memory) > self._cross_batch_memory_size:
                self.cross_batch_memory = self.cross_batch_memory[
                    -self._cross_batch_memory_size :
                ]

            if len(self.cross_batch_memory) < self._cross_batch_memory_size:
                return

            embeddings, labels = zip(*self.cross_batch_memory, strict=True)
            embeddings = torch.stack(embeddings)
            labels = torch.stack(labels)

        pairwise_distances = _get_pairwise_distances(embeddings)
        pairwise_distances.fill_diagonal_(math.inf)

        closest_indices = torch.argmin(pairwise_distances, dim=1)
        closest_labels = labels[closest_indices]

        positive_mask = _get_anchor_positive_triplet_mask(labels)
        n_positives = positive_mask.sum(dim=1)
        has_at_least_one_positive_and_negative = (n_positives > 0) & (
            n_positives < len(labels)
        )

        filtered_labels = labels[has_at_least_one_positive_and_negative]
        filtered_closest_labels = closest_labels[
            has_at_least_one_positive_and_negative
        ]

        correct_predictions = (
            filtered_labels == filtered_closest_labels
        ).sum()

        self.correct += correct_predictions
        self.total += len(filtered_labels)

    @override
    def compute(self) -> Tensor:
        """Return the share of counted embeddings with a correct match.

        Returns:
            ``Tensor``: ``correct / total``, a scalar from ``0`` to ``1``.
            It is ``NaN`` when no embedding counted since the last reset.

        """
        return self.correct / self.total


class MedianDistances(BaseMetric):
    r"""Median distances between embeddings, for diagnostics.

    Inputs:
        - ``embeddings`` (``Tensor``): :math:`\left[B, D\right]`
        - ``target`` (``Tensor``): :math:`\left[B\right]` identity
          labels

    Outputs:
        - ``MedianDistance``, ``MedianClosestDistance``,
          ``MedianClosestPositiveDistance``,
          ``MedianClosestVsClosestPositiveDistance`` (``Tensor``):
          scalar medians

    Formula:
        The metric computes the Euclidean distance between each pair of
        embeddings. It collects four sets of distances over all batches
        and reports the median of each:

        - ``MedianDistance``: each unordered pair of embeddings.
        - ``MedianClosestDistance``: each embedding and its nearest
          other embedding.
        - ``MedianClosestPositiveDistance``: each embedding and its
          nearest other embedding with the same label.
        - ``MedianClosestVsClosestPositiveDistance``: the nearest
          same-label distance minus the nearest distance, for each
          embedding.

        The last two sets skip an embedding when no other embedding has
        its label. For an even number of values, ``torch.median``
        returns the lower of the two middle values.

    References:
        - Source: Converted to PyTorch from the TensorFlow code at
          `omoindrot.github.io/triplet-loss
          <https://omoindrot.github.io/triplet-loss>`_.
        - License: Apache-2.0 (this project)

    Notes:
        The cross-batch memory of the head works as in
        `ClosestIsPositiveAccuracy`. All four values are ``NaN`` when
        the metric scored no batch. The result holds only sub-metrics,
        so this metric cannot be the main metric.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``GhostFaceNetHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: GhostFaceNetHead
              inputs: [GhostFaceNet]
              metrics:
                - name: MedianDistances

    Compatible with:
        - Used by: `EmbeddingsModel`
        - Nodes: `GhostFaceNetHead`

    """

    supported_tasks = [Tasks.EMBEDDINGS]
    node: GhostFaceNetHead

    cross_batch_memory: Annotated[list[tuple[Tensor, Tensor]], MetricState()]
    all_distances: Annotated[list[Tensor], MetricState()]
    closest_distances: Annotated[list[Tensor], MetricState()]
    positive_distances: Annotated[list[Tensor], MetricState()]
    closest_vs_positive_distances: Annotated[list[Tensor], MetricState()]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._cross_batch_memory_size = self.node.cross_batch_memory_size

    @override
    def update(self, embeddings: Tensor, target: Tensor) -> None:
        """Add the distances of one batch to the four distance lists.

        The cross-batch memory works as in
        `ClosestIsPositiveAccuracy.update`. While the memory is not
        full, the method stores the batch and adds nothing to the lists.

        The method appends one tensor to each list:

        - ``all_distances``: the distance of each unordered pair.
        - ``closest_distances``: the nearest distance of each embedding.
        - ``positive_distances``: the nearest same-label distance of
          each embedding that has another embedding with its label.
        - ``closest_vs_positive_distances``: the nearest same-label
          distance minus the nearest distance, for the same embeddings.

        Args:
            embeddings (``Tensor``): Embeddings of shape ``[B, D]``, the
                ``embeddings`` output of the node.
            target (``Tensor``): The ``metadata/id`` label of each
                embedding, of shape ``[B]``.

        """
        if self._cross_batch_memory_size is not None:
            self.cross_batch_memory.extend(
                list(zip(embeddings, target, strict=True))
            )

            if len(self.cross_batch_memory) > self._cross_batch_memory_size:
                self.cross_batch_memory = self.cross_batch_memory[
                    -self._cross_batch_memory_size :
                ]

            if len(self.cross_batch_memory) < self._cross_batch_memory_size:
                return

            embeddings_list, target_list = zip(
                *self.cross_batch_memory, strict=True
            )
            embeddings = torch.stack(embeddings_list)
            target = torch.stack(target_list)

        pairwise_distances = _get_pairwise_distances(embeddings)
        self.all_distances.append(
            pairwise_distances[
                torch.triu(torch.ones_like(pairwise_distances), diagonal=1)
                == 1
            ].flatten()
        )

        pairwise_distances.fill_diagonal_(math.inf)

        closest_distances, _ = torch.min(pairwise_distances, dim=1)
        self.closest_distances.append(closest_distances)

        positive_mask = _get_anchor_positive_triplet_mask(target).bool()

        only_positive_distances = pairwise_distances.clone()
        only_positive_distances[~positive_mask] = math.inf

        closest_positive_distances, _ = torch.min(
            only_positive_distances, dim=1
        )

        non_inf_mask = closest_positive_distances != math.inf
        difference = closest_positive_distances - closest_distances

        self.closest_vs_positive_distances.append(difference[non_inf_mask])
        self.positive_distances.append(
            closest_positive_distances[non_inf_mask]
        )

    @override
    def compute(self) -> dict[str, Tensor]:
        """Return the median of each distance list.

        Returns:
            ``dict[str, Tensor]``: Scalar medians under the keys
            ``"MedianDistance"``, ``"MedianClosestDistance"``,
            ``"MedianClosestPositiveDistance"``, and
            ``"MedianClosestVsClosestPositiveDistance"``. All four are
            ``NaN`` when `update` added nothing since the last reset. A
            list that holds only empty tensors also gives ``NaN``.

        """
        if len(self.all_distances) == 0:
            return {
                "MedianDistance": torch.tensor(math.nan),
                "MedianClosestDistance": torch.tensor(math.nan),
                "MedianClosestPositiveDistance": torch.tensor(math.nan),
                "MedianClosestVsClosestPositiveDistance": torch.tensor(
                    math.nan
                ),
            }

        all_distances = torch.cat(self.all_distances)
        closest_distances = torch.cat(self.closest_distances)
        positive_distances = torch.cat(self.positive_distances)
        closest_vs_positive_distances = torch.cat(
            self.closest_vs_positive_distances
        )

        return {
            "MedianDistance": torch.median(all_distances),
            "MedianClosestDistance": torch.median(closest_distances),
            "MedianClosestPositiveDistance": torch.median(positive_distances),
            "MedianClosestVsClosestPositiveDistance": torch.median(
                closest_vs_positive_distances
            ),
        }


def _get_pairwise_distances(embeddings: Tensor) -> Tensor:
    """Compute the Euclidean distance between each pair of embeddings.

    The function derives the squared distances from the dot products and
    clamps negative rounding errors to ``0``. Before the square root, it
    adds ``1e-16`` to each zero entry, and after it, it sets these
    entries back to ``0``. This keeps the gradient of the square root
    finite.

    Args:
        embeddings (``Tensor``): Embeddings of shape ``[N, D]``.

    Returns:
        ``Tensor``: The distances, of shape ``[N, N]``.

    Example:
        >>> import torch
        >>> points = torch.tensor([[0.0, 0.0], [3.0, 4.0], [6.0, 8.0]])
        >>> _get_pairwise_distances(points).tolist()
        [[0.0, 5.0, 10.0], [5.0, 0.0, 5.0], [10.0, 5.0, 0.0]]

    """
    dot_product = embeddings @ embeddings.T

    square_norm = torch.diag(dot_product)

    distances = (
        square_norm.unsqueeze(0) - 2.0 * dot_product + square_norm.unsqueeze(1)
    )
    distances = torch.max(distances, torch.tensor(0.0))

    mask = (distances == 0.0).float()
    distances = distances + mask * 1e-16

    return distances.sqrt_() * (1.0 - mask)


def _get_anchor_positive_triplet_mask(labels: Tensor) -> Tensor:
    """Mark the pairs of two different samples with the same label.

    Args:
        labels (``Tensor``): Labels of shape ``[N]``.

    Returns:
        ``Tensor``: A ``uint8`` mask of shape ``[N, N]``. An entry is
        ``1`` when ``i != j`` and ``labels[i] == labels[j]``, else ``0``.

    Example:
        >>> import torch
        >>> _get_anchor_positive_triplet_mask(torch.tensor([7, 7, 3])).tolist()
        [[0, 1, 0], [1, 0, 0], [0, 0, 0]]

    """
    indices_equal = torch.eye(
        labels.shape[0], dtype=torch.uint8, device=labels.device
    )
    indices_not_equal = ~indices_equal
    labels_equal = labels.unsqueeze(0) == labels.unsqueeze(1)
    return indices_not_equal & labels_equal
