"""Exact-match accuracy of OCR predictions.

The metric also gives the share of the texts with exactly one and with
exactly two wrong characters.

"""

from typing import Annotated

import torch
import torch.nn.functional as F
from torch import Tensor
from typing_extensions import override

from luxonis_train.nodes import OCRCTCHead
from luxonis_train.tasks import Tasks

from .base_metric import BaseMetric, MetricState


class OCRAccuracy(BaseMetric):
    r"""Share of OCR texts with zero, one, or two wrong characters.

    Inputs:
        - ``predictions`` (``Tensor``): :math:`\left[B, T, C\right]`
          logits
        - ``target`` (``Tensor``): :math:`\left[B, S\right]` character
          codes, ``0``-padded

    Outputs:
        - ``Tensor``: scalar, the share of exact matches
        - ``rank_0``, ``rank_1``, ``rank_2`` (``Tensor``): scalar, the
          share of texts with exactly ``0``, ``1``, or ``2`` wrong
          characters

    Formula:
        The metric decodes each prediction greedily. It takes the class
        with the highest logit at each step and merges each run of
        equal classes into one class. It then removes ``blank_class``
        and pads the result with ``0`` to :math:`T` positions. The
        ``encoder`` of the node converts the target characters to class
        indices. The metric pads a shorter target with ``blank_class``
        and crops a longer target to :math:`T` positions. It compares
        the two sequences position by position. A text with
        :math:`e \leq 2` different positions counts for ``rank_e``. A
        text with more counts for no rank.

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        - The comparison is not an edit distance. A missing character
          shifts the characters after it, and each shifted position
          counts as wrong.
        - The characters of a target after position :math:`T` do not
          count.
        - The encoder of `OCRCTCHead` uses the class ``0`` for the blank
          and for the padding. With another ``blank_class``, the
          decoding keeps the blanks of the head. Each position that the
          metric adds to a target also counts as wrong.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``OCRCTCHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: OCRCTCHead
              inputs: [SVTRNeck]
              metrics:
                - name: OCRAccuracy

    Compatible with:
        - Used by: `OCRRecognitionModel`
        - Nodes: `OCRCTCHead`

    """

    supported_tasks = [Tasks.OCR]

    node: OCRCTCHead

    rank_0: Annotated[Tensor, MetricState()]
    rank_1: Annotated[Tensor, MetricState()]
    rank_2: Annotated[Tensor, MetricState()]
    total: Annotated[Tensor, MetricState()]

    def __init__(self, blank_class: int = 0, **kwargs):
        """Initialize the metric.

        The node must be an `OCRCTCHead`. Otherwise `BaseAttachedModule`
        raises `IncompatibleError`.

        Args:
            blank_class (int): The class index of the CTC blank. The
                decoding removes it from the predictions, and the metric
                pads the targets with it. Keep ``0``, the blank of the
                encoder of `OCRCTCHead`.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseMetric`, such as ``node``.

        """
        super().__init__(**kwargs)
        self._blank_class = blank_class

    @override
    def update(self, predictions: Tensor, target: Tensor) -> None:
        """Decode one batch and add its counts to the states.

        The method adds the number of texts with exactly ``0``, ``1``,
        and ``2`` wrong characters to ``rank_0``, ``rank_1``, and
        ``rank_2``. It adds the batch size to ``total``. The class
        docstring describes the decoding and the comparison.

        Args:
            predictions (``Tensor``): The logits of shape ``[B, T, C]``,
                the main output of the node.
            target (``Tensor``): The character codes of the texts, of
                shape ``[B, S]``, padded with ``0``. It is the
                ``metadata/text`` label of the task.

        """
        target = self.node.encoder(target).to(self.device)

        batch_size, text_length, _ = predictions.shape

        pred_classes = predictions.argmax(dim=-1)

        predictions = torch.zeros(
            (batch_size, text_length), dtype=torch.int64, device=self.device
        )
        for i in range(batch_size):
            unique_cons_classes = torch.unique_consecutive(pred_classes[i])
            unique_cons_classes = unique_cons_classes[
                unique_cons_classes != self._blank_class
            ]
            if len(unique_cons_classes) != 0:
                predictions[i, : unique_cons_classes.shape[0]] = (
                    unique_cons_classes
                )

        target = F.pad(
            target, (0, text_length - target.shape[1]), value=self._blank_class
        )
        errors = (predictions != target).sum(dim=1)

        for rank in range(3):
            matching = (errors == rank) * 1.0
            [self.rank_0, self.rank_1, self.rank_2][rank] += matching.sum()
        self.total += batch_size

    @override
    def compute(self) -> tuple[Tensor, dict[str, Tensor]]:
        """Divide the counts by the number of texts.

        Returns:
            ``tuple[Tensor, dict[str, Tensor]]``: The share of exact
            matches, and a dictionary with the keys ``"rank_0"``,
            ``"rank_1"``, and ``"rank_2"``. ``"rank_k"`` is the share of
            the texts with exactly ``k`` wrong characters. All values
            are scalars. They are ``NaN`` when no `update` ran since the
            last ``reset``.

        Example:
            The alphabet ``["a", "b"]`` gives the classes blank, ``"a"``,
            and ``"b"``. The first text decodes to ``"ab"``. The second
            text decodes to ``"aa"``, with one wrong character:

            >>> import torch
            >>> import torch.nn.functional as F
            >>> from torch import Size
            >>> from luxonis_train.nodes import OCRCTCHead
            >>> head = OCRCTCHead(
            ...     alphabet=["a", "b"],
            ...     input_shapes=[{"features": [Size([1, 8, 1, 4])]}],
            ... )
            >>> metric = OCRAccuracy(node=head)
            >>> classes = torch.tensor([[1, 1, 2, 0], [1, 0, 1, 0]])
            >>> text = torch.tensor([[97, 98], [97, 98]])
            >>> metric.update(F.one_hot(classes, 3).float(), text)
            >>> accuracy, ranks = metric.compute()
            >>> accuracy.item(), ranks["rank_1"].item()
            (0.5, 0.5)

        """
        return self.rank_0 / self.total, {
            "rank_0": self.rank_0 / self.total,
            "rank_1": self.rank_1 / self.total,
            "rank_2": self.rank_2 / self.total,
        }
