"""Precision, recall, and F1 over a grid of confidence thresholds.

The metric runs its own NMS on the pre-NMS candidates of the head. Thus
the confidence threshold of the head does not limit the curves.

"""

from typing import TYPE_CHECKING

import torch
from torch import Tensor
from torchvision.ops import box_convert, box_iou

from luxonis_train.nodes.heads.base_detection_head import BaseDetectionHead
from luxonis_train.tasks import Tasks
from luxonis_train.utils import non_max_suppression

from .base_metric import BaseMetric

if TYPE_CHECKING:
    from matplotlib.figure import Figure

DEFAULT_NUM_THRESHOLDS = 101
DEFAULT_MIN_CONFIDENCE = 0.0
DEFAULT_MAX_CONFIDENCE = 1.0

ARTIFACT_WIDTH = 1200
ARTIFACT_HEIGHT = 400


class PrecisionRecallCurve(BaseMetric):
    r"""Detection precision, recall, and F1 over a confidence grid.

    Inputs:
        - ``detections_pre_nms`` (``Tensor``): :math:`\left[B, N, 5 +
          n_{classes} + E\right]`, the NMS input of the head, boxes in
          ``xyxy`` pixels. :math:`E` is the number of extra values of a
          keypoint or segmentation head, else ``0``.
        - ``target_boundingbox`` (``Tensor``): :math:`\left[N_t,
          6\right]`, ``[batch, class, x, y, w, h]``, normalized

    Outputs:
        - ``confidence``, ``precision``, ``recall``, ``f1``
          (``Tensor``): :math:`\left[T\right]` over the threshold grid
        - ``max_f1``, ``confidence_at_max_f1`` (``Tensor``): scalar

    Formula:
        For each batch, the metric runs NMS with ``nms_conf_threshold``,
        ``nms_iou_threshold``, and ``max_detections``. It visits the kept
        detections of an image from the highest score to the lowest. A
        detection is a true positive when a free target of its class has
        an IoU of at least ``matching_iou_threshold`` with it. The
        detection then takes the free target with the highest IoU. For
        the threshold :math:`c`, the detections with a score of at least
        :math:`c` count:

        .. math::

            P(c) = \frac{TP(c)}{TP(c) + FP(c)}, \qquad
            R(c) = \frac{TP(c)}{N_t}, \qquad
            F_1(c) = \frac{2 \, P(c) \, R(c)}{P(c) + R(c)}

        :math:`N_t` is the number of targets of all batches. :math:`P`
        is ``1`` when no detection reaches :math:`c`, so the curve does
        not drop to ``0`` at the high thresholds. :math:`R` is ``0``
        when there are no targets, and :math:`F_1` is ``0`` when
        :math:`P + R = 0`.

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        - The node must be a `BaseDetectionHead`. The constructor calls
          `BaseDetectionHead.request_detections_pre_nms`, so the node
          adds the candidates to its packet in evaluation mode.
        - `get_loggable_values` selects ``max_f1`` as the logged value of
          the metric. `get_artifacts` draws the curves.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientBBoxHead
              inputs: [RepPANNeck]
              metrics:
                - name: PrecisionRecallCurve

    Compatible with:
        - Nodes:

          - `EfficientBBoxHead`
          - `EfficientKeypointBBoxHead`
          - `PrecisionBBoxHead`
          - `PrecisionSegmentBBoxHead`

    """

    supported_tasks = [
        Tasks.BOUNDINGBOX,
        Tasks.INSTANCE_KEYPOINTS,
        Tasks.INSTANCE_SEGMENTATION,
    ]

    node: BaseDetectionHead
    thresholds: Tensor
    true_positives: Tensor
    false_positives: Tensor
    target_count: Tensor

    def __init__(
        self,
        *,
        confidence_thresholds: list[float] | None = None,
        num_thresholds: int | None = None,
        min_confidence: float | None = None,
        max_confidence: float | None = None,
        matching_iou_threshold: float = 0.5,
        nms_conf_threshold: float = 1e-3,
        nms_iou_threshold: float | None = None,
        max_detections: int | None = None,
        **kwargs,
    ):
        """Build the threshold grid and resolve the NMS settings.

        Args:
            confidence_thresholds (list[float] | None): An explicit grid
                of at least two strictly increasing values in
                ``[0, 1]``. ``None`` builds a grid of ``num_thresholds``
                evenly spaced values from ``min_confidence`` to
                ``max_confidence``.
            num_thresholds (int | None): The number of values of the
                built grid, at least ``2``. ``None`` selects ``101``.
            min_confidence (float | None): The first value of the built
                grid, in ``[0, 1]``. ``None`` selects ``0.0``.
            max_confidence (float | None): The last value of the built
                grid, in ``[0, 1]`` and above ``min_confidence``.
                ``None`` selects ``1.0``.
            matching_iou_threshold (float): The smallest IoU, in
                ``[0, 1]``, at which a detection matches a target of its
                class.
            nms_conf_threshold (float): The score floor of NMS, in
                ``[0, 1]``. NMS drops the candidates below the floor, so
                they never count, not even at the first threshold. The
                metric uses the larger of this value and the first value
                of the grid. A lower floor keeps more candidates, and
                NMS then takes more time. A floor of ``0`` keeps every
                candidate with a score above ``0``.
            nms_iou_threshold (float | None): The IoU threshold of NMS,
                in ``[0, 1]``. ``None`` selects ``iou_thres`` of the node.
            max_detections (int | None): The largest number of detections
                that NMS keeps for each image, above ``0``. ``None``
                selects ``max_det`` of the node.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseMetric`. They must hold ``node``.

        Raises:
            ValueError: When ``confidence_thresholds`` comes with one of
                ``num_thresholds``, ``min_confidence``, or
                ``max_confidence``. Also when a value is outside its
                range, and when the explicit grid is not strictly
                increasing.

        """
        super().__init__(**kwargs)

        thresholds = self._build_thresholds(
            confidence_thresholds=confidence_thresholds,
            num_thresholds=num_thresholds,
            min_confidence=min_confidence,
            max_confidence=max_confidence,
        )
        self.register_buffer("thresholds", thresholds, persistent=False)

        self.matching_iou_threshold = self._validate_unit_interval(
            matching_iou_threshold,
            "matching_iou_threshold",
        )
        self.nms_iou_threshold = self._resolve_nms_iou_threshold(
            nms_iou_threshold
        )
        self.max_detections = self._resolve_max_detections(max_detections)
        self.lowest_threshold = float(thresholds[0])
        self.nms_conf_threshold = max(
            self._validate_unit_interval(
                nms_conf_threshold, "nms_conf_threshold"
            ),
            self.lowest_threshold,
        )

        self.add_state(
            "true_positives",
            default=torch.zeros(len(thresholds), dtype=torch.long),
            dist_reduce_fx="sum",
        )
        self.add_state(
            "false_positives",
            default=torch.zeros(len(thresholds), dtype=torch.long),
            dist_reduce_fx="sum",
        )
        self.add_state(
            "target_count",
            default=torch.tensor(0, dtype=torch.long),
            dist_reduce_fx="sum",
        )

        # The pre-NMS candidates are large; heads only keep them in
        # their output packet when a module such as this one asks for it.
        self.node.request_detections_pre_nms()

    @staticmethod
    def _validate_unit_interval(value: float, name: str) -> float:
        value = float(value)
        if not 0.0 <= value <= 1.0:
            raise ValueError(f"{name} must be between 0 and 1.")
        return value

    @classmethod
    def _build_thresholds(
        cls,
        *,
        confidence_thresholds: list[float] | None,
        num_thresholds: int | None,
        min_confidence: float | None,
        max_confidence: float | None,
    ) -> Tensor:
        if confidence_thresholds is not None:
            cls._reject_grid_parameters(
                num_thresholds=num_thresholds,
                min_confidence=min_confidence,
                max_confidence=max_confidence,
            )
            return cls._explicit_thresholds(confidence_thresholds)

        if num_thresholds is None:
            num_thresholds = DEFAULT_NUM_THRESHOLDS
        if min_confidence is None:
            min_confidence = DEFAULT_MIN_CONFIDENCE
        if max_confidence is None:
            max_confidence = DEFAULT_MAX_CONFIDENCE

        if num_thresholds < 2:
            raise ValueError("num_thresholds must be at least 2.")

        min_confidence = cls._validate_unit_interval(
            min_confidence,
            "min_confidence",
        )
        max_confidence = cls._validate_unit_interval(
            max_confidence,
            "max_confidence",
        )
        if min_confidence >= max_confidence:
            raise ValueError(
                "min_confidence must be lower than max_confidence."
            )

        return torch.linspace(
            min_confidence,
            max_confidence,
            num_thresholds,
            dtype=torch.float32,
        )

    def _resolve_nms_iou_threshold(self, value: float | None) -> float:
        if value is None:
            value = self.node.iou_thres
        return self._validate_unit_interval(value, "nms_iou_threshold")

    def _resolve_max_detections(self, value: int | None) -> int:
        if value is None:
            value = self.node.max_det
        if value <= 0:
            raise ValueError("max_detections must be positive.")
        return int(value)

    def update(
        self,
        detections_pre_nms: Tensor,
        target_boundingbox: Tensor,
    ) -> None:
        """Run NMS on one batch and add its counts to the states.

        For each threshold, the method adds the true positives and the
        false positives of the batch to ``true_positives`` and
        ``false_positives``. It adds the number of targets to
        ``target_count``. First, it replaces each state that ``reset``
        made in inference mode with a normal tensor.

        Args:
            detections_pre_nms (``Tensor``): The candidates of the head,
                of shape ``[B, N, 5 + n_classes + E]``. Each row holds
                the ``xyxy`` box in pixels, a constant ``1``, the class
                scores, and ``E`` extra values that the metric ignores.
            target_boundingbox (``Tensor``): The target boxes of shape
                ``[N_t, 6]``, as ``[batch, class, x, y, w, h]`` with
                normalized values. The method moves them to the device
                of the candidates.

        """
        self._detach_inference_states()

        target_boundingbox = target_boundingbox.to(detections_pre_nms.device)
        predictions = non_max_suppression(
            detections_pre_nms,
            n_classes=self.node.n_classes,
            conf_thres=_exclusive_threshold(
                self.nms_conf_threshold,
                detections_pre_nms.dtype,
            ),
            iou_thres=self.nms_iou_threshold,
            bbox_format="xyxy",
            max_det=self.max_detections,
            predicts_objectness=False,
        )

        scores, true_positive = self._match_predictions(
            predictions,
            target_boundingbox,
        )
        active = scores.unsqueeze(0) >= self.thresholds.unsqueeze(1)

        self.true_positives += (active & true_positive.unsqueeze(0)).sum(dim=1)
        self.false_positives += (active & ~true_positive.unsqueeze(0)).sum(
            dim=1
        )
        self.target_count += target_boundingbox.shape[0]

    def _detach_inference_states(self) -> None:
        """Replace the inference-mode states with normal tensors.

        Lightning runs the evaluation loop in ``torch.inference_mode``,
        and ``reset`` runs in that loop. The new states are thus
        inference tensors. An in-place update of such a tensor outside
        inference mode raises ``RuntimeError``. The quantization
        evaluation makes such updates.

        """
        if self.true_positives.is_inference():
            self.true_positives = self.true_positives.clone()
        if self.false_positives.is_inference():
            self.false_positives = self.false_positives.clone()
        if self.target_count.is_inference():
            self.target_count = self.target_count.clone()

    def _match_predictions(
        self,
        predictions: list[Tensor],
        target_boundingbox: Tensor,
    ) -> tuple[Tensor, Tensor]:
        all_scores: list[Tensor] = []
        all_true_positive: list[Tensor] = []

        height, width = self.node.original_in_shape[-2:]

        for image_index, image_predictions in enumerate(predictions):
            if image_predictions.numel() == 0:
                continue

            image_targets = target_boundingbox[
                target_boundingbox[:, 0].long() == image_index
            ]
            target_boxes, target_classes = self._prepare_targets(
                image_targets,
                height=height,
                width=width,
            )

            order = torch.argsort(
                image_predictions[:, 4],
                descending=True,
                stable=True,
            )
            image_predictions = image_predictions[order]

            all_scores.append(image_predictions[:, 4])
            all_true_positive.append(
                self._match_image_predictions(
                    prediction_boxes=image_predictions[:, :4],
                    prediction_classes=image_predictions[:, 5].long(),
                    target_boxes=target_boxes,
                    target_classes=target_classes,
                )
            )

        if not all_scores:
            return (
                target_boundingbox.new_empty((0,)),
                torch.empty(
                    0,
                    dtype=torch.bool,
                    device=target_boundingbox.device,
                ),
            )

        scores = torch.cat(all_scores)
        true_positive = torch.cat(all_true_positive)
        order = torch.argsort(scores, descending=True, stable=True)
        return scores[order], true_positive[order]

    def _match_image_predictions(
        self,
        *,
        prediction_boxes: Tensor,
        prediction_classes: Tensor,
        target_boxes: Tensor,
        target_classes: Tensor,
    ) -> Tensor:
        """Pair the score-sorted predictions of one image with targets.

        The method computes the IoU matrix once. The loop then visits
        only the predictions with at least one target of the same class
        at or above ``matching_iou_threshold``. Each prediction takes
        the free target with the highest IoU, and each target pairs
        once.

        Args:
            prediction_boxes (``Tensor``): The ``xyxy`` boxes of the
                predictions in pixels, of shape ``[M, 4]``, from the
                highest score to the lowest.
            prediction_classes (``Tensor``): The class index of each
                prediction, of shape ``[M]``.
            target_boxes (``Tensor``): The ``xyxy`` boxes of the targets
                in pixels, of shape ``[K, 4]``.
            target_classes (``Tensor``): The class index of each target,
                of shape ``[K]``.

        Returns:
            ``Tensor``: A ``bool`` tensor of shape ``[M]``. An item is
            ``True`` when its prediction pairs with a target.

        """
        true_positive = torch.zeros(
            len(prediction_boxes),
            dtype=torch.bool,
            device=prediction_boxes.device,
        )
        if len(target_boxes) == 0 or len(prediction_boxes) == 0:
            return true_positive

        ious = box_iou(prediction_boxes, target_boxes)
        eligible = (
            prediction_classes.unsqueeze(1) == target_classes.unsqueeze(0)
        ) & (ious >= self.matching_iou_threshold)
        matched_targets = torch.zeros(
            len(target_boxes),
            dtype=torch.bool,
            device=prediction_boxes.device,
        )

        candidates = eligible.any(dim=1).nonzero(as_tuple=True)[0]
        for prediction_index in candidates.tolist():
            available = eligible[prediction_index] & ~matched_targets
            if not bool(available.any()):
                continue

            target_index = int(
                torch.argmax(
                    ious[prediction_index].masked_fill(~available, -1)
                )
            )
            matched_targets[target_index] = True
            true_positive[prediction_index] = True

        return true_positive

    @staticmethod
    def _prepare_targets(
        image_targets: Tensor,
        *,
        height: int,
        width: int,
    ) -> tuple[Tensor, Tensor]:
        if image_targets.numel() == 0:
            return (
                image_targets.new_empty((0, 4)),
                torch.empty(
                    0,
                    dtype=torch.long,
                    device=image_targets.device,
                ),
            )

        boxes = box_convert(
            image_targets[:, 2:6],
            in_fmt="xywh",
            out_fmt="xyxy",
        )
        boxes[:, 0::2] *= width
        boxes[:, 1::2] *= height
        return boxes, image_targets[:, 1].long()

    def compute(self) -> dict[str, Tensor]:
        """Compute precision, recall, and F1 at each confidence threshold.

        The class docstring gives the formulas.

        Returns:
            ``dict[str, Tensor]``: The curves and their best point:

            - ``"confidence"``: the threshold grid, of shape ``[T]``.
            - ``"precision"``, ``"recall"``, ``"f1"``: the values at the
              thresholds, each of shape ``[T]``.
            - ``"max_f1"``: the largest F1, a scalar.
            - ``"confidence_at_max_f1"``: the first threshold that
              reaches ``max_f1``, a scalar.

        Example:
            One detection with the score ``0.8`` covers the only target.
            At the threshold ``0.9``, no detection counts. The precision
            there is ``1`` and the recall is ``0``:

            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import EfficientBBoxHead
            >>> head = EfficientBBoxHead(
            ...     n_heads=1,
            ...     n_classes=1,
            ...     input_shapes=[{"features": [Size([1, 8, 8, 8])]}],
            ...     original_in_shape=Size([3, 64, 64]),
            ... )
            >>> metric = PrecisionRecallCurve(
            ...     node=head, confidence_thresholds=[0.0, 0.5, 0.9]
            ... )
            >>> candidates = torch.tensor([[[0.0, 0.0, 32.0, 32.0, 1.0, 0.8]]])
            >>> target = torch.tensor([[0.0, 0.0, 0.0, 0.0, 0.5, 0.5]])
            >>> metric.update(candidates, target)
            >>> values = metric.compute()
            >>> values["precision"].tolist(), values["recall"].tolist()
            ([1.0, 1.0, 1.0], [1.0, 1.0, 0.0])

        """
        true_positives = self.true_positives.float()
        false_positives = self.false_positives.float()
        false_negatives = (self.target_count - self.true_positives).float()

        precision = torch.where(
            true_positives + false_positives > 0,
            true_positives / (true_positives + false_positives),
            # No prediction reaches the threshold, so nothing is
            # predicted incorrectly. Reporting 0 instead would drag the
            # curve to the floor over the whole high-confidence range.
            torch.ones_like(true_positives),
        )
        recall = torch.where(
            self.target_count > 0,
            true_positives / (true_positives + false_negatives),
            torch.zeros_like(true_positives),
        )
        f1 = torch.where(
            precision + recall > 0,
            2 * precision * recall / (precision + recall),
            torch.zeros_like(precision),
        )

        best_index = torch.argmax(f1)

        return {
            "confidence": self.thresholds,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "max_f1": f1[best_index],
            "confidence_at_max_f1": self.thresholds[best_index],
        }

    def get_loggable_values(
        self,
        values: dict[str, Tensor],
    ) -> tuple[Tensor, dict[str, Tensor]]:
        """Select ``max_f1`` as the logged value of the metric.

        The trainer logs only the returned values, so the curves stay out
        of the scalar logs.

        Args:
            values (``dict[str, Tensor]``): The result of `compute`.

        Returns:
            ``tuple[Tensor, dict[str, Tensor]]``: ``values["max_f1"]``,
            and a dictionary with the key ``"confidence_at_max_f1"``.

        """
        return values["max_f1"], {
            "confidence_at_max_f1": values["confidence_at_max_f1"],
        }

    def get_artifact_names(self) -> tuple[str, ...]:
        """Return the name of the curve image.

        Returns:
            ``tuple[str, ...]``: ``("curves",)``, the key that
            `get_artifacts` uses.

        """
        return ("curves",)

    def get_artifacts(
        self,
        values: dict[str, Tensor],
    ) -> dict[str, Tensor]:
        """Draw the curves of `build_curve_figure` as one image.

        The method closes the figure after it draws it.

        Args:
            values (``dict[str, Tensor]``): The result of `compute`.

        Returns:
            ``dict[str, Tensor]``: The key ``"curves"``, with a ``uint8``
            RGB image of shape ``[3, 400, 1200]``.

        """
        from luxonis_train.attached_modules.visualizers.utils import (
            figure_to_torch,
        )

        return {
            "curves": figure_to_torch(
                self.build_curve_figure(values),
                width=ARTIFACT_WIDTH,
                height=ARTIFACT_HEIGHT,
            )
        }

    def build_curve_figure(self, values: dict[str, Tensor]) -> "Figure":
        """Build a figure with three curve plots side by side.

        - Left: the precision over the recall.
        - Middle: the precision over the confidence.
        - Right: the recall over the confidence.

        The confidence axes span the threshold grid. All the other axes
        span ``[0, 1]``.

        Args:
            values (``dict[str, Tensor]``): The result of `compute`. The
                method reads ``"confidence"``, ``"precision"``, and
                ``"recall"``.

        Returns:
            ``Figure``: A ``matplotlib`` figure of ``12x4`` inches with a
            constrained layout.

        """
        from matplotlib.figure import Figure

        confidence = values["confidence"].detach().cpu().numpy()
        precision = values["precision"].detach().cpu().numpy()
        recall = values["recall"].detach().cpu().numpy()

        figure = Figure(
            figsize=(ARTIFACT_WIDTH / 100, ARTIFACT_HEIGHT / 100),
            layout="constrained",
        )
        axes = figure.subplots(1, 3)

        axes[0].plot(recall[::-1], precision[::-1])
        axes[0].set_title("Precision-Recall")
        axes[0].set_xlabel("Recall")
        axes[0].set_ylabel("Precision")
        axes[0].set_xlim(0, 1)

        axes[1].plot(confidence, precision)
        axes[1].set_title("Precision-Confidence")
        axes[1].set_xlabel("Confidence")
        axes[1].set_ylabel("Precision")

        axes[2].plot(confidence, recall)
        axes[2].set_title("Recall-Confidence")
        axes[2].set_xlabel("Confidence")
        axes[2].set_ylabel("Recall")

        # The confidence axes span the configured grid, which is not
        # necessarily the whole unit interval.
        for axis in axes[1:]:
            axis.set_xlim(float(confidence[0]), float(confidence[-1]))

        for axis in axes:
            axis.set_ylim(0, 1)
            axis.grid()

        return figure

    @staticmethod
    def _reject_grid_parameters(**grid_parameters: float | None) -> None:
        provided = sorted(
            name
            for name, value in grid_parameters.items()
            if value is not None
        )
        if provided:
            raise ValueError(
                "confidence_thresholds must not be combined with "
                f"{', '.join(provided)}; the explicit grid would "
                "silently take precedence."
            )

    @staticmethod
    def _explicit_thresholds(confidence_thresholds: list[float]) -> Tensor:
        thresholds = torch.tensor(confidence_thresholds, dtype=torch.float32)
        if thresholds.ndim != 1 or len(thresholds) < 2:
            raise ValueError(
                "confidence_thresholds must contain at least two values."
            )
        if torch.any(thresholds < 0) or torch.any(thresholds > 1):
            raise ValueError(
                "confidence_thresholds values must be between 0 and 1."
            )
        if not torch.all(thresholds[1:] > thresholds[:-1]):
            raise ValueError(
                "confidence_thresholds must be strictly increasing."
            )
        return thresholds


def _exclusive_threshold(value: float, dtype: torch.dtype) -> float:
    """Convert an inclusive confidence floor to an exclusive one.

    `non_max_suppression` keeps the candidates with a score strictly
    above ``conf_thres``, but the curve counts use ``>=``. The function
    returns the largest value below ``value`` in ``dtype``, as a
    ``float``. Thus the value does not round back to ``value``. A floor
    of ``0`` stays ``0``, so a candidate with the score ``0`` never
    counts.

    Args:
        value (float): The inclusive floor, in ``[0, 1]``.
        dtype (torch.dtype): The dtype of the scores that NMS compares
            with the floor.

    Returns:
        float: The exclusive floor for the ``conf_thres`` argument of
        `non_max_suppression`.

    """
    if value <= 0.0:
        return 0.0
    return float(
        torch.nextafter(
            torch.tensor(value, dtype=dtype),
            torch.tensor(float("-inf"), dtype=dtype),
        )
    )
