"""The ``torchmetrics`` classification metrics, wrapped for the
registry.

The wrapper fills in ``task`` and ``num_classes`` from the node it
attaches to, so a config only sets what it wants to override.

"""

from contextlib import suppress
from functools import cached_property

import torchmetrics
from torch import Tensor
from typing_extensions import override

from luxonis_train.tasks import Metadata, Tasks

from .base_metric import BaseMetric


class TorchMetricWrapper(BaseMetric):
    """Base wrapper for torchmetrics classification-style metrics.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, n_classes, ...]`` logits
          or scores
        - ``target`` (``Tensor``): ``[B, n_classes, ...]`` one-hot or
          ``[B, ...]`` indices

    Outputs:
        - ``Tensor``: scalar
        - ``dict[str, Tensor]``: per-class values, when
          ``per_class_metrics`` is set

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Infers binary, multiclass, or multilabel mode from parameters or
        the attached node.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``DiscSubNetHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: DiscSubNetHead
              inputs: [RecSubNet]
              metrics:
                - name: TorchMetricWrapper

    Compatible with:
        - Nodes:

          - `BiSeNetHead`
          - `DDRNetSegmentationHead`
          - `DiscSubNetHead`
          - `SegmentationHead`
          - `TransformerSegmentationHead`

    """

    Metric: type[torchmetrics.Metric]

    def __init__(self, **kwargs):
        super().__init__(node=kwargs.pop("node", None))
        task = self._infer_torchmetrics_task(**kwargs)
        self._torchmetric_task = task
        kwargs["task"] = task

        n_classes: int | None = kwargs.get(
            "num_classes", kwargs.get("num_labels")
        )

        if n_classes is None:
            with suppress(RuntimeError, ValueError):
                n_classes = self.n_classes

        if n_classes is None and task != "binary":
            arg_name = "num_classes" if task == "multiclass" else "num_labels"
            raise ValueError(
                f"'{self.name}' metric does not have the '{arg_name}' parameter set "
                "and it is not possible to infer it from the other arguments. "
                "You can either set the '{arg_name}' parameter explicitly, or use this metric with a node."
            )

        if task == "binary" and n_classes is not None and n_classes > 1:
            raise ValueError(
                f"Task type set to '{task}', but the dataset has more than 1 class. "
                f"Set the `task` argument of '{self.name}' to either 'multiclass' or 'multilabel'."
            )
        if task != "binary" and n_classes == 1:
            raise ValueError(
                f"Task type set to '{task}', but the dataset has only 1 class. "
                f"Set the `task` argument of '{self.name}' to 'binary'."
            )

        if task == "multiclass":
            kwargs["num_classes"] = n_classes
        elif task == "multilabel":
            kwargs["num_labels"] = n_classes

        self.metric = self.Metric(**kwargs)

    @override
    def update(self, predictions: Tensor, target: Tensor) -> None:
        if self._torchmetric_task == "multiclass":
            target = target.argmax(dim=1)
        self.metric.update(predictions, target)

    @override
    def compute(self) -> Tensor | tuple[Tensor, dict[str, Tensor]]:
        x = self.metric.compute()
        if not (isinstance(x, Tensor) and x.ndim > 0 and x.numel() > 1):
            return x
        if getattr(self, "classes", None):
            metric_name = type(self.metric).__name__
            class_names = {v: k for k, v in self.classes.items()}
            return x.mean(), {
                metric_name + "_" + class_names[i]: x[i]
                for i in range(x.numel())
            }
        raise ValueError(
            f"Metric '{self.name}' does not have 'classes' attribute set."
        )

    @override
    def reset(self) -> None:
        self.metric.reset()

    @cached_property
    @override
    def required_labels(self) -> set[str | Metadata]:
        if self.task == Tasks.ANOMALY_DETECTION:
            return Tasks.SEGMENTATION.required_labels
        return self.task.required_labels


class Accuracy(TorchMetricWrapper):
    """TorchMetrics accuracy adapter.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, n_classes, ...]`` logits
          or scores
        - ``target`` (``Tensor``): ``[B, n_classes, ...]`` one-hot or
          ``[B, ...]`` indices

    Outputs:
        - ``Tensor``: scalar
        - ``dict[str, Tensor]``: per-class values, when
          ``per_class_metrics`` is set

    Formula:
        Delegates accuracy accumulation and computation to
        ``torchmetrics.Accuracy``.

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Uses ``TorchMetricWrapper`` task inference and optional
        per-class output handling.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              metrics:
                - name: Accuracy

    Compatible with:
        - Used by: `ClassificationModel`
        - Nodes:

          - `BiSeNetHead`
          - `ClassificationHead`
          - `DDRNetSegmentationHead`
          - `DiscSubNetHead`
          - `SegmentationHead`
          - `TransformerClassificationHead`
          - `TransformerSegmentationHead`

    """

    supported_tasks = [
        Tasks.CLASSIFICATION,
        Tasks.SEGMENTATION,
        Tasks.ANOMALY_DETECTION,
    ]
    Metric = torchmetrics.Accuracy


class F1Score(TorchMetricWrapper):
    """TorchMetrics F1 score adapter.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, n_classes, ...]`` logits
          or scores
        - ``target`` (``Tensor``): ``[B, n_classes, ...]`` one-hot or
          ``[B, ...]`` indices

    Outputs:
        - ``Tensor``: scalar
        - ``dict[str, Tensor]``: per-class values, when
          ``per_class_metrics`` is set

    Formula:
        Delegates F1 accumulation and computation to ``torchmetrics.F1Score``.

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Uses ``TorchMetricWrapper`` task inference and optional
        per-class output handling.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              metrics:
                - name: F1Score

    Compatible with:
        - Used by:

          - `ClassificationModel`
          - `SegmentationModel`

        - Nodes:

          - `BiSeNetHead`
          - `ClassificationHead`
          - `DDRNetSegmentationHead`
          - `DiscSubNetHead`
          - `SegmentationHead`
          - `TransformerClassificationHead`
          - `TransformerSegmentationHead`

    """

    supported_tasks = [
        Tasks.CLASSIFICATION,
        Tasks.SEGMENTATION,
        Tasks.ANOMALY_DETECTION,
    ]
    Metric = torchmetrics.F1Score


class JaccardIndex(TorchMetricWrapper):
    """TorchMetrics Jaccard index adapter.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, n_classes, ...]`` logits
          or scores
        - ``target`` (``Tensor``): ``[B, n_classes, ...]`` one-hot or
          ``[B, ...]`` indices

    Outputs:
        - ``Tensor``: scalar
        - ``dict[str, Tensor]``: per-class values, when
          ``per_class_metrics`` is set

    Formula:
        Delegates Jaccard accumulation and computation to
        ``torchmetrics.JaccardIndex``.

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Uses ``TorchMetricWrapper`` task inference and optional
        per-class output handling.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              metrics:
                - name: JaccardIndex

    Compatible with:
        - Used by:

          - `AnomalyDetectionModel`
          - `SegmentationModel`

        - Nodes:

          - `BiSeNetHead`
          - `ClassificationHead`
          - `DDRNetSegmentationHead`
          - `DiscSubNetHead`
          - `SegmentationHead`
          - `TransformerClassificationHead`
          - `TransformerSegmentationHead`

    """

    supported_tasks = [
        Tasks.CLASSIFICATION,
        Tasks.SEGMENTATION,
        Tasks.ANOMALY_DETECTION,
    ]
    Metric = torchmetrics.JaccardIndex


class Precision(TorchMetricWrapper):
    """TorchMetrics precision adapter.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, n_classes, ...]`` logits
          or scores
        - ``target`` (``Tensor``): ``[B, n_classes, ...]`` one-hot or
          ``[B, ...]`` indices

    Outputs:
        - ``Tensor``: scalar
        - ``dict[str, Tensor]``: per-class values, when
          ``per_class_metrics`` is set

    Formula:
        Delegates precision accumulation and computation to
        ``torchmetrics.Precision``.

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Uses ``TorchMetricWrapper`` task inference and optional
        per-class output handling.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              metrics:
                - name: Precision

    Compatible with:
        - Nodes:

          - `BiSeNetHead`
          - `ClassificationHead`
          - `DDRNetSegmentationHead`
          - `DiscSubNetHead`
          - `SegmentationHead`
          - `TransformerClassificationHead`
          - `TransformerSegmentationHead`

    """

    supported_tasks = [
        Tasks.CLASSIFICATION,
        Tasks.SEGMENTATION,
        Tasks.ANOMALY_DETECTION,
    ]
    Metric = torchmetrics.Precision


class Recall(TorchMetricWrapper):
    """TorchMetrics recall adapter.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, n_classes, ...]`` logits
          or scores
        - ``target`` (``Tensor``): ``[B, n_classes, ...]`` one-hot or
          ``[B, ...]`` indices

    Outputs:
        - ``Tensor``: scalar
        - ``dict[str, Tensor]``: per-class values, when
          ``per_class_metrics`` is set

    Formula:
        Delegates recall accumulation and computation to ``torchmetrics.Recall``.

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Uses ``TorchMetricWrapper`` task inference and optional
        per-class output handling.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``ClassificationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]
              metrics:
                - name: Recall

    Compatible with:
        - Used by: `ClassificationModel`
        - Nodes:

          - `BiSeNetHead`
          - `ClassificationHead`
          - `DDRNetSegmentationHead`
          - `DiscSubNetHead`
          - `SegmentationHead`
          - `TransformerClassificationHead`
          - `TransformerSegmentationHead`

    """

    supported_tasks = [
        Tasks.CLASSIFICATION,
        Tasks.SEGMENTATION,
        Tasks.ANOMALY_DETECTION,
    ]
    Metric = torchmetrics.Recall
