"""A classification head with pooling, dropout, and a linear layer."""

from luxonis_ml.typing import Params
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.heads import BaseHead
from luxonis_train.tasks import Tasks


class ClassificationHead(BaseHead):
    r"""Classification head with one linear layer.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, h, w\right]`

    Outputs:
        - ``classification`` (``Tensor``): :math:`\left[B,
          n_{classes}\right]` logits

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        The head applies global average pooling, dropout, and one linear
        layer. The feature map can have any height :math:`h` and width
        :math:`w`. ``forward`` does not check the mode, so export mode
        also gives the logits. The dropout acts only in training mode.

    Variants:
        None. Configure the node through ``params``.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: ClassificationHead
              inputs: [ResNet]

    Compatible with:
        - Attach index: ``-1``, the last output of the input node
        - Required labels: ``classification``
        - Used by: `ClassificationModel`
        - Losses:

          - `BCEWithLogitsLoss`
          - `CrossEntropyLoss`
          - `OHEMLoss`
          - `SigmoidFocalLoss`
          - `SmoothBCEWithLogitsLoss`
          - `SoftmaxFocalLoss`

        - Metrics:

          - `Accuracy`
          - `ConfusionMatrix`
          - `F1Score`
          - `JaccardIndex`
          - `Precision`
          - `Recall`

        - Visualizers: `ClassificationVisualizer`
        - Export parser: ``ClassificationParser``

    """

    in_channels: int
    task = Tasks.CLASSIFICATION
    parser: str = "ClassificationParser"

    def __init__(self, dropout_rate: float = 0.2, **kwargs):
        """Build the pooling, the dropout, and the linear layer.

        Args:
            dropout_rate (float): The probability that the dropout layer
                sets a pooled feature to zero in training mode, in
                ``[0, 1]``.
            **kwargs (``Any``): Keyword arguments for `BaseNode`. They
                must hold ``input_shapes`` or ``in_sizes``, and the class
                count through ``n_classes`` or ``dataset_metadata``.

        """
        super().__init__(**kwargs)

        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Dropout(dropout_rate),
            nn.Linear(self.in_channels, self.n_classes),
        )

    def forward(self, inputs: Tensor) -> Tensor:
        """Compute the class logits.

        Args:
            inputs (``Tensor``): The feature map of shape
                ``[B, C, h, w]``.

        Returns:
            ``Tensor``: The logits of shape ``[B, n_classes]``.
            `BaseNode.run` puts them under the ``"classification"`` key.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import ClassificationHead
            >>> head = ClassificationHead(
            ...     n_classes=4,
            ...     input_shapes=[{"features": [Size([2, 16, 7, 7])]}],
            ... )
            >>> head(torch.zeros(2, 16, 7, 7)).shape
            torch.Size([2, 4])

        """
        return self.head(inputs)

    @override
    def get_custom_head_config(self) -> Params:
        return {"is_softmax": False}
