"""The decoupled detection head of YOLOv6."""

import math
from collections.abc import Iterable
from typing import Literal, cast

import torch
from luxonis_ml.typing import Params
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.blocks import EfficientDecoupledBlock
from luxonis_train.nodes.heads.base_detection_head import BaseDetectionHead
from luxonis_train.tasks import Tasks
from luxonis_train.typing import Packet
from luxonis_train.utils import (
    anchors_for_fpn_features,
    dist2bbox,
    non_max_suppression,
)


class EfficientBBoxHead(BaseDetectionHead):
    r"""Efficient object detection head.

    Inputs:
        - ``inputs`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
          W_i\right]` per scale

    Outputs:
        - train:

          - ``features`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
            W_i\right]` per scale
          - ``class_scores`` (``Tensor``): :math:`\left[B, N,
            n_{classes}\right]`
          - ``distributions`` (``Tensor``): :math:`\left[B, N,
            4\right]`, ``(l, t, r, b)`` in stride units

        - eval:

          - ``features`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
            W_i\right]` per scale
          - ``class_scores`` (``Tensor``): :math:`\left[B, N,
            n_{classes}\right]`
          - ``distributions`` (``Tensor``): :math:`\left[B, N,
            4\right]`, ``(l, t, r, b)`` in stride units
          - ``boundingbox`` (``list[Tensor]``): :math:`\left[M_i,
            6\right]` per image, ``[x1, y1, x2, y2, conf, class]``,
            pixels
          - ``detections_pre_nms`` (``Tensor``): :math:`\left[B, N, 5 +
            n_{classes}\right]`, only when requested

        - export:

          - ``boundingbox`` (``list[Tensor]``): :math:`\left[B, 5 +
            n_{classes}, H_i, W_i\right]` per scale, ``(l, t, r, b)``
            then scores

    References:
        - Source: Reimplemented from `YOLOv6: A Single-Stage Object
          Detection Framework for Industrial Applications
          <https://arxiv.org/abs/2209.02976>`_.
        - License: Apache-2.0 (this project)

    Notes:
        The head runs one `EfficientDecoupledBlock` for each scale. In
        evaluation mode, it decodes the distances around the anchor
        points into boxes and runs NMS. Training mode and export mode
        skip this step.

    Variants:
        None. Configure the node through ``params``.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: EfficientBBoxHead
              inputs: [RepPANNeck]

    Compatible with:
        - Required labels: ``boundingbox``
        - Used by: `DetectionModel`
        - Losses: `AdaptiveDetectionLoss`
        - Metrics:

          - `ConfusionMatrix`
          - `MeanAveragePrecision`
          - `PrecisionRecallCurve`

        - Visualizers: `BBoxVisualizer`
        - Export parser: ``YOLO``
        - Pretrained weights: available through ``weights: download``

    """

    task = Tasks.BOUNDINGBOX

    def __init__(
        self,
        n_heads: Literal[2, 3, 4] = 3,
        conf_thres: float = 0.25,
        iou_thres: float = 0.45,
        max_det: int = 300,
        bias_init_p: float = 1e-2,
        **kwargs,
    ):
        """Initialize one decoupled block for each scale.

        Args:
            n_heads (``Literal[2, 3, 4]``): Number of scales. The head
                reads the last ``n_heads`` outputs of the input node. An
                ``attach_index`` param replaces this selection. The value
                is usually equal to the number of neck outputs. When the
                input node gives fewer outputs, the head logs a warning
                and uses that number. Defaults to ``3``.
            conf_thres (float): NMS keeps only the boxes whose maximum
                class score is above this value. The value must be in
                ``[0, 1]``. Defaults to ``0.25``.
            iou_thres (float): NMS removes a box when its IoU with a box of
                the same class and a higher score is above this value.
                The value must be in ``[0, 1]``. Defaults to ``0.45``.
            max_det (int): Maximum number of boxes that NMS keeps for each
                image. Defaults to ``300``.
            bias_init_p (float): Initial class score of every anchor point.
                `initialize_weights` sets the class bias from it.
                Defaults to ``1e-2``.
            **kwargs (``Any``): Keyword arguments for `BaseNode`, such as
                ``n_classes`` and ``input_shapes``.

        """
        super().__init__(
            n_heads=n_heads,
            conf_thres=conf_thres,
            iou_thres=iou_thres,
            max_det=max_det,
            **kwargs,
        )

        self.grid_cell_offset = 0.5
        self.grid_cell_size = 5.0

        self.heads = cast(list[EfficientDecoupledBlock], nn.ModuleList())

        for i in range(self._n_heads):
            self.heads.append(
                EfficientDecoupledBlock(
                    in_channels=self.in_channels[i], n_classes=self.n_classes
                )
            )
        self._bias_init_p = bias_init_p

    @override
    def initialize_weights(self, method: str | None = None) -> None:
        r"""Initialize the weights and the priors of the last layers.

        The method first calls `BaseNode.initialize_weights`. Then, for
        each scale, it sets the weights of the last convolution of both
        branches to zero. The bias of the class branch becomes
        :math:`-\log\left((1 - p) / p\right)`, where :math:`p` is
        ``bias_init_p``. The bias of the regression branch becomes ``1``.
        A new head thus predicts the class score ``bias_init_p`` and the
        distance ``1`` for every anchor point and every input.

        Args:
            method (str | None): Method for `BaseNode.initialize_weights`.
                ``"yolo"`` changes the batch norm and activation settings.
                Other values skip that step. Defaults to ``None``.

        Example:
            The node calls the method after construction, so a new head
            already gives these outputs:

            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import EfficientBBoxHead
            >>> sizes = [Size([1, 8, 32, 32]), Size([1, 16, 16, 16])]
            >>> head = EfficientBBoxHead(
            ...     n_heads=2,
            ...     n_classes=2,
            ...     input_shapes=[{"features": sizes}],
            ...     original_in_shape=Size([3, 256, 256]),
            ... )
            >>> out = head([torch.zeros(size) for size in sizes])
            >>> torch.allclose(out["class_scores"], torch.tensor(0.01))
            True
            >>> out["distributions"].unique().tolist()
            [1.0]

        """
        super().initialize_weights(method)
        for head in self.heads:
            data = [
                (
                    head.class_branch[-1],
                    -math.log((1 - self._bias_init_p) / self._bias_init_p),
                ),
                (head.regression_branch[-1], 1.0),
            ]
            for module, fill_value in data:
                assert isinstance(module, nn.Conv2d)
                assert module.bias is not None

                nn.init.constant_(module.weight, 0)
                nn.init.constant_(module.bias, fill_value)

    @override
    def load_checkpoint(
        self, path: str | None = None, strict: bool = False
    ) -> None:
        """Load a checkpoint, with a non-strict key match by default.

        The method passes ``path`` as ``ckpt`` to
        `BaseNode.load_checkpoint`. The override renames the first
        parameter and sets the default of ``strict`` to ``False``.

        **Warning:** The override has no ``ckpt`` parameter. After
        construction, the node calls ``load_checkpoint(ckpt=...)`` for a
        ``weights`` URL. Thus, a call such as
        ``EfficientBBoxHead(weights="https://...")`` raises ``TypeError``.

        Args:
            path (str | None): Local path or URL of a ``.ckpt`` file.
                `LuxonisLightningModule` also gives a state dictionary,
                and the base method loads it directly. ``None`` or ``""``
                takes the URL from `get_weights_url`. That call fails
                when no variant built the node.
            strict (bool): Whether the keys of the checkpoint must match
                the keys of the head exactly. Defaults to ``False``.

        """
        return super().load_checkpoint(path, strict=strict)

    def forward(self, inputs: list[Tensor]) -> Packet[Tensor]:
        """Run the block of each scale and build the packet of the mode.

        Each `EfficientDecoupledBlock` returns the decoded features, the
        class logits, and the distances of one scale. The head applies a
        sigmoid to the class logits. Export mode has priority over
        training mode. The packet depends on the mode:

        - Export mode: ``"boundingbox"`` holds one map of shape
          ``[B, 5 + n_classes, H_i, W_i]`` for each scale. Its channels
          are the distances ``(l, t, r, b)``, the maximum class score,
          and the class scores.
        - Training mode: ``"features"`` holds the decoded feature map
          of shape ``[B, C_i, H_i, W_i]`` for each scale.
          ``"class_scores"`` of shape ``[B, N, n_classes]`` and
          ``"distributions"`` of shape ``[B, N, 4]`` hold the class
          scores and the distances of all ``N`` anchor points. The
          distances ``(l, t, r, b)`` are in stride units. ``N`` is the
          sum of ``H_i * W_i``.
        - Evaluation mode: the training keys and ``"boundingbox"``. The
          head decodes the distances into boxes in pixels and runs NMS.
          Each image gets a tensor of shape ``[M_i, 6]`` with the rows
          ``[x1, y1, x2, y2, score, class]``. An image without boxes
          gets a tensor of shape ``[0, 5 + n_classes]``. After a call to
          `BaseDetectionHead.request_detections_pre_nms`, the packet
          also holds ``"detections_pre_nms"``. This is the NMS input of
          shape ``[B, N, 5 + n_classes]``: the ``xyxy`` box in pixels, a
          constant ``1``, and the class scores.

        Args:
            inputs (``list[Tensor]``): One feature map for each scale, of
                shape ``[B, C_i, H_i, W_i]``.

        Returns:
            ``Packet[Tensor]``: The packet of the current mode.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import EfficientBBoxHead
            >>> sizes = [Size([1, 8, 32, 32]), Size([1, 16, 16, 16])]
            >>> head = EfficientBBoxHead(
            ...     n_heads=2,
            ...     n_classes=3,
            ...     input_shapes=[{"features": sizes}],
            ...     original_in_shape=Size([3, 256, 256]),
            ... )
            >>> out = head([torch.zeros(size) for size in sizes])
            >>> out["class_scores"].shape, out["distributions"].shape
            (torch.Size([1, 1280, 3]), torch.Size([1, 1280, 4]))

            A new head gives each class the score ``0.01``, which is
            below ``conf_thres``. In evaluation mode, NMS thus keeps no
            box:

            >>> out = head.eval()([torch.zeros(size) for size in sizes])
            >>> sorted(out)
            ['boundingbox', 'class_scores', 'distributions', 'features']
            >>> out["boundingbox"][0].shape
            torch.Size([0, 8])

        """
        features_list, classes_list, regressions_list = self._forward(inputs)

        if self.export:
            return self._wrap_export(classes_list, regressions_list)

        class_scores = self._postprocess(classes_list)
        distributions = self._postprocess(regressions_list)

        if self.training:
            return {
                "features": features_list,
                "class_scores": class_scores,
                "distributions": distributions,
            }

        _, anchor_points, _, stride_tensor = anchors_for_fpn_features(
            features_list,
            self.stride,
            self.grid_cell_size,
            self.grid_cell_offset,
            multiply_with_stride=False,
        )
        detections_pre_nms = self._prepare_bbox_inference_output(
            features_list,
            class_scores,
            distributions,
            anchor_points,
            stride_tensor,
        )
        bboxes = self._run_nms(detections_pre_nms)
        packet: Packet[Tensor] = {
            self.task.main_output: bboxes,
            "features": features_list,
            "class_scores": class_scores,
            "distributions": distributions,
        }
        if self.keep_detections_pre_nms:
            packet["detections_pre_nms"] = detections_pre_nms
        return packet

    @staticmethod
    def _wrap_export(
        classes_list: list[Tensor], regressions_list: list[Tensor]
    ) -> Packet[Tensor]:
        """Build the export map of each scale.

        Args:
            classes_list (``list[Tensor]``): Class scores of shape
                ``[B, n_classes, H_i, W_i]`` for each scale.
            regressions_list (``list[Tensor]``): Distances of shape
                ``[B, 4, H_i, W_i]`` for each scale.

        Returns:
            ``Packet[Tensor]``: The key ``"boundingbox"`` with one map of
            shape ``[B, 5 + n_classes, H_i, W_i]`` for each scale. Its
            channels are the distances, the maximum class score, and the
            class scores.

        """
        bboxes: list[Tensor] = []
        for classes, regressions in zip(
            classes_list, regressions_list, strict=True
        ):
            conf, _ = classes.max(1, keepdim=True)
            out = torch.cat([regressions, conf, classes], dim=1)
            bboxes.append(out)
        return {"boundingbox": bboxes}

    @staticmethod
    def _postprocess(outputs: Iterable[Tensor]) -> Tensor:
        """Flatten the maps of all scales and join them.

        Args:
            outputs (``Iterable[Tensor]``): One tensor of shape
                ``[B, C, H_i, W_i]`` or ``[B, C, H_i * W_i]`` for each
                scale.

        Returns:
            ``Tensor``: Tensor of shape ``[B, N, C]``, where ``N`` is the
            sum of ``H_i * W_i``.

        """
        return torch.cat([out.flatten(2) for out in outputs], dim=2).permute(
            0, 2, 1
        )

    @override
    def get_weights_url(self) -> str:
        """Return the COCO checkpoint URL for the selected variant.

        This base head defines no variants itself; only subclasses with
        variants can use the URL.

        """
        return f"{{github}}/efficientbbox_head_{self.variant[0]}_coco.ckpt"

    @property
    @override
    def export_output_names(self) -> list[str] | None:
        """The names of the ``n_heads`` outputs of the exported model.

        The default names are ``output1_yolov6r2``,
        ``output2_yolov6r2``, and so on. These names are compatible with
        DepthAI. The ``export_output_names`` param replaces them only
        when it holds exactly ``n_heads`` names. The head logs a warning
        each time it gives the default names. The value is never
        ``None``.

        """
        return self.get_output_names(
            [f"output{i + 1}_yolov6r2" for i in range(self._n_heads)]
        )

    def _prepare_bbox_inference_output(
        self,
        features: list[Tensor],
        class_scores: Tensor,
        distributions: Tensor,
        anchor_points: Tensor,
        stride_tensor: Tensor,
        *,
        tail: list[Tensor] | None = None,
    ) -> Tensor:
        """Decode the predictions into the input tensor of NMS.

        Args:
            features (``list[Tensor]``): Feature maps of the scales. The
                method reads only the batch size of the last map.
            class_scores (``Tensor``): Class scores of shape
                ``[B, N, n_classes]``.
            distributions (``Tensor``): Distances ``(l, t, r, b)`` in
                stride units, of shape ``[B, N, 4]``.
            anchor_points (``Tensor``): Anchor points in grid units, of
                shape ``[N, 2]``.
            stride_tensor (``Tensor``): Stride of each anchor point, of
                shape ``[N, 1]``.
            tail (``list[Tensor] | None``): Tensors of shape ``[B, N, D_j]``
                to add after the class scores, in list order. NMS keeps
                these values with each box. Defaults to ``None``.

        Returns:
            ``Tensor``: Tensor of shape ``[B, N, 5 + n_classes + D]``,
            where ``D`` is the sum of all ``D_j``. Each row holds the
            ``xyxy`` box in pixels, a constant ``1``, the class scores,
            and the tail values.

        """
        tail = tail or []
        bboxes = dist2bbox(distributions, anchor_points, out_format="xyxy")

        bboxes *= stride_tensor
        return torch.cat(
            [
                bboxes,
                torch.ones(
                    (features[-1].shape[0], bboxes.shape[1], 1),
                    dtype=bboxes.dtype,
                    device=bboxes.device,
                ),
                class_scores,
                *tail,
            ],
            dim=-1,
        )

    def _run_nms(self, detections_pre_nms: Tensor) -> list[Tensor]:
        """Run NMS on the decoded candidates of each image.

        Args:
            detections_pre_nms (``Tensor``): Output of
                ``_prepare_bbox_inference_output``, of shape
                ``[B, N, 5 + n_classes + D]``.

        Returns:
            ``list[Tensor]``: One tensor of shape ``[M_i, 6 + D]`` for
            each image, with ``M_i`` at most ``max_det``. Each row holds
            ``[x1, y1, x2, y2, score, class]`` and the tail values. An
            image without boxes gets a tensor of shape
            ``[0, 5 + n_classes + D]``.

        """
        return non_max_suppression(
            detections_pre_nms,
            n_classes=self.n_classes,
            conf_thres=self._conf_thres,
            iou_thres=self.iou_thres,
            bbox_format="xyxy",
            max_det=self.max_det,
            predicts_objectness=False,
        )

    @override
    def get_custom_head_config(self) -> Params:
        return super().get_custom_head_config() | {"subtype": "yolov6r2"}
