"""The YOLO-Pose head, which predicts keypoints beside the boxes."""

from typing import Literal

import torch
from luxonis_ml.typing import Params
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.blocks import ConvBlock
from luxonis_train.tasks import Tasks
from luxonis_train.typing import Packet
from luxonis_train.utils import anchors_for_fpn_features

from .efficient_bbox_head import EfficientBBoxHead


class EfficientKeypointBBoxHead(EfficientBBoxHead):
    r"""Efficient object and keypoint detection head.

    Inputs:
        - ``inputs`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
          W_i\right]` per scale

    Outputs:
        - train:

          - ``features`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
            W_i\right]` per scale
          - ``class_scores`` (``Tensor``): :math:`\left[B, N,
            n_{classes}\right]`
          - ``distributions`` (``Tensor``): :math:`\left[B, N,
            4\right]`, ``(l, t, r, b)`` in stride units
          - ``keypoints_raw`` (``Tensor``): :math:`\left[B, N, 3 *
            n_{keypoints}\right]`

        - eval:

          - ``features`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
            W_i\right]` per scale
          - ``class_scores`` (``Tensor``): :math:`\left[B, N,
            n_{classes}\right]`
          - ``distributions`` (``Tensor``): :math:`\left[B, N,
            4\right]`, ``(l, t, r, b)`` in stride units
          - ``keypoints_raw`` (``Tensor``): :math:`\left[B, N, 3 *
            n_{keypoints}\right]`
          - ``boundingbox`` (``list[Tensor]``): :math:`\left[M_i,
            6\right]` per image, ``[x1, y1, x2, y2, conf, class]``,
            pixels
          - ``keypoints`` (``list[Tensor]``): :math:`\left[M_i,
            n_{keypoints}, 3\right]` per image, ``(x, y, conf)``, pixels
          - ``detections_pre_nms`` (``Tensor``): :math:`\left[B, N, 5 +
            n_{classes}\right]`, only when requested

        - export:

          - ``boundingbox`` (``list[Tensor]``): :math:`\left[B, 5 +
            n_{classes}, H_i, W_i\right]` per scale
          - ``keypoints`` (``list[Tensor]``): :math:`\left[B, 3 *
            n_{keypoints}, H_i * W_i\right]` per scale

    References:
        - Source: Reimplemented from `YOLOv6: A Single-Stage Object
          Detection Framework for Industrial Applications
          <https://arxiv.org/abs/2209.02976>`_.
        - License: Apache-2.0 (this project)

    Notes:
        Extends ``EfficientBBoxHead`` with per-scale keypoint heads and
        keypoint decoding relative to FPN anchors.

    Variants:
        - ``None``:
            - Default: yes
            - Aliases: None
            - Parameters:
                - No predefined variants.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: EfficientKeypointBBoxHead
              inputs: [RepPANNeck]

    Compatible with:
        - Required labels: ``boundingbox``, ``keypoints``
        - Used by: `KeypointDetectionModel`
        - Losses: `EfficientKeypointBBoxLoss`
        - Metrics: `ConfusionMatrix`, `MeanAveragePrecision`,
          `ObjectKeypointSimilarity`, `PrecisionRecallCurve`
        - Visualizers: `KeypointVisualizer`
        - Export parser: ``YOLOExtendedParser``

    """

    parser = "YOLOExtendedParser"
    task = Tasks.INSTANCE_KEYPOINTS

    def __init__(
        self,
        n_heads: Literal[2, 3, 4] = 3,
        conf_thres: float = 0.25,
        iou_thres: float = 0.45,
        max_det: int = 300,
        **kwargs,
    ):
        """Head for object and keypoint detection.

        Adapted from `YOLOv6: A Single-Stage Object Detection Framework for Industrial
        Applications <https://arxiv.org/pdf/2209.02976.pdf>`_.

        Args:
            n_heads (``Literal[2, 3, 4]``): Number of output heads. Defaults to ``3``. Note: Should be same also on neck in most cases.
            conf_thres (float): Threshold for confidence. Defaults to ``0.25``.
            iou_thres (float): Threshold for IoU. Defaults to ``0.45``.
            max_det (int): Maximum number of detections retained after NMS. Defaults to ``300``.
            **kwargs (``Any``): Keyword arguments forwarded to the parent class.

        """
        super().__init__(
            n_heads=n_heads,
            conf_thres=conf_thres,
            iou_thres=iou_thres,
            max_det=max_det,
            **kwargs,
        )

        self.n_keypoints_flat = self.n_keypoints * 3

        mid_channels = max(self.in_channels[0] // 4, self.n_keypoints_flat)
        self.keypoint_heads = nn.ModuleList(
            nn.Sequential(
                ConvBlock(
                    in_channels=self.in_channels[i],
                    out_channels=mid_channels,
                    kernel_size=3,
                    stride=1,
                    padding=1,
                    activation=nn.SiLU(),
                ),
                ConvBlock(
                    in_channels=mid_channels,
                    out_channels=mid_channels,
                    kernel_size=3,
                    stride=1,
                    padding=1,
                    activation=nn.SiLU(),
                ),
                nn.Conv2d(
                    in_channels=mid_channels,
                    out_channels=self.n_keypoints_flat,
                    kernel_size=1,
                    stride=1,
                ),
            )
            for i in range(len(self.heads))
        )

    def forward(self, inputs: list[Tensor]) -> Packet[Tensor]:
        features_list, classes_list, regressions_list = super()._forward(
            inputs
        )
        keypoints_list: list[Tensor] = []

        for head, x in zip(self.keypoint_heads, inputs, strict=True):
            keypoints_list.append(head(x))

        bs = features_list[0].shape[0]
        if self.export:
            packet = self._wrap_export(classes_list, regressions_list)
            keypoints = []
            for i, keypoint in enumerate(keypoints_list):
                keypoints.append(
                    self._distributions_to_keypoints(
                        keypoint.view(bs, self.n_keypoints_flat, -1),
                        features_list,
                        bs,
                        i,
                        apply_sigmoid=False,
                    )
                )
            return packet | {"keypoints": keypoints}

        class_scores = self._postprocess(classes_list)
        distributions = self._postprocess(regressions_list)
        keypoints_raw = self._postprocess(
            out.view(bs, self.n_keypoints_flat, -1) for out in keypoints_list
        )

        if self.training:
            return {
                "features": features_list,
                "class_scores": class_scores,
                "distributions": distributions,
                "keypoints_raw": keypoints_raw,
            }

        pred_keypoints = torch.cat(
            [
                self._distributions_to_keypoints(
                    keypoint.view(bs, self.n_keypoints_flat, -1),
                    features_list,
                    bs,
                    i,
                )
                for i, keypoint in enumerate(keypoints_list)
            ],
            dim=2,
        ).permute(0, 2, 1)

        _, anchor_points, _, stride_tensor = anchors_for_fpn_features(
            features_list,
            self.stride,
            self.grid_cell_size,
            self.grid_cell_offset,
            multiply_with_stride=False,
        )
        detections_pre_nms = self._prepare_bbox_inference_output(
            features_list,
            class_scores,
            distributions,
            anchor_points,
            stride_tensor,
            tail=[pred_keypoints],
        )
        boxes, kpts = self._split_keypoint_detections(
            self._run_nms(detections_pre_nms)
        )
        packet: Packet[Tensor] = {
            "boundingbox": boxes,
            "keypoints": kpts,
            "features": features_list,
            "class_scores": class_scores,
            "distributions": distributions,
            "keypoints_raw": keypoints_raw,
        }
        if self.keep_detections_pre_nms:
            packet["detections_pre_nms"] = detections_pre_nms
        return packet

    @property
    @override
    def export_output_names(self) -> list[str] | None:
        return self.get_output_names(
            [f"output{i + 1}_yolov6" for i in range(self.n_heads)]
            + [f"kpt_output{i + 1}" for i in range(self.n_heads)]
        )

    @override
    def get_custom_head_config(self) -> Params:
        return super().get_custom_head_config() | {
            "n_keypoints": self.n_keypoints
        }

    def _distributions_to_keypoints(
        self,
        keypoints: Tensor,
        features: list[Tensor],
        batch_size: int,
        index: int,
        apply_sigmoid: bool = True,
    ) -> Tensor:
        _, anchor_points, n_anchors_list, _ = anchors_for_fpn_features(
            features,
            self.stride,
            self.grid_cell_size,
            self.grid_cell_offset,
            multiply_with_stride=False,
        )
        anchors = anchor_points.split(n_anchors_list, dim=0)
        keypoints = keypoints.view(batch_size, self.n_keypoints, 3, -1)
        grid_coords = (
            keypoints[:, :, :2] * 2.0 + (anchors[index].transpose(1, 0) - 0.5)
        ) * self.stride[index]

        conf_scores = keypoints[:, :, 2:3]

        if apply_sigmoid:
            conf_scores = conf_scores.sigmoid()

        return torch.cat((grid_coords, conf_scores), dim=2).view(
            batch_size, self.n_keypoints_flat, -1
        )

    def _split_keypoint_detections(
        self, detections: list[Tensor]
    ) -> tuple[list[Tensor], list[Tensor]]:
        """Split post-NMS detections into bboxes and keypoints."""
        bboxes = [detection[:, :6] for detection in detections]
        keypoints = [
            detection[:, 6:].reshape(-1, self.n_keypoints, 3)
            for detection in detections
        ]
        return bboxes, keypoints
