"""The FOMO head, which predicts a heatmap of object centers instead of
boxes.
"""

import torch
import torch.nn.functional as F
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.blocks.blocks import ConvBlock
from luxonis_train.nodes.heads import BaseHead
from luxonis_train.tasks import Task, Tasks
from luxonis_train.typing import Packet


class FOMOHead(BaseHead):
    r"""FOMO heatmap detection head.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, H_f, W_f\right]`

    Outputs:
        - train:

          - ``heatmap`` (``Tensor``): :math:`\left[B, n_{classes}, H_f,
            W_f\right]` logits

        - eval:

          - ``heatmap`` (``Tensor``): :math:`\left[B, n_{classes}, H_f,
            W_f\right]` logits
          - ``keypoints`` (``list[Tensor]``): :math:`\left[K_i, 1,
            4\right]` per image, ``(x, y, prob, class)``, pixels

        - export:

          - ``outputs`` (``list[Tensor]``): :math:`\left[B, n_{classes},
            H_f, W_f\right]`, max-pooled when ``use_nms``

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        The head runs a stack of ``1x1`` convolutions, so each heatmap
        cell sees only its own feature vector. In evaluation mode, the
        head keeps the cells with a probability above ``0.5`` as
        keypoints. When ``use_nms`` is ``True``, the head also applies a
        ``3x3`` max pooling. In evaluation mode, only the local maxima
        then become keypoints. In export mode, the pooled heatmap
        replaces the heatmap.

    Variants:
        None. Configure the node through ``params``.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: FOMOHead
              inputs: [EfficientRep]

    Compatible with:
        - Attach index: ``1``, output 1 of the input node
        - Required labels: ``boundingbox``
        - Used by: `FOMOModel`
        - Losses: `FOMOLocalizationLoss`
        - Metrics:

          - `ConfusionMatrix`
          - `ObjectKeypointSimilarity`

        - Visualizers:

          - `FOMOVisualizer`
          - `KeypointVisualizer`

    """

    task: Task = Tasks.FOMO
    attach_index: int = 1
    in_channels: int

    def __init__(
        self,
        n_conv_layers: int = 3,
        conv_channels: int = 16,
        use_nms: bool = True,
        **kwargs,
    ):
        """Initialize the stack of ``1x1`` convolutions.

        The stack has ``n_conv_layers - 1`` hidden `ConvBlock` layers
        with ``conv_channels`` output channels, a bias, ReLU, and no
        batch norm. The first hidden layer reads ``in_channels``
        channels. A last ``1x1`` convolution maps ``conv_channels``
        channels to ``n_classes`` channels. This last layer always
        expects ``conv_channels`` input channels. Thus, an
        ``n_conv_layers`` below ``2`` works only when the input has
        ``conv_channels`` channels.

        Args:
            n_conv_layers (int): Number of convolutions, the last one
                included. Defaults to ``3``.
            conv_channels (int): Number of channels of the hidden layers.
                Defaults to ``16``.
            use_nms (bool): Whether to apply a ``3x3`` max pooling with
                stride ``1``. In evaluation mode, only the local maxima
                of the heatmap then become keypoints. In export mode, the
                pooled heatmap replaces the heatmap. Defaults to
                ``True``.
            **kwargs (``Any``): Keyword arguments for `BaseNode`, such as
                ``n_classes`` and ``input_shapes``.

        """
        super().__init__(**kwargs)
        self.n_conv_layers = n_conv_layers
        self.conv_channels = conv_channels
        self.use_nms = use_nms

        current_channels = self.in_channels

        layers = []
        for _ in range(self.n_conv_layers - 1):
            layers.append(
                ConvBlock(
                    current_channels,
                    self.conv_channels,
                    kernel_size=1,
                    stride=1,
                    use_norm=False,
                    bias=True,
                )
            )
            current_channels = self.conv_channels
        layers.append(
            nn.Conv2d(
                self.conv_channels, self.n_classes, kernel_size=1, stride=1
            )
        )
        self.conv_layers = nn.Sequential(*layers)

    @property
    @override
    def n_keypoints(self) -> int:
        """The number of keypoints of each object, always ``1``.

        The head predicts one point for each object. It ignores the
        ``n_keypoints`` param and the dataset metadata.

        """
        return 1

    def forward(self, inputs: Tensor) -> Packet[Tensor]:
        """Predict the class heatmap and build the packet of the mode.

        Training mode has priority over export mode. The packet depends
        on the mode:

        - Training mode: ``"heatmap"`` holds the logits, of shape
          ``[B, n_classes, H, W]``.
        - Export mode: ``"outputs"`` holds a list with one tensor, the
          heatmap logits of shape ``[B, n_classes, H, W]``. When
          ``use_nms`` is ``True``, a ``3x3`` max pooling with stride
          ``1`` first replaces each cell with the maximum of its
          neighborhood.
        - Evaluation mode: ``"heatmap"``, and ``"keypoints"`` with a
          tensor of shape ``[K_i, 1, 4]`` for each image. The head
          applies a sigmoid and keeps the cells with a probability above
          ``0.5``. When ``use_nms`` is ``True``, a cell must also equal
          the maximum of its ``3x3`` neighborhood. Each of the ``K_i``
          keypoints holds ``[x, y, probability, class]``. ``x`` and ``y``
          are the top-left corner of the cell, in the pixels of the
          original input.

        Args:
            inputs (``Tensor``): Feature map of shape ``[B, C, H, W]``.
                By default, it is output ``1`` of the input node.

        Returns:
            ``Packet[Tensor]``: The packet of the current mode.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import FOMOHead
            >>> sizes = [Size([1, 8, 64, 64]), Size([1, 16, 32, 32])]
            >>> head = FOMOHead(
            ...     n_classes=2,
            ...     input_shapes=[{"features": sizes}],
            ...     original_in_shape=Size([3, 128, 128]),
            ... )
            >>> head.in_channels
            16
            >>> head(torch.zeros(1, 16, 32, 32))["heatmap"].shape
            torch.Size([1, 2, 32, 32])

            In evaluation mode, the packet also holds one keypoint
            tensor for each image:

            >>> out = head.eval()(torch.zeros(1, 16, 32, 32))
            >>> sorted(out)
            ['heatmap', 'keypoints']
            >>> len(out["keypoints"]), out["keypoints"][0].shape[1:]
            (1, torch.Size([1, 4]))

        """
        heatmap = self.conv_layers(inputs)

        if self.training:
            return {self.task.main_output: heatmap}

        if self.export:
            if self.use_nms:
                heatmap = F.max_pool2d(
                    heatmap, kernel_size=3, stride=1, padding=1
                )

            return {"outputs": [heatmap]}

        return {
            "keypoints": self._heatmap_to_kpts(heatmap),
            self.task.main_output: heatmap,
        }

    def _heatmap_to_kpts(self, heatmap: Tensor) -> list[Tensor]:
        """Convert the heatmap logits into the keypoints of each image.

        The method applies a sigmoid to each class map and keeps the
        cells that ``_get_keypoint_mask`` selects.

        Args:
            heatmap (``Tensor``): Logits of shape ``[B, n_classes, H, W]``.

        Returns:
            ``list[Tensor]``: One ``float32`` tensor of shape
            ``[K_i, 1, 4]`` for each image. Each of the ``K_i`` keypoints
            holds ``[x, y, probability, class]``. ``x`` and ``y`` are
            the top-left corner of the cell, in the pixels of the
            original input. The keypoints are in class order.

        """
        device = heatmap.device
        batch_size, n_classes, height, width = heatmap.shape

        batch_kpts = []
        for batch_idx in range(batch_size):
            kpts_per_img = []

            for class_id in range(n_classes):
                prob_map = torch.sigmoid(heatmap[batch_idx, class_id, :, :])

                keep = self._get_keypoint_mask(prob_map)

                y_indices, x_indices = torch.where(keep)
                kpts = [
                    [
                        x.item() / width * self.original_in_shape[2],
                        y.item() / height * self.original_in_shape[1],
                        float(prob_map[y, x]),
                        class_id,
                    ]
                    for y, x in zip(y_indices, x_indices, strict=True)
                ]

                kpts_per_img.extend(kpts)

            batch_kpt = torch.tensor(
                kpts_per_img, device=device, dtype=torch.float32
            ).unsqueeze(1)
            if batch_kpt.numel() == 0:
                batch_kpt = torch.zeros((0, 1, 4), device=device)
            batch_kpts.append(batch_kpt)

        return batch_kpts

    def _get_keypoint_mask(self, prob_map: Tensor) -> Tensor:
        """Select the keypoint cells of one class.

        Args:
            prob_map (``Tensor``): Probabilities of one class, of shape
                ``[H, W]``.

        Returns:
            ``Tensor``: Boolean mask of shape ``[H, W]``. A cell is
            ``True`` when its probability is above ``0.5``. When
            ``use_nms`` is ``True``, the cell must also equal the maximum
            of its ``3x3`` neighborhood.

        """
        if self.use_nms:
            pooled_map = (
                F.max_pool2d(
                    # Shape: `[1, 1, H, W]`
                    prob_map.unsqueeze(0).unsqueeze(0),
                    kernel_size=3,
                    stride=1,
                    padding=1,
                )
                .squeeze(0)
                .squeeze(0)
            )  # [H, W]
            threshold = 0.5
            return (prob_map == pooled_map) & (prob_map > threshold)

        return prob_map > 0.5
