"""The embedding head of GhostFaceNet."""

# Original source: https://github.com/Hazqeel09/ellzaf_ml/blob/main/ellzaf_ml/models/ghostfacenetsv2.py
import math

from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.blocks.blocks import ConvBlock
from luxonis_train.nodes.heads.base_head import BaseHead
from luxonis_train.tasks import Tasks


class GhostFaceNetHead(BaseHead):
    r"""GhostFaceNet embedding head.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, \lceil H/32
          \rceil, \lceil W/32 \rceil\right]`

    Outputs:
        - ``embeddings`` (``Tensor``): :math:`\left[B, D\right]`, where
          :math:`D` is ``embedding_size``

    References:
        - Source: Adapted from `Hazqeel09/ellzaf_ml
          <https://github.com/Hazqeel09/ellzaf_ml>`_ (MIT).
        - License: MIT

    Notes:
        :math:`H` and :math:`W` are the height and the width of the
        model input. The last output of the `GhostFaceNet` backbone has
        this size. The head applies these layers in order:

        - A depthwise `ConvBlock` with batch norm and no activation. Its
          kernel has the size of the input map, so the output is
          ``1x1``.
        - A dropout layer.
        - A ``1x1`` convolution without bias to :math:`D` channels.
        - A flatten step and a 1D batch norm.

        ``forward`` does not check the mode, so export mode also gives
        the embeddings. **The input map must have exactly the size
        above.** A map of another size makes a layer raise
        ``RuntimeError``. In training mode, a batch of one image makes
        the batch norm of the depthwise `ConvBlock` raise ``ValueError``.

    Variants:
        None. Configure the node through ``params``.

    See Also:
        - `The GhostFaceNetsV2 code in ellzaf_ml
          <https://github.com/Hazqeel09/ellzaf_ml/blob/main/ellzaf_ml/models/ghostfacenetsv2.py>`_
        - `GhostFaceNets: Lightweight Face Recognition Model From Cheap
          Operations
          <https://www.researchgate.net/publication/369930264_GhostFaceNets_Lightweight_Face_Recognition_Model_from_Cheap_Operations>`_

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: GhostFaceNetHead
              inputs: [GhostFaceNet]

    Compatible with:
        - Attach index: ``-1``, the last output of the input node
        - Required labels: ``metadata/id``
        - Used by: `EmbeddingsModel`
        - Losses:

          - ``AngularLoss``
          - ``CircleLoss``
          - ``ContrastiveLoss``
          - ``DynamicSoftMarginLoss``
          - ``FastAPLoss``
          - ``GeneralizedLiftedStructureLoss``
          - ``HistogramLoss``
          - ``InstanceLoss``
          - ``IntraPairVarianceLoss``
          - ``LiftedStructureLoss``
          - ``MarginLoss``
          - ``MultiSimilarityLoss``
          - ``NCALoss``
          - ``NPairsLoss``
          - ``NTXentLoss``
          - ``PNPLoss``
          - ``RankedListLoss``
          - ``SignalToNoiseRatioContrastiveLoss``
          - ``SupConLoss``
          - ``ThresholdConsistentMarginLoss``
          - ``TripletMarginLoss``
          - ``TupletMarginLoss``

        - Metrics:

          - `ClosestIsPositiveAccuracy`
          - `MedianDistances`

        - Visualizers: `EmbeddingsVisualizer`

    """

    in_channels: int
    in_width: int
    task = Tasks.EMBEDDINGS

    def __init__(
        self,
        embedding_size: int = 512,
        cross_batch_memory_size: int | None = None,
        dropout: float = 0.2,
        **kwargs,
    ):
        r"""Build the layers of the head.

        The constructor stores ``embedding_size`` and
        ``cross_batch_memory_size`` in attributes of the same names. The
        embedding losses read both attributes from the node. The
        embedding metrics read only ``cross_batch_memory_size``. The
        kernel of the depthwise convolution is
        :math:`\lceil H/32 \rceil \times \lceil W/32 \rceil`, with
        :math:`H` and :math:`W` from ``original_in_shape``.

        Args:
            embedding_size (int): The number of values in each embedding.
                It is the number of output channels of the ``1x1``
                convolution.
            cross_batch_memory_size (int | None): The maximum number of
                the newest embeddings that the embedding losses and
                metrics keep in memory across batches. ``None`` turns this
                memory off. A loss that ``CrossBatchMemory`` does not
                support logs a warning and ignores the value. The head
                itself does not read the value.
            dropout (float): The probability that the dropout layer sets
                a value to zero in training mode, in ``[0, 1]``.
            **kwargs (``Any``): Keyword arguments for `BaseNode`. They
                must hold ``original_in_shape``, and ``input_shapes`` or
                ``in_sizes``.

        """
        super().__init__(**kwargs)
        self.embedding_size = embedding_size
        self.cross_batch_memory_size = cross_batch_memory_size
        _, H, W = self.original_in_shape

        self.head = nn.Sequential(
            ConvBlock(
                self.in_channels,
                self.in_channels,
                kernel_size=(
                    H // 32 if H % 32 == 0 else H // 32 + 1,
                    W // 32 if W % 32 == 0 else W // 32 + 1,
                ),
                groups=self.in_channels,
                activation=False,
            ),
            nn.Dropout(dropout),
            nn.Conv2d(
                self.in_channels, embedding_size, kernel_size=1, bias=False
            ),
            nn.Flatten(),
            nn.BatchNorm1d(embedding_size),
        )

    def forward(self, x: Tensor) -> Tensor:
        r"""Compute the embeddings of a batch of feature maps.

        Args:
            x (``Tensor``): The last feature map of the backbone, of shape
                ``[B, C, ceil(H / 32), ceil(W / 32)]``. ``H`` and ``W``
                come from ``original_in_shape``.

        Returns:
            ``Tensor``: The embeddings of shape ``[B, embedding_size]``.
            `BaseNode.run` puts them under the ``"embeddings"`` key.

        Example:
            A model input of ``100x100`` pixels gives a ``4x4`` map,
            because :math:`\lceil 100/32 \rceil = 4`:

            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import GhostFaceNetHead
            >>> head = GhostFaceNetHead(
            ...     embedding_size=16,
            ...     input_shapes=[{"features": [Size([2, 8, 4, 4])]}],
            ...     original_in_shape=Size([3, 100, 100]),
            ... )
            >>> packet = head.run([{"features": [torch.zeros(2, 8, 4, 4)]}])
            >>> packet["embeddings"].shape
            torch.Size([2, 16])

        """
        return self.head(x)

    @override
    def initialize_weights(self, method: str | None = None) -> None:
        r"""Initialize the convolutions and the 2D batch norm layers.

        The method first calls `BaseNode.initialize_weights` with
        ``method``. Then it draws the weights of every `torch.nn.Conv2d`
        and `torch.nn.Linear` from a normal distribution with the mean
        ``0`` and this standard deviation:

        .. math::

            \sigma = \sqrt{\frac{2}{n_{in} \left(1 + a^2\right)}}

        :math:`n_{in}` is the fan-in of the layer, and :math:`a` is
        ``0.25``. This is the Kaiming normal initialization for a leaky
        ReLU with the slope ``0.25``. The biases do not change.

        Every `torch.nn.BatchNorm2d` then gets ``momentum=0.9`` and
        ``eps=1e-5``. The 1D batch norm keeps its defaults. PyTorch uses
        ``momentum`` as the weight of the new batch in the running
        statistics. With ``0.9``, these statistics thus follow the last
        batches closely.

        Args:
            method (str | None): The method for
                `BaseNode.initialize_weights`. The value has no effect on
                this head. The head has no activation that ``"yolo"``
                changes, and the method replaces the batch norm values of
                ``"yolo"``.

        Example:
            The node calls the method after construction:

            >>> from torch import Size
            >>> from luxonis_train.nodes import GhostFaceNetHead
            >>> head = GhostFaceNetHead(
            ...     input_shapes=[{"features": [Size([2, 8, 4, 4])]}],
            ...     original_in_shape=Size([3, 112, 112]),
            ...     weights="yolo",
            ... )
            >>> batch_norm = head.head[0].bn
            >>> batch_norm.momentum, batch_norm.eps
            (0.9, 1e-05)

        """
        super().initialize_weights(method)
        for m in self.modules():
            if isinstance(m, nn.Conv2d | nn.Linear):
                fan_in, _ = nn.init._calculate_fan_in_and_fan_out(m.weight)
                negative_slope = 0.25
                m.weight.data.normal_(
                    0, math.sqrt(2.0 / (fan_in * (1 + negative_slope**2)))
                )
            if isinstance(m, nn.BatchNorm2d):
                m.momentum = 0.9
                m.eps = 1e-5
