"""The OCR head that predicts the character class scores of each
sequence step for CTC.
"""

import math

from luxonis_ml.typing import Params
from torch import Tensor, nn
from torch.nn import functional as F
from typing_extensions import override

from luxonis_train.nodes.heads import BaseHead
from luxonis_train.tasks import Tasks
from luxonis_train.utils import OCRDecoder, OCREncoder


class OCRCTCHead(BaseHead):
    r"""OCR CTC sequence classification head.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, 1, T\right]`

    Outputs:
        - train, eval:

          - ``ocr`` (``Tensor``): :math:`\left[B, T, n_{classes}\right]`
            logits, class ``0`` is blank

        - export:

          - ``ocr`` (``Tensor``): :math:`\left[B, T, n_{classes}\right]`
            softmax probabilities

    References:
        - Source: Adapted from `PaddlePaddle/PaddleOCR
          <https://github.com/PaddlePaddle/PaddleOCR>`_ (Apache-2.0).
        - License: Apache-2.0

    Notes:
        The head removes the height axis of the feature map, so the
        height must be ``1``. Each of the :math:`T` columns becomes one
        step of the sequence. One linear layer maps each step to the
        class logits. With ``mid_channels``, two linear layers with a
        ReLU between them do this.

        The classes come from ``alphabet``, not from the dataset.
        :math:`n_{classes}` is `out_channels`. Class ``0`` is the CTC
        blank. The unique characters of ``alphabet`` follow in sorted
        order. With ``ignore_unknown=False``, the last class is
        ``"<UNK>"``. `CTCLoss` and `OCRAccuracy` encode the text labels
        with `encoder`. `OCRVisualizer` decodes the predictions with
        `decoder`.

    Variants:
        None. Configure the node through ``params``.

    See Also:
        - `The CTC head of PaddleOCR
          <https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/modeling/heads/rec_ctc_head.py>`_

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: OCRCTCHead
              inputs: [SVTRNeck]
              params:
                alphabet: ["a", "b", "c"]

    Compatible with:
        - Attach index: ``-1``, the last output of the input node
        - Required labels: ``metadata/text``
        - Used by: `OCRRecognitionModel`
        - Losses: `CTCLoss`
        - Metrics: `OCRAccuracy`
        - Visualizers: `OCRVisualizer`
        - Export parser: ``ClassificationSequenceParser``

    """

    in_channels: int
    task = Tasks.OCR

    parser: str = "ClassificationSequenceParser"

    def __init__(
        self,
        alphabet: list[str],
        ignore_unknown: bool = True,
        mid_channels: int | None = None,
        return_feats: bool = False,
        **kwargs,
    ):
        """Build the encoder, the decoder, and the linear layers.

        Args:
            alphabet (list[str]): The characters that the head predicts.
                The encoder sorts them and puts the blank class before
                them. Each character must occur only once.
            ignore_unknown (bool): Whether the encoder drops a label
                character that is not in ``alphabet``. With ``False``, the
                encoder maps the character to the extra class
                ``"<UNK>"``, so the head predicts one more class.
            mid_channels (int | None): The number of hidden features
                between two linear layers. ``None`` gives one linear layer
                from ``in_channels`` to `out_channels`.
            return_feats (bool): The head stores the value in the
                ``return_feats`` attribute. `forward` does not read it,
                so the value has no effect.
            **kwargs (``Any``): Keyword arguments for `BaseNode`. They
                must hold ``input_shapes`` or ``in_sizes``.

        Raises:
            ValueError: When ``alphabet`` holds a character more than
                once.

        """
        super().__init__(**kwargs)
        if len(set(alphabet)) != len(alphabet):  # pragma: no cover
            raise ValueError("Alphabet has duplicate characters.")

        self.return_feats = return_feats

        self._encoder = OCREncoder(alphabet, ignore_unknown)
        self._decoder = OCRDecoder(self._encoder.char_to_int)

        if mid_channels is None:
            self.block = nn.Linear(self.in_channels, self.out_channels)
        else:
            self.block = nn.Sequential(
                nn.Linear(self.in_channels, mid_channels),
                nn.ReLU(),
                nn.Linear(mid_channels, self.out_channels),
            )

    def forward(self, x: Tensor) -> Tensor:
        """Compute the class scores of each step of the sequence.

        The method removes the height axis and moves the width axis
        before the channel axis. Each column of the feature map is then
        one step. The linear layers map the ``C`` channels of each step
        to the class logits. In export mode, the method applies a softmax
        over the classes.

        Args:
            x (``Tensor``): The feature map of shape ``[B, C, 1, T]``. With
                a height other than ``1``, ``permute`` raises
                ``RuntimeError``.

        Returns:
            ``Tensor``: The logits of shape ``[B, T, out_channels]``. In
            export mode, the softmax probabilities of the same shape.
            `BaseNode.run` puts the result under the ``"ocr"`` key.

        Example:
            The alphabet ``["b", "a"]`` gives three classes: the blank,
            ``"a"``, and ``"b"``.

            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import OCRCTCHead
            >>> head = OCRCTCHead(
            ...     alphabet=["b", "a"],
            ...     input_shapes=[{"features": [Size([1, 8, 1, 4])]}],
            ... )
            >>> head(torch.zeros(1, 8, 1, 4)).shape
            torch.Size([1, 4, 3])
            >>> head.export = True
            >>> probabilities = head(torch.zeros(1, 8, 1, 4))
            >>> torch.allclose(probabilities.sum(dim=-1), torch.tensor(1.0))
            True

        """
        x = x.squeeze(2).permute(0, 2, 1)
        predictions = self.block(x)

        if self.export:
            predictions = F.softmax(predictions, dim=-1)

        return predictions

    @property
    def encoder(self) -> OCREncoder:
        """The encoder that converts text labels to class indices.

        `CTCLoss` and `OCRAccuracy` use it. Its alphabet starts with the
        blank ``""`` at index ``0``. The sorted unique characters of
        ``alphabet`` follow. With ``ignore_unknown=False``, ``"<UNK>"``
        is the last entry.

        """
        return self._encoder

    @property
    def decoder(self) -> OCRDecoder:
        """The decoder that converts the predictions to text.

        It applies a softmax and takes the most probable class at each
        step. It drops the blank class ``0`` and each class that repeats
        the class of the previous step. For each sequence, it returns
        the text and the mean probability of the kept characters. The
        mean is ``NaN`` for an empty text. `OCRVisualizer` and
        `BaseHead.annotate` use it.

        """
        return self._decoder

    @property
    @override
    def export_output_names(self) -> list[str]:
        """The name of the output in the exported model.

        The value is always ``["output_ocr_ctc"]``. The property ignores
        the ``export_output_names`` param.

        """
        return ["output_ocr_ctc"]

    @override
    def get_custom_head_config(self) -> Params:
        """Return the NN Archive metadata of the head.

        `BaseHead.get_head_config` merges the result into the metadata.
        The ``"classes"`` and ``"n_classes"`` keys of the result replace
        the values from the dataset. `BaseHead.get_head_config` still
        reads the class names of the dataset first, so it needs
        ``dataset_metadata``.

        Returns:
            ``Params``: A dictionary with these keys:

            - ``"classes"``: the alphabet of `encoder`, with the blank
              ``""`` first.
            - ``"n_classes"``: `out_channels`.
            - ``"is_softmax"``: ``True``, because the exported model
              applies a softmax.
            - ``"concatenate_classes"``: ``True``.
            - ``"ignored_indexes"``: ``[0]``, the index of the blank.
            - ``"remove_duplicates"``: ``True``.

        Example:
            >>> from torch import Size
            >>> from luxonis_train.nodes import OCRCTCHead
            >>> head = OCRCTCHead(
            ...     alphabet=["b", "a"],
            ...     ignore_unknown=False,
            ...     input_shapes=[{"features": [Size([1, 8, 1, 4])]}],
            ... )
            >>> config = head.get_custom_head_config()
            >>> [str(char) for char in config["classes"]]
            ['', 'a', 'b', '<UNK>']
            >>> config["n_classes"], config["ignored_indexes"]
            (4, [0])

        """
        return {
            "classes": self.encoder.alphabet,
            "n_classes": self.encoder.n_classes,
            "is_softmax": True,
            "concatenate_classes": True,
            "ignored_indexes": [0],
            "remove_duplicates": True,
        }

    @property
    def out_channels(self) -> int:
        """The number of classes that the head predicts.

        It is the length of the alphabet of `encoder`: the blank, the
        unique characters of ``alphabet``, and ``"<UNK>"`` when
        ``ignore_unknown`` is ``False``.

        """
        return self.encoder.n_classes

    @override
    def initialize_weights(self, method: str | None = None) -> None:
        r"""Initialize the linear layers.

        The method first calls `BaseNode.initialize_weights` with
        ``method``. Then it draws the weight and the bias of every
        `torch.nn.Linear` from the uniform distribution on
        :math:`\left[-1/\sqrt{n_{in}}, 1/\sqrt{n_{in}}\right]`.
        :math:`n_{in}` is the number of input features of the layer.
        These are the bounds of the PyTorch default initialization of
        `torch.nn.Linear`.

        Args:
            method (str | None): The method for
                `BaseNode.initialize_weights`. With ``mid_channels``,
                ``"yolo"`` makes the ReLU between the linear layers run in
                place. Other values change nothing there.

        """
        super().initialize_weights(method)
        for m in self.modules():
            if isinstance(m, nn.Linear):
                std = 1.0 / math.sqrt(m.in_features)
                nn.init.uniform_(m.weight, -std, std)
                nn.init.uniform_(m.bias, -std, std)
