"""The SVTR neck, which refines the feature map that the OCR head reads
as a sequence.
"""

from typing import Literal

import torch
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes import BaseNode
from luxonis_train.nodes.blocks import ConvBlock
from luxonis_train.nodes.necks.svtr_neck.blocks import SVTRBlock


class SVTRNeck(BaseNode):
    r"""SVTR neck.

    The neck refines the last feature map of an OCR backbone with SVTR
    transformer blocks. Each position of the map is one token.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, H, W\right]`

    Outputs:
        - ``features`` (``Tensor``): :math:`\left[B, D, H, W\right]`,
          where :math:`D` is ``dims``

    References:
        - Source: Adapted from `PaddlePaddle/PaddleOCR
          <https://github.com/PaddlePaddle/PaddleOCR>`_ (Apache-2.0).
          Paper: `SVTR: Scene Text Recognition with a Single Visual
          Model <https://arxiv.org/abs/2205.00159>`_.
        - License: Apache-2.0

    Notes:
        The neck runs these steps:

        1. Two `ConvBlock` layers map the :math:`C` channels to
           :math:`\lfloor C / 8 \rfloor` channels, and then to
           ``mid_channels``.
        2. The neck flattens the map into :math:`H \cdot W` tokens.
           ``depth`` `SVTRBlock` layers and a layer norm process them.
        3. The neck reshapes the tokens into a map. A ``1x1``
           `ConvBlock` maps it back to :math:`C` channels.
        4. The neck concatenates the input and this map. Two
           `ConvBlock` layers map the :math:`2C` channels to
           :math:`\lfloor C / 8 \rfloor` channels, and then to
           :math:`D`.

        Every `ConvBlock` has a bias, a batch norm, and ReLU. Both values
        of ``kernel_size`` must be the same odd number. Other values
        change the size of the map in step 1, and the concatenation in
        step 4 raises ``RuntimeError``. Thus the output has the height
        and the width of the input. The neck does not check the mode, so
        export mode gives the same output.

        `OCRCTCHead` needs a map of the height ``1``, so a neck in front
        of it needs an input of the height ``1``.

    Variants:
        None. Configure the node through ``params``.

    See Also:
        - `The SVTR neck of PaddleOCR
          <https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/modeling/necks/rnn.py>`_

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: SVTRNeck
              inputs: [PPLCNetV3]

    Compatible with:
        - Attach index: ``-1``, the last output of the input node
        - Used by: `OCRRecognitionModel`

    """

    in_channels: int

    def __init__(
        self,
        dims: int = 64,
        depth: int = 2,
        mid_channels: int = 120,
        use_guide: bool = False,
        n_heads: int = 8,
        mlp_ratio: float = 2.0,
        drop_rate: float = 0.1,
        attn_drop_rate: float = 0.1,
        drop_path: float = 0.0,
        kernel_size: tuple[int, int] = (3, 3),
        qk_scale: float | None = None,
        mixer: Literal["global", "local", "conv"] = "global",
        height: int | None = None,
        width: int | None = None,
        prenorm: bool = False,
        **kwargs,
    ):
        r"""Build the convolutions and the SVTR blocks.

        The constructor stores ``dims`` in ``out_channels``, and
        ``depth`` and ``use_guide`` in attributes of the same names.

        Args:
            dims (int): The number of output channels.
            depth (int): The number of `SVTRBlock` layers.
            mid_channels (int): The number of channels of each token. It
                must be a multiple of ``n_heads``.
            use_guide (bool): Whether the neck reads a detached copy of
                the input. With ``True``, no gradient flows from the neck
                back to the input node.
            n_heads (int): The number of attention heads of each block,
                or the number of convolution groups of the ``"conv"``
                mixer.
            mlp_ratio (float): The number of hidden features of each MLP,
                as a multiple of ``mid_channels``.
            drop_rate (float): The dropout probability of the dropout
                layers of the MLPs, and after the attention outputs.
            attn_drop_rate (float): The dropout probability of the
                attention weights.
            drop_path (float): The probability that `DropPath` drops a
                residual branch for a sample in training mode. ``0.0``
                turns it off.
            kernel_size (tuple[int, int]): The kernel of the two
                `ConvBlock` layers with :math:`\lfloor C / 8 \rfloor`
                output channels. The padding is ``kernel_size[0] // 2``
                on all sides. Use the same odd number twice. Other values
                change the size of the map, and the concatenation raises
                ``RuntimeError``. The blocks do not use this value.
            qk_scale (float | None): The scale of the attention queries.
                ``None`` or ``0`` gives :math:`1 / \sqrt{d}`, where
                :math:`d` is ``mid_channels // n_heads``.
            mixer (``Literal["global", "local", "conv"]``): The token
                mixer of every block. ``"global"`` attends to all tokens.
                ``"local"`` attends to a ``7x11`` window of tokens. Its
                mask stays on the CPU, so it works only for an input on
                the CPU. ``"conv"`` uses a grouped ``7x11`` convolution.
            height (int | None): The height of the input map. The
                ``"local"`` and ``"conv"`` mixers need it. Without it,
                the blocks raise ``ValueError``.
            width (int | None): The width of the input map. The
                ``"local"`` and ``"conv"`` mixers need it. Without it,
                the blocks raise ``ValueError``.
            prenorm (bool): The place of the norm layers in each block.
                ``False`` puts them before the branches. ``True`` puts
                them after the residual sums. See `SVTRBlock`.
            **kwargs (``Any``): Keyword arguments for `BaseNode`. They
                must hold ``input_shapes`` or ``in_sizes``.

        """
        super().__init__(**kwargs)
        self.depth = depth
        self.use_guide = use_guide
        self.conv1 = ConvBlock(
            self.in_channels,
            self.in_channels // 8,
            kernel_size=kernel_size,
            padding=kernel_size[0] // 2,
            bias=True,
            activation=nn.ReLU(),
        )
        self.conv2 = ConvBlock(
            self.in_channels // 8,
            mid_channels,
            kernel_size=1,
            bias=True,
            activation=nn.ReLU(),
        )

        self.svtr_block = nn.ModuleList(
            [
                SVTRBlock(
                    dim=mid_channels,
                    n_heads=n_heads,
                    mixer=mixer,
                    height=height,
                    width=width,
                    mlp_ratio=mlp_ratio,
                    qk_scale=qk_scale,
                    dropout=drop_rate,
                    act_layer=nn.ReLU,
                    attn_drop=attn_drop_rate,
                    drop_path=drop_path,
                    norm_layer=nn.LayerNorm,
                    epsilon=1e-05,
                    prenorm=prenorm,
                )
                for _ in range(depth)
            ]
        )
        self.norm = nn.LayerNorm(mid_channels, eps=1e-6)
        self.conv3 = ConvBlock(
            mid_channels,
            self.in_channels,
            kernel_size=1,
            bias=True,
            activation=nn.ReLU(),
        )
        self.conv4 = ConvBlock(
            2 * self.in_channels,
            self.in_channels // 8,
            kernel_size=kernel_size,
            padding=kernel_size[0] // 2,
            bias=True,
            activation=nn.ReLU(),
        )

        self.conv1x1 = ConvBlock(
            self.in_channels // 8,
            dims,
            kernel_size=1,
            bias=True,
            activation=nn.ReLU(),
        )
        self.out_channels = dims

    def forward(self, x: Tensor) -> Tensor:
        """Refine a feature map with the SVTR blocks.

        Args:
            x (``Tensor``): The feature map of shape
                ``[B, in_channels, H, W]``. With the ``"local"`` or
                ``"conv"`` mixer, ``H`` and ``W`` must be ``height`` and
                ``width``.

        Returns:
            ``Tensor``: The refined map of shape ``[B, dims, H, W]``.
            `BaseNode.run` puts it under the ``"features"`` key.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import SVTRNeck
            >>> neck = SVTRNeck(
            ...     dims=32,
            ...     input_shapes=[{"features": [Size([2, 64, 1, 16])]}],
            ... )
            >>> neck(torch.zeros(2, 64, 1, 16)).shape
            torch.Size([2, 32, 1, 16])

        """
        z = x.clone().detach() if self.use_guide else x
        h = z

        z = self.conv1(z)
        z = self.conv2(z)

        B, C, H, W = z.shape
        z = z.flatten(2).permute(0, 2, 1)
        for blk in self.svtr_block:
            z = blk(z)
        z = self.norm(z)

        z = z.reshape([B, H, W, C]).permute(0, 3, 1, 2)
        z = self.conv3(z)
        z = torch.cat((h, z), dim=1)
        return self.conv1x1(self.conv4(z))

    @override
    def initialize_weights(self, method: str | None = None) -> None:
        """Initialize the linear and the layer norm layers.

        The node calls the method after construction, unless ``weights``
        asks for a checkpoint. The method first calls
        `BaseNode.initialize_weights` with ``method``. Then it changes
        these layers:

        - Every `torch.nn.Linear` draws its weight from a normal
          distribution with the mean ``0`` and the standard deviation
          ``0.02``, truncated to ``[-2, 2]``. Its bias becomes ``0``.
        - Every `torch.nn.LayerNorm` gets the weight ``1`` and the bias
          ``0``.

        After the first step, the method does not change the
        convolutions and the batch norms.

        Args:
            method (str | None): The method for
                `BaseNode.initialize_weights`. ``"yolo"`` changes the
                batch norms and makes every ReLU run in place, also the
                ReLU layers of the MLPs. Other values change nothing
                there.

        """
        super().initialize_weights(method)
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.LayerNorm):
                nn.init.zeros_(m.bias)
                nn.init.ones_(m.weight)
