"""The YOLOv6 detection loss, and the varifocal loss it uses for
classification.
"""

from typing import Literal, cast

import torch
import torch.nn.functional as F
from loguru import logger
from torch import Tensor, amp, nn
from torchvision.ops import box_convert

from luxonis_train.assigners import ATSSAssigner, TaskAlignedAssigner
from luxonis_train.nodes import EfficientBBoxHead
from luxonis_train.tasks import Tasks
from luxonis_train.utils import (
    anchors_for_fpn_features,
    compute_iou_loss,
    dist2bbox,
)
from luxonis_train.utils.boundingbox import IoUType

from .base_loss import BaseLoss


class AdaptiveDetectionLoss(BaseLoss):
    r"""Bounding box loss of YOLOv6, with a warmup of the anchor assignment.

    Inputs:
        - ``features`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
          W_i\right]` per scale
        - ``class_scores`` (``Tensor``): :math:`\left[B, N,
          n_{classes}\right]` sigmoid scores
        - ``distributions`` (``Tensor``): :math:`\left[B, N, 4\right]`,
          ``(l, t, r, b)`` in stride units
        - ``target`` (``Tensor``): :math:`\left[M, 6\right]`, ``[batch,
          class, x, y, w, h]``, ``xywh`` normalized

    Outputs:
        - ``Tensor``: scalar total loss
        - ``dict[str, Tensor]``: sub-losses ``class`` and ``iou``,
          without the loss weights

    Formula:
        On each call, an assigner matches the :math:`N` anchors to the
        target boxes. `ATSSAssigner` runs while the epoch is lower than
        ``n_warmup_epochs``, and `TaskAlignedAssigner` runs after that.
        For each anchor :math:`a`, the assigner gives a class, a box, and
        a soft score :math:`q_{a,c}` for each class :math:`c`.
        :math:`S` is the sum of all :math:`q_{a,c}`:

        .. math::

            L = \frac{\lambda_{cls} L_{cls}
            + \lambda_{iou} \sum_{a \in P} \left( 1 - \text{IoU}_a \right)
            \sum_{c} q_{a,c}}{\max(S, 1)}

        :math:`L_{cls}` is the `VarifocalLoss`, summed over all anchors
        and classes. :math:`P` is the set of positive anchors, and
        :math:`\text{IoU}_a` is the ``iou_type`` overlap of the predicted
        and the assigned box of anchor :math:`a`. :math:`\lambda_{cls}`
        is ``class_loss_weight`` and :math:`\lambda_{iou}` is
        ``iou_loss_weight``. The IoU term is ``0`` when no anchor is
        positive.

    References:
        - Source: Reimplemented from `YOLOv6: A Single-Stage Object
          Detection Framework for Industrial Applications
          <https://arxiv.org/abs/2209.02976>`_ and `PP-YOLOE: An evolved
          version of YOLO <https://arxiv.org/abs/2203.16250>`_.
        - License: Apache-2.0 (this project)

    Notes:
        The first call builds the anchors, the anchor points, and the
        strides from the shapes of ``features``. The loss stores them as
        non-persistent buffers. All later calls use these buffers, even
        when the shapes of ``features`` change. The first call that uses
        `TaskAlignedAssigner` logs the change of the assigner, also when
        ``n_warmup_epochs`` is ``0``.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientBBoxHead
              inputs: [RepPANNeck]
              losses:
                - name: AdaptiveDetectionLoss

    Compatible with:
        - Used by: `DetectionModel`
        - Nodes: `EfficientBBoxHead`

    """

    supported_tasks = [Tasks.BOUNDINGBOX]

    node: EfficientBBoxHead

    anchors: Tensor
    anchor_points: Tensor
    n_anchors_list: list[int]
    stride_tensor: Tensor
    gt_bboxes_scale: Tensor
    anchor_points_strided: Tensor

    def __init__(
        self,
        n_warmup_epochs: int = 0,
        iou_type: IoUType = "giou",
        reduction: Literal["sum", "mean"] = "mean",
        class_loss_weight: float = 1.0,
        iou_loss_weight: float = 2.5,
        per_class_weights: list[float] | None = None,
        skip_stal: bool = False,
        **kwargs,
    ):
        r"""Initialize the loss, its two assigners, and `VarifocalLoss`.

        The method reads the strides, the grid cell size, the grid cell
        offset, the number of classes, and the input image size from the
        node. The loss therefore needs a node: without ``node``,
        `BaseAttachedModule.node` raises ``RuntimeError``. The code
        adapts `PPYOLOE_pytorch
        <https://github.com/Nioolek/PPYOLOE_pytorch/blob/master/ppyoloe/models>`_.

        Args:
            n_warmup_epochs (int): The number of epochs, counted from
                epoch ``0``, that use `ATSSAssigner` with ``topk=9``.
                The later epochs use `TaskAlignedAssigner` with
                ``topk=13``, ``alpha=1.0``, and ``beta=6.0``.
            iou_type (``IoUType``): The IoU variant of the box term:
                ``"none"`` for the plain IoU, ``"giou"``, ``"diou"``,
                ``"ciou"``, or ``"siou"``. `luxonis_train.utils.bbox_iou`
                describes the variants.
            reduction (``Literal["sum", "mean"]``): The loss does not
                read it. Both terms always use the normalized sum of the
                class formula.
            class_loss_weight (float): The factor :math:`\lambda_{cls}`
                of the classification term.
            iou_loss_weight (float): The factor :math:`\lambda_{iou}` of
                the box term.
            per_class_weights (list[float] | None): One factor for each
                class. `VarifocalLoss` multiplies the weight of each
                class by its factor. A list with a length other than the
                number of classes logs a warning, and the loss then uses
                no factors. ``None`` uses no factors.
            skip_stal (bool): ``True`` turns off the Small-Target-Aware
                Label Assignment of `TaskAlignedAssigner`.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseLoss`, such as ``final_loss_weight`` and ``node``.

        """
        super().__init__(**kwargs)

        self._iou_type: IoUType = iou_type
        self._reduction = reduction
        self._stride = self.node.stride
        self._grid_cell_size = self.node.grid_cell_size
        self._grid_cell_offset = self.node.grid_cell_offset
        self._original_img_size = self.original_in_shape[1:]

        self._n_warmup_epochs = n_warmup_epochs
        self.atss_assigner = ATSSAssigner(topk=9, n_classes=self.n_classes)
        self.tal_assigner = TaskAlignedAssigner(
            topk=13,
            n_classes=self.n_classes,
            alpha=1.0,
            beta=6.0,
            strides=self._stride,
            skip_stal=skip_stal,
        )

        if per_class_weights is not None:
            if len(per_class_weights) == self.n_classes:
                self._per_class_weights = torch.tensor(per_class_weights)
            else:
                logger.warning(
                    f"Incorrect per_class_weights length. "
                    f"Expected {self.n_classes} but got "
                    f"{len(per_class_weights)}. Setting to None."
                )
                self._per_class_weights = None
        else:
            self._per_class_weights = None

        self.varifocal_loss = VarifocalLoss(
            per_class_weights=self._per_class_weights
        )
        self._class_loss_weight = class_loss_weight
        self._iou_loss_weight = iou_loss_weight

        self.register_buffer(
            "gt_bboxes_scale",
            torch.tensor(
                [
                    self._original_img_size[1],
                    self._original_img_size[0],
                    self._original_img_size[1],
                    self._original_img_size[0],
                ],
            ),
            persistent=False,
        )

        self._logged_assigner_change = False

    def forward(
        self,
        features: list[Tensor],
        class_scores: Tensor,
        distributions: Tensor,
        target: Tensor,
    ) -> tuple[Tensor, dict[str, Tensor]]:
        """Assign the anchors to the target boxes and compute the loss.

        The method converts ``target`` to ``xyxy`` boxes in pixels of
        the input image. It pads the boxes of each image to the largest
        number of boxes in one image. It decodes ``distributions`` to
        predicted boxes around the anchor points. The assigner of the
        current epoch then matches the anchors to the target boxes, and
        the method computes the two terms of the class formula.

        Args:
            features (``list[Tensor]``): The feature maps of the head,
                one of shape ``[B, C_i, H_i, W_i]`` for each scale. Only
                the first call uses them, to build the anchors.
            class_scores (``Tensor``): Sigmoid class scores of shape
                ``[B, N, n_classes]``, for the ``N`` anchors of all
                scales.
            distributions (``Tensor``): The distances from each anchor
                point to the left, top, right, and bottom side of its
                box, of shape ``[B, N, 4]``, in stride units.
            target (``Tensor``): The ``boundingbox`` label of shape
                ``[M, 6]``. Each row holds the batch index, the class,
                and the normalized ``x``, ``y``, ``w``, and ``h`` of one
                box. ``x`` and ``y`` give the top-left corner.

        Returns:
            ``tuple[Tensor, dict[str, Tensor]]``: The total loss as a
            scalar, and the sub-losses ``"class"`` and ``"iou"``. The
            sub-losses are the detached terms without the factors
            ``class_loss_weight`` and ``iou_loss_weight``.

        """
        batch_size = class_scores.shape[0]

        self._init_parameters(features)

        target = self._preprocess_bbox_target(target, batch_size)
        pred_bboxes = dist2bbox(distributions, self.anchor_points_strided)

        gt_labels = target[:, :, :1]
        gt_xyxy = target[:, :, 1:]
        mask_gt = (gt_xyxy.sum(-1, keepdim=True) > 0).float()

        (
            assigned_labels,
            assigned_bboxes,
            assigned_scores,
            mask_positive,
            _,
        ) = self._run_assigner(
            gt_labels, gt_xyxy, mask_gt, pred_bboxes, class_scores
        )

        assigned_bboxes /= self.stride_tensor

        one_hot_label = F.one_hot(assigned_labels.long(), self.n_classes + 1)[
            ..., :-1
        ]
        loss_cls = self.varifocal_loss(
            class_scores, assigned_scores, one_hot_label
        )

        if assigned_scores.sum() > 1:
            loss_cls /= assigned_scores.sum()

        loss_iou = compute_iou_loss(
            pred_bboxes,
            assigned_bboxes,
            assigned_scores,
            mask_positive,
            reduction="sum",
            iou_type=self._iou_type,
            bbox_format="xyxy",
        )[0]

        loss = (
            self._class_loss_weight * loss_cls
            + self._iou_loss_weight * loss_iou
        )

        sub_losses = {"class": loss_cls.detach(), "iou": loss_iou.detach()}

        return loss, sub_losses

    def _init_parameters(self, features: list[Tensor]) -> None:
        if not hasattr(self, "anchors"):
            (
                anchors,
                anchor_points,
                n_anchors_list,
                stride_tensor,
            ) = anchors_for_fpn_features(
                features,
                self._stride,
                self._grid_cell_size,
                self._grid_cell_offset,
                multiply_with_stride=True,
            )
            self.register_buffer("anchors", anchors, persistent=False)
            self.register_buffer(
                "anchor_points", anchor_points, persistent=False
            )
            self.register_buffer(
                "n_anchors_list",
                torch.tensor(n_anchors_list),
                persistent=False,
            )
            self.register_buffer(
                "stride_tensor", stride_tensor, persistent=False
            )
            self.register_buffer(
                "anchor_points_strided",
                anchor_points / stride_tensor,
                persistent=False,
            )

    def _run_assigner(
        self,
        gt_labels: Tensor,
        gt_xyxy: Tensor,
        mask_gt: Tensor,
        pred_bboxes: Tensor,
        pred_scores: Tensor,
        pred_kpts: Tensor | None = None,
        gt_kpts: Tensor | None = None,
        sigmas: Tensor | None = None,
        area_factor: float | None = None,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor, Tensor]:
        if self.current_epoch < self._n_warmup_epochs:
            return self.atss_assigner(
                self.anchors,
                self.n_anchors_list,
                gt_labels,
                gt_xyxy,
                mask_gt,
                pred_bboxes.detach() * self.stride_tensor,
            )
        self._log_assigner_change()
        return self.tal_assigner(
            pred_scores.detach(),
            pred_bboxes.detach() * self.stride_tensor,
            self.anchor_points,
            gt_labels,
            gt_xyxy,
            mask_gt,
            pred_kpts,
            gt_kpts,
            sigmas,
            area_factor,
        )

    def _preprocess_bbox_target(
        self, target: Tensor, batch_size: int
    ) -> Tensor:
        """Convert the flat box label to padded boxes for each image.

        Args:
            target (``Tensor``): The ``boundingbox`` label of shape
                ``[M, 6]``, as `forward` describes it.
            batch_size (int): The number of images ``B``.

        Returns:
            ``Tensor``: Boxes of shape ``[B, K, 5]``. ``K`` is the
            largest number of boxes in one image, or ``0`` for a batch
            without boxes. Each row holds the class and the ``xyxy`` box
            in pixels of the input image. A padding row has the class
            ``-1`` and a zero box.

        """
        sample_ids, counts = cast(
            tuple[Tensor, Tensor],
            torch.unique(target[:, 0].int(), return_counts=True),
        )
        c_max = int(counts.max()) if counts.numel() > 0 else 0
        out_target = torch.zeros(batch_size, c_max, 5, device=target.device)
        out_target[:, :, 0] = -1
        for id, count in zip(sample_ids, counts, strict=True):
            out_target[id, :count] = target[target[:, 0] == id][:, 1:]

        scaled_target = out_target[:, :, 1:5] * self.gt_bboxes_scale
        out_target[..., 1:] = box_convert(scaled_target, "xywh", "xyxy")
        return out_target

    def _log_assigner_change(self) -> None:
        if self._logged_assigner_change:
            return

        logger.info(
            f"Switching to Task Aligned Assigner after {self._n_warmup_epochs} warmup epochs.",
            stacklevel=2,
        )
        self._logged_assigner_change = True


class VarifocalLoss(nn.Module):
    r"""Varifocal loss, which trains IoU-aware class scores.

    The loss trains the predicted class score to match a soft target
    score, such as the IoU between the predicted box and the assigned
    box. It weights the binary cross entropy between the predicted score
    :math:`p` and the target score :math:`q` of each anchor and class.
    With the one-hot label :math:`y`:

    .. math::

        L = \sum w \cdot \text{BCE}(p, q), \qquad
        w = \alpha \, p^{\gamma} \, (1 - y) + q \, y

    A negative element gets the focal weight :math:`\alpha p^{\gamma}`,
    and a positive element gets the weight :math:`q`. With
    ``per_class_weights``, the loss also multiplies the weight of each
    class by the factor of that class. The loss does not detach
    :math:`w`, so the gradient also flows through :math:`p^{\gamma}`.
    `AdaptiveDetectionLoss` uses this loss for its classification term.

    References:
        - `VarifocalNet: An IoU-aware Dense Object Detector
          <https://arxiv.org/abs/2008.13367>`_
        - The implementation adapts the code of `PPYOLOE_pytorch
          <https://github.com/Nioolek/PPYOLOE_pytorch/blob/master/ppyoloe/models/losses.py>`_.

    Example:
        The example has one anchor with two classes. The first class is
        positive with the target score ``0.8``. The binary cross entropy
        of both elements is :math:`\ln 2`, and the weights are ``0.8``
        and :math:`0.75 \cdot 0.5^2 = 0.1875`:

        >>> import torch
        >>> loss = VarifocalLoss()
        >>> pred_score = torch.tensor([[[0.5, 0.5]]])
        >>> target_score = torch.tensor([[[0.8, 0.0]]])
        >>> label = torch.tensor([[[1.0, 0.0]]])
        >>> round(loss(pred_score, target_score, label).item(), 4)
        0.6845

    """

    def __init__(
        self,
        alpha: float = 0.75,
        gamma: float = 2.0,
        per_class_weights: Tensor | None = None,
    ):
        r"""Initialize the varifocal loss.

        Args:
            alpha (float): The factor :math:`\alpha` of the weight of a
                negative element.
            gamma (float): The exponent :math:`\gamma` of the predicted
                score in the weight of a negative element.
            per_class_weights (``Tensor | None``): One factor for each
                class, of shape ``[n_classes]``. ``None`` uses no
                factors.

        """
        super().__init__()

        self._alpha = alpha
        self._gamma = gamma
        self._per_class_weights = per_class_weights

    def forward(
        self, pred_score: Tensor, target_score: Tensor, label: Tensor
    ) -> Tensor:
        """Compute the varifocal loss, summed over all elements.

        The binary cross entropy runs in ``float32``, with autocast off.
        When ``per_class_weights`` and ``pred_score`` are on different
        devices, the method replaces ``per_class_weights`` with a copy
        on the device of ``pred_score``.

        Args:
            pred_score (``Tensor``): Predicted class scores in
                ``[0, 1]``, of shape ``[B, N, n_classes]``.
            target_score (``Tensor``): Target scores in ``[0, 1]``, of
                the same shape. An assigner gives a soft score to the
                assigned class, and ``0`` to the other classes.
            label (``Tensor``): One-hot labels of the same shape. A
                background anchor has only zeros.

        Returns:
            ``Tensor``: The loss summed over all elements, as a scalar.

        """
        weight = (
            self._alpha * pred_score.pow(self._gamma) * (1 - label)
            + target_score * label
        )

        if self._per_class_weights is not None:
            if (
                self._per_class_weights.device != pred_score.device
            ):  # pragma: no cover
                self._per_class_weights = self._per_class_weights.to(
                    pred_score.device
                )
            # the shape [1, 1, n_classes] broadcasts over batches and anchors
            weight = weight * self._per_class_weights.view(1, 1, -1)

        with amp.autocast(device_type=pred_score.device.type, enabled=False):
            ce_loss = F.binary_cross_entropy(
                pred_score.float(), target_score.float(), reduction="none"
            )
        return (ce_loss * weight).sum()
