"""Cross entropy over raw logits."""

from typing import Literal

import torch
from loguru import logger
from torch import Tensor, nn

from luxonis_train.tasks import Tasks

from .base_loss import BaseLoss


class CrossEntropyLoss(BaseLoss):
    """Compute cross entropy between logits and class targets.

    Inputs:
        - ``predictions`` (``Tensor``): ``[B, C, ...]`` logits
        - ``target`` (``Tensor``): ``[B, C, ...]`` one-hot or ``[B,
          ...]`` indices

    Outputs:
        - ``Tensor``: scalar, or ``[B, ...]`` when unreduced

    Formula:
        Applies PyTorch ``nn.CrossEntropyLoss`` after target normalization.

    References:
        - Source: Wraps `torch.nn.CrossEntropyLoss
          <https://docs.pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html>`_
          (BSD-3-Clause).
        - License: Apache-2.0 (this project)

    Notes:
        Handles one-hot targets and logs a warning once when one-channel
        logits are adapted for cross entropy.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``DDRNetSegmentationHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: DDRNetSegmentationHead
              inputs: [DDRNet]
              losses:
                - name: CrossEntropyLoss

    Compatible with:
        - Used by: ``ClassificationModel``
        - Nodes: ``BiSeNetHead``, ``ClassificationHead``,
          ``DDRNetSegmentationHead``, ``SegmentationHead``,
          ``TransformerClassificationHead``, ``TransformerSegmentationHead``

    """

    supported_tasks = [Tasks.SEGMENTATION, Tasks.CLASSIFICATION]

    def __init__(
        self,
        weight: list[float] | None = None,
        ignore_index: int = -100,
        reduction: Literal["none", "mean", "sum"] = "mean",
        label_smoothing: float = 0.0,
        **kwargs,
    ):
        """Set up the cross entropy criterion.

        Args:
            weight (list[float] | None): A rescaling weight for each
                class. Give one value for each class, or leave it out to
                weight them equally.
            ignore_index (int): A target value the loss skips. It does
                not contribute to the gradient.
            reduction (``Literal["none", "mean", "sum"]``): How to reduce
                the loss over the batch.
            label_smoothing (float): How much of the target mass to
                spread over the other classes, between 0 and 1. It mixes
                the label with a uniform distribution, as in `Rethinking
                the Inception Architecture for Computer Vision
                <https://arxiv.org/abs/1512.00567>`_.
            **kwargs (``Any``): Keyword arguments forwarded to `BaseLoss`.

        """
        super().__init__(**kwargs)

        self.criterion = nn.CrossEntropyLoss(
            weight=(torch.tensor(weight) if weight is not None else None),
            ignore_index=ignore_index,
            reduction=reduction,
            label_smoothing=label_smoothing,
        )
        self._was_logged = False

    def forward(self, predictions: Tensor, target: Tensor) -> Tensor:
        if predictions.ndim == target.ndim:
            ch_dim = 1 if predictions.ndim > 1 else 0
            if predictions.shape[ch_dim] == 1:
                if not self._was_logged:
                    logger.warning(
                        "`CrossEntropyLoss` expects at least 2 classes. "
                        "Attempting to fix by adding a dummy channel. "
                        "If you want to be sure, use `BCEWithLogitsLoss` instead."
                    )
                    self._was_logged = True
                predictions = torch.cat(
                    [torch.zeros_like(predictions), predictions], dim=ch_dim
                )
                if target.shape[ch_dim] == 1:
                    target = torch.cat([1 - target, target], dim=ch_dim)
            target = target.argmax(dim=ch_dim)

        if target.ndim != predictions.ndim - 1:
            raise RuntimeError(
                f"Target tensor dimension should be equal to preds dimension - 1 ({predictions.ndim - 1}) "
                f"but is ({target.ndim})."
            )
        return self.criterion(predictions, target)
