"""The class, box, and keypoint loss of `EfficientKeypointBBoxHead`."""

from typing import Literal

import torch
import torch.nn.functional as F
from loguru import logger
from torch import Tensor

from luxonis_train.attached_modules.losses import AdaptiveDetectionLoss
from luxonis_train.nodes import EfficientKeypointBBoxHead
from luxonis_train.tasks import Tasks
from luxonis_train.utils import (
    compute_iou_loss,
    dist2bbox,
    get_sigmas,
    get_with_default,
)
from luxonis_train.utils.boundingbox import IoUType
from luxonis_train.utils.keypoints import insert_class


class EfficientKeypointBBoxLoss(AdaptiveDetectionLoss):
    r"""Class, box, and keypoint loss of `EfficientKeypointBBoxHead`.

    Inputs:
        - ``features`` (``list[Tensor]``): :math:`\left[B, C_i, H_i,
          W_i\right]` per scale
        - ``class_scores`` (``Tensor``): :math:`\left[B, N,
          n_{classes}\right]` sigmoid scores
        - ``distributions`` (``Tensor``): :math:`\left[B, N, 4\right]`,
          ``(l, t, r, b)`` in stride units
        - ``keypoints_raw`` (``Tensor``): :math:`\left[B, N, 3 *
          n_{keypoints}\right]`, raw ``(x, y, v)`` of each keypoint
        - ``target_boundingbox`` (``Tensor``): :math:`\left[M,
          6\right]`, ``[batch, class, x, y, w, h]``, ``xywh`` normalized
        - ``target_keypoints`` (``Tensor``): :math:`\left[M, 1 + 3 *
          n_{keypoints}\right]`, ``[batch, x, y, v, ...]``, ``x`` and
          ``y`` normalized

    Outputs:
        - ``Tensor``: scalar total loss
        - ``dict[str, Tensor]``: sub-losses ``class``, ``iou``,
          ``regression``, and ``visibility``, without the loss weights

    Formula:
        The class term :math:`L_{cls}` and the box term :math:`L_{iou}`
        are the two terms of `AdaptiveDetectionLoss`, each divided by
        :math:`\max(S, 1)`. :math:`S` is the sum of the assigned scores.
        After the warmup, `TaskAlignedAssigner` also reads the
        keypoints. It multiplies its IoU by the object keypoint
        similarity. The warmup `ATSSAssigner` ignores the keypoints.

        The keypoint terms read only the set :math:`P` of positive
        anchors. For anchor :math:`a` and keypoint :math:`i`, the
        predicted position :math:`(\hat{x}_{a,i}, \hat{y}_{a,i})` comes
        from `dist2kpts_noscale`. The target position
        :math:`(x_{a,i}, y_{a,i})` is the keypoint of the assigned
        instance, divided by the stride of the anchor. Both positions
        are in grid units. :math:`v_{a,i}` is ``1`` when the target
        visibility is above ``0``, else ``0``:

        .. math::

            L_{kpt} = \frac{1}{|P|} \sum_{a \in P}
            \frac{\sum_i v_{a,i} \left(1 - \exp(-d_{a,i})\right)}
            {\sum_i v_{a,i}},
            \qquad
            d_{a,i} = \frac{(\hat{x}_{a,i} - x_{a,i})^2
            + (\hat{y}_{a,i} - y_{a,i})^2}{2 \, (2 \sigma_i)^2 \, A_a}

        :math:`\sigma_i` is the sigma of keypoint :math:`i`, and
        :math:`A_a` is the area of the assigned box in grid units times
        ``area_factor``. The code adds ``1e-9`` to :math:`A_a` and to
        :math:`\sum_i v_{a,i}` to prevent a division by zero. The
        visibility term :math:`L_{vis}` is the mean binary cross entropy
        with logits between the raw visibility :math:`\hat{v}_{a,i}` and
        :math:`v_{a,i}`, over all keypoints of all positive anchors.
        ``viz_pw`` is the weight of its positive part. The total loss
        is:

        .. math::

            L = \lambda_{cls} L_{cls} + \lambda_{iou} L_{iou}
            + \lambda_{kpt} L_{kpt} + \lambda_{vis} L_{vis}

        :math:`\lambda_{cls}`, :math:`\lambda_{iou}`,
        :math:`\lambda_{kpt}`, and :math:`\lambda_{vis}` are
        ``class_loss_weight``, ``iou_loss_weight``,
        ``regr_kpts_loss_weight``, and ``vis_kpts_loss_weight``.

    References:
        - Source: Reimplemented from `YOLOv6: A Single-Stage Object
          Detection Framework for Industrial Applications
          <https://arxiv.org/abs/2209.02976>`_ and `PP-YOLOE: An evolved
          version of YOLO <https://arxiv.org/abs/2203.16250>`_.
        - License: Apache-2.0 (this project)

    Notes:
        The loss extends `AdaptiveDetectionLoss`. The first call builds
        the anchors, as in that class. A batch without positive anchors,
        such as a batch without instances, makes both keypoint terms
        and the total loss ``nan``. For a batch without instances, the
        loss also logs a debug message.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientKeypointBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientKeypointBBoxHead
              inputs: [RepPANNeck]
              losses:
                - name: EfficientKeypointBBoxLoss

    Compatible with:
        - Used by: `KeypointDetectionModel`
        - Nodes: `EfficientKeypointBBoxHead`

    """

    node: EfficientKeypointBBoxHead
    supported_tasks = [Tasks.INSTANCE_KEYPOINTS]

    gt_kpts_scale: Tensor

    def __init__(
        self,
        n_warmup_epochs: int = 0,
        iou_type: IoUType = "giou",
        reduction: Literal["sum", "mean"] = "mean",
        class_loss_weight: float = 0.5,
        iou_loss_weight: float = 7.5,
        viz_pw: float = 1.0,
        regr_kpts_loss_weight: float = 12,
        vis_kpts_loss_weight: float = 1.0,
        sigmas: list[float] | None = None,
        area_factor: float | None = None,
        **kwargs,
    ):
        r"""Initialize the box loss and the keypoint parameters.

        `AdaptiveDetectionLoss` builds the assigners and `VarifocalLoss`.
        The loss reads the strides, the grid cell size, and the grid cell
        offset from the node. It also reads the number of classes, the
        number of keypoints, and the input image size. The loss therefore
        needs a node: without ``node``, `BaseAttachedModule.node` raises
        ``RuntimeError``. The code of the box term adapts `PPYOLOE_pytorch
        <https://github.com/Nioolek/PPYOLOE_pytorch/blob/master/ppyoloe/models>`_.

        Args:
            n_warmup_epochs (int): The number of epochs, counted from
                epoch ``0``, that use `ATSSAssigner`. The later epochs
                use `TaskAlignedAssigner`, which also reads the
                keypoints.
            iou_type (``IoUType``): The IoU variant of the box term:
                ``"none"`` for the plain IoU, ``"giou"``, ``"diou"``,
                ``"ciou"``, or ``"siou"``.
            reduction (``Literal["sum", "mean"]``): The method stores
                it as ``self.reduction``. The loss does not read it.
            class_loss_weight (float): The factor :math:`\lambda_{cls}`
                of the class term.
            iou_loss_weight (float): The factor :math:`\lambda_{iou}` of
                the box term.
            viz_pw (float): The weight of the positive part of the
                binary cross entropy in the visibility term.
            regr_kpts_loss_weight (float): The factor
                :math:`\lambda_{kpt}` of the keypoint regression term.
            vis_kpts_loss_weight (float): The factor
                :math:`\lambda_{vis}` of the visibility term.
            sigmas (list[float] | None): One sigma for each keypoint.
                ``None`` selects the COCO person sigmas for ``17``
                keypoints, and ``0.04`` for each keypoint otherwise.
                `get_sigmas` logs the choice. A list with a length other
                than the number of keypoints raises ``ValueError``.
            area_factor (float | None): The factor that scales the area
                of a box to the pose area, in the keypoint regression
                term and in `TaskAlignedAssigner`. ``None`` uses
                ``0.53`` and logs an info message.
            **kwargs (``Any``): Keyword arguments forwarded to
                `AdaptiveDetectionLoss`, such as ``per_class_weights``,
                ``skip_stal``, ``final_loss_weight``, and ``node``.

        """
        super().__init__(
            n_warmup_epochs=n_warmup_epochs,
            iou_type=iou_type,
            reduction=reduction,
            class_loss_weight=class_loss_weight,
            iou_loss_weight=iou_loss_weight,
            **kwargs,
        )

        self.pos_weight = torch.tensor([viz_pw])
        self.sigmas = get_sigmas(
            sigmas=sigmas, n_keypoints=self.n_keypoints, caller_name=self.name
        )
        self.area_factor = get_with_default(
            area_factor, "bbox area scaling", self.name, default=0.53
        )
        self.regr_kpts_loss_weight = regr_kpts_loss_weight
        self.vis_kpts_loss_weight = vis_kpts_loss_weight
        self.register_buffer(
            "gt_kpts_scale",
            torch.tensor(
                [self.original_img_size[1], self.original_img_size[0]],
            ),
            persistent=False,
        )

    def forward(
        self,
        features: list[Tensor],
        class_scores: Tensor,
        distributions: Tensor,
        keypoints_raw: Tensor,
        target_boundingbox: Tensor,
        target_keypoints: Tensor,
    ) -> tuple[Tensor, dict[str, Tensor]]:
        """Assign the anchors to the instances and compute the loss.

        The method inserts the class of each box into its keypoints. It
        decodes ``distributions`` to ``xyxy`` boxes and
        ``keypoints_raw`` to keypoints, both in grid units around the
        anchor points. It converts the targets to padded tensors for
        each image, in pixels of the input image. The assigner of the
        current epoch then matches the anchors to the target boxes.
        `TaskAlignedAssigner` also compares the keypoints in pixels. The
        method then computes the four terms of the class formula. For a
        batch without instances, the method logs a debug message.

        Args:
            features (``list[Tensor]``): The feature maps of the head,
                one of shape ``[B, C_i, H_i, W_i]`` for each scale. Only
                the first call uses them, to build the anchors.
            class_scores (``Tensor``): Sigmoid class scores of shape
                ``[B, N, n_classes]``, for the ``N`` anchors of all
                scales.
            distributions (``Tensor``): The distances from each anchor
                point to the left, top, right, and bottom side of its
                box, of shape ``[B, N, 4]``, in stride units.
            keypoints_raw (``Tensor``): The raw keypoint values of shape
                ``[B, N, 3 * n_keypoints]``. Each keypoint has the raw
                ``x`` and ``y`` offsets and a visibility logit.
            target_boundingbox (``Tensor``): The ``boundingbox`` label of
                shape ``[M, 6]``. Each row holds the batch index, the
                class, and the normalized ``x``, ``y``, ``w``, and ``h``
                of one box. ``x`` and ``y`` give the top-left corner.
            target_keypoints (``Tensor``): The ``keypoints`` label of
                shape ``[M, 1 + 3 * n_keypoints]``, with the rows in the
                order of ``target_boundingbox``. Each row holds the batch
                index, then the normalized ``x`` and ``y`` and the
                visibility of each keypoint.

        Returns:
            ``tuple[Tensor, dict[str, Tensor]]``: The total loss as a
            scalar, and the sub-losses ``"class"``, ``"iou"``,
            ``"regression"``, and ``"visibility"``. The sub-losses are
            the detached terms without their factors. When no anchor is
            positive, the total loss and the two keypoint sub-losses are
            ``nan``.

        """
        self._init_parameters(features)

        device = keypoints_raw.device
        target_keypoints = insert_class(target_keypoints, target_boundingbox)

        batch_size = class_scores.shape[0]
        n_kpts = (target_keypoints.shape[1] - 2) // 3

        pred_bboxes = dist2bbox(distributions, self.anchor_points_strided)
        keypoints_raw = self.dist2kpts_noscale(
            self.anchor_points_strided,
            keypoints_raw.view(batch_size, -1, n_kpts, 3),
        )

        target_boundingbox = self._preprocess_bbox_target(
            target_boundingbox, batch_size
        )

        gt_bbox_labels = target_boundingbox[..., :1]
        gt_xyxy = target_boundingbox[..., 1:]
        mask_gt = (gt_xyxy.sum(-1, keepdim=True) > 0).float()

        batched_kpts = self._preprocess_kpts_target(
            target_keypoints, batch_size, self.gt_kpts_scale
        )

        scaled_raw_keypoints = keypoints_raw.clone()
        scaled_raw_keypoints[..., :2] = scaled_raw_keypoints[
            ..., :2
        ] * self.stride_tensor.clone().view(1, -1, 1, 1)

        sigmas = self.sigmas.to(device)

        (
            assigned_labels,
            assigned_bboxes,
            assigned_scores,
            mask_positive,
            assigned_gt_idx,
        ) = self._run_assigner(
            gt_bbox_labels,
            gt_xyxy,
            mask_gt,
            pred_bboxes,
            class_scores,
            scaled_raw_keypoints,
            batched_kpts,
            sigmas,
            self.area_factor,
        )

        assigned_gt_idx_expanded = assigned_gt_idx.unsqueeze(-1).unsqueeze(-1)
        if batched_kpts.numel() == 0:
            logger.debug("No instances found in the batch")
            selected_keypoints = batched_kpts.new_zeros(
                (
                    batched_kpts.size(0),
                    assigned_gt_idx_expanded.size(1),
                    self.n_keypoints,
                    3,
                )
            )
        else:
            selected_keypoints = batched_kpts.gather(
                1, assigned_gt_idx_expanded.expand(-1, -1, self.n_keypoints, 3)
            )
        xy_components = selected_keypoints[..., :2]
        normalized_xy = xy_components / self.stride_tensor.view(1, -1, 1, 1)
        selected_keypoints = torch.cat(
            (normalized_xy, selected_keypoints[..., 2:]), dim=-1
        )
        gt_kpts = selected_keypoints[mask_positive]
        keypoints_raw = keypoints_raw[mask_positive]
        assigned_bboxes = assigned_bboxes / self.stride_tensor

        area = (
            (
                assigned_bboxes[mask_positive][:, 0]
                - assigned_bboxes[mask_positive][:, 2]
            )
            * (
                assigned_bboxes[mask_positive][:, 1]
                - assigned_bboxes[mask_positive][:, 3]
            )
            * self.area_factor
        )

        d = (gt_kpts[..., 0] - keypoints_raw[..., 0]).pow(2) + (
            gt_kpts[..., 1] - keypoints_raw[..., 1]
        ).pow(2)
        e = d / ((2 * sigmas).pow(2) * ((area.view(-1, 1) + 1e-9) * 2))
        mask = (gt_kpts[..., 2] > 0).float()
        regression_loss = (
            ((1 - torch.exp(-e)) * mask).sum(dim=1) / (mask.sum(dim=1) + 1e-9)
        ).mean()

        visibility_loss = F.binary_cross_entropy_with_logits(
            keypoints_raw[..., 2],
            mask,
            pos_weight=self.pos_weight.clone().to(device),
        )

        one_hot_label = F.one_hot(assigned_labels.long(), self.n_classes + 1)[
            ..., :-1
        ]
        loss_cls = self.varifocal_loss(
            class_scores, assigned_scores, one_hot_label
        )

        if assigned_scores.sum() > 1:
            loss_cls /= assigned_scores.sum()

        loss_iou = compute_iou_loss(
            pred_bboxes,
            assigned_bboxes,
            assigned_scores,
            mask_positive,
            reduction="sum",
            iou_type=self.iou_type,
            bbox_format="xyxy",
        )[0]

        loss = (
            self.class_loss_weight * loss_cls
            + self.iou_loss_weight * loss_iou
            + regression_loss * self.regr_kpts_loss_weight
            + visibility_loss * self.vis_kpts_loss_weight
        )

        sub_losses = {
            "class": loss_cls.detach(),
            "iou": loss_iou.detach(),
            "regression": regression_loss.detach(),
            "visibility": visibility_loss.detach(),
        }

        return loss, sub_losses

    def _preprocess_kpts_target(
        self, kpts_target: Tensor, batch_size: int, scale_tensor: Tensor
    ) -> Tensor:
        """Convert the keypoint label to padded keypoints per image.

        Args:
            kpts_target (``Tensor``): The keypoints of shape
                ``[M, 2 + 3 * n_keypoints]``, with the batch index and
                the class in the first two columns. The ``x``, ``y``,
                and visibility of each keypoint follow, with ``x`` and
                ``y`` normalized.
            batch_size (int): The number of images ``B``.
            scale_tensor (``Tensor``): The width and the height of the
                input image, of shape ``[2]``.

        Returns:
            ``Tensor``: Keypoints of shape ``[B, K, n_keypoints, 3]``.
            ``K`` is the largest number of instances in one image, or
            ``0`` for a batch without instances. ``x`` and ``y`` are in
            pixels of the input image. A padding instance has only
            zeros.

        """
        _, counts = torch.unique(kpts_target[:, 0].int(), return_counts=True)
        max_kpts = int(counts.max()) if counts.numel() > 0 else 0
        batched_keypoints = torch.zeros(
            (batch_size, max_kpts, self.n_keypoints, 3),
            device=kpts_target.device,
        )
        for i in range(batch_size):
            keypoints_i = kpts_target[kpts_target[:, 0] == i]
            scaled_keypoints_i = keypoints_i[:, 2:].clone()
            batched_keypoints[i, : keypoints_i.shape[0]] = (
                scaled_keypoints_i.view(-1, self.n_keypoints, 3)
            )
            batched_keypoints[i, :, :, :2] *= scale_tensor[:2]

        return batched_keypoints

    def dist2kpts_noscale(self, anchor_points: Tensor, kpts: Tensor) -> Tensor:
        """Decode the raw keypoint offsets around the anchor points.

        For the raw values :math:`(t_x, t_y)` and the anchor point
        :math:`(a_x, a_y)`, the decoded position is
        :math:`(2 t_x + a_x - 0.5, 2 t_y + a_y - 0.5)`. The method
        keeps the third value of each keypoint as it is. Unlike the
        decoding of `EfficientKeypointBBoxHead`, it does not multiply
        the position by the stride. The method does not change ``kpts``.

        Args:
            anchor_points (``Tensor``): The anchor points of shape
                ``[N, 2]``, as ``(x, y)``. The loss passes them in grid
                units.
            kpts (``Tensor``): The raw keypoint values of shape
                ``[B, N, n_keypoints, 3]``.

        Returns:
            ``Tensor``: The decoded keypoints, of the shape of ``kpts``,
            in the units of ``anchor_points``.

        """
        adj_kpts = kpts.clone()
        scale = 2.0
        x_adj = anchor_points[:, [0]] - 0.5
        y_adj = anchor_points[:, [1]] - 0.5

        adj_kpts[..., :2] *= scale
        adj_kpts[..., 0] += x_adj
        adj_kpts[..., 1] += y_adj
        return adj_kpts
