"""The weighted focal loss of the FOMO heatmap of object centers."""

import torch
import torch.nn.functional as F
from torch import Tensor

from luxonis_train.nodes import FOMOHead
from luxonis_train.tasks import Tasks
from luxonis_train.utils import get_center_keypoints

from .base_loss import BaseLoss


class FOMOLocalizationLoss(BaseLoss):
    r"""Focal loss of `FOMOHead` over a heatmap of object centers.

    Inputs:
        - ``heatmap`` (``Tensor``): :math:`\left[B, n_{classes}, H_f,
          W_f\right]` logits
        - ``target`` (``Tensor``): :math:`\left[M, 6\right]`, ``[batch,
          class, x, y, w, h]``, ``xywh`` normalized

    Outputs:
        - ``Tensor``: scalar

    Formula:
        The target heatmap :math:`y` is ``1`` in the cell that holds the
        center of a box, in the channel of the box class. It is ``0`` in
        all other cells. For the logit :math:`x` of each cell:

        .. math::

            L = \frac{1}{B \, n_{classes} \, H_f \, W_f} \sum
            \alpha \, (1 - p_t)^{\gamma} \, w \, \text{BCE}(x, y),
            \qquad
            p_t = \exp\left(-\text{BCE}(x, y)\right)

        :math:`\text{BCE}` is the binary cross entropy with logits, and
        :math:`p_t` is the predicted probability of the target value.
        :math:`w` is ``object_weight`` in a center cell and ``1`` in the
        other cells. :math:`\alpha` is ``alpha``, and :math:`\gamma` is
        ``gamma``.

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        The FOMO task has no keypoint labels, so the loss uses the box
        centers as the targets. The center of a box with the normalized
        top-left corner :math:`(x, y)` and size :math:`(w, h)` is in
        column :math:`\lfloor (x + w / 2) \, W_f \rfloor` and row
        :math:`\lfloor (y + h / 2) \, H_f \rfloor`. Two boxes of one
        class with centers in the same cell give one target cell.
        Unlike the usual focal loss, :math:`\alpha` scales the center
        cells and the other cells by the same factor.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``FOMOHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: FOMOHead
              inputs: [EfficientRep]
              losses:
                - name: FOMOLocalizationLoss

    Compatible with:
        - Used by: `FOMOModel`
        - Nodes: `FOMOHead`

    """

    node: FOMOHead
    supported_tasks = [Tasks.FOMO]

    def __init__(
        self,
        object_weight: float = 500,
        alpha: float = 0.45,
        gamma: float = 2,
        **kwargs,
    ):
        r"""Initialize the loss.

        The method reads the input image size of the node. `forward`
        does not use the size. The loss therefore needs a node: without
        ``node``, `BaseAttachedModule.node` raises ``RuntimeError``.

        Args:
            object_weight (float): The factor :math:`w` of the loss in a
                center cell. The other cells have the factor ``1``.
            alpha (float): The factor :math:`\alpha` of the loss in
                every cell.
            gamma (float): The exponent :math:`\gamma` of the focal
                term. A higher value lowers the loss of the cells that
                the head already predicts well. ``0`` removes the focal
                term.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseLoss`, such as ``final_loss_weight`` and ``node``.

        """
        super().__init__(**kwargs)
        self._original_img_size = self.original_in_shape[1:]
        self._object_weight = object_weight
        self._alpha = alpha
        self._gamma = gamma

    def forward(self, heatmap: Tensor, target: Tensor) -> Tensor:
        r"""Build the target heatmap and compute the weighted focal loss.

        Args:
            heatmap (``Tensor``): The class logits of shape
                ``[B, n_classes, H, W]``, from the ``heatmap`` key of the
                node output.
            target (``Tensor``): The ``boundingbox`` label of shape
                ``[M, 6]``. Each row holds the batch index, the class,
                and the normalized ``x``, ``y``, ``w``, and ``h`` of one
                box. ``x`` and ``y`` give the top-left corner.

        Returns:
            ``Tensor``: The mean of the weighted focal loss over all
            cells of ``heatmap``, as a scalar.

        Example:
            The example uses a heatmap of zero logits on a ``4x4`` grid.
            One box has its center in column ``2`` and row ``2``. Each
            cell has the binary cross entropy :math:`\ln 2` and the focal
            factor :math:`0.45 \cdot 0.5^2`. The center cell has the
            weight ``500``, so it gives most of the loss:

            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import FOMOHead
            >>> sizes = [Size([1, 8, 8, 8]), Size([1, 16, 4, 4])]
            >>> head = FOMOHead(
            ...     n_classes=1,
            ...     input_shapes=[{"features": sizes}],
            ...     original_in_shape=Size([3, 32, 32]),
            ... )
            >>> heatmap = torch.zeros(1, 1, 4, 4)
            >>> target = torch.tensor([[0.0, 0.0, 0.25, 0.25, 0.5, 0.5]])
            >>> loss = FOMOLocalizationLoss(node=head)
            >>> round(loss(heatmap, target).item(), 4)
            2.51
            >>> loss = FOMOLocalizationLoss(node=head, object_weight=1)
            >>> round(loss(heatmap, target).item(), 4)
            0.078

        """
        batch_size, n_classes, height, width = heatmap.shape
        target_keypoints = get_center_keypoints(
            target, height=height, width=width
        ).int()
        target_heatmap = torch.zeros(
            (batch_size, n_classes, height, width), device=heatmap.device
        )

        for bbox, kpt in zip(target, target_keypoints, strict=True):
            class_id = int(bbox[1])
            batch_index, x_c, y_c = kpt[:3]
            target_heatmap[batch_index, class_id, y_c, x_c] = 1.0

        weight_matrix = torch.ones_like(target_heatmap)
        weight_matrix[target_heatmap == 1] = self._object_weight
        bce = F.binary_cross_entropy_with_logits(
            heatmap, target_heatmap, reduction="none"
        )
        pt = torch.exp(-bce)
        focal = self._alpha * (1 - pt) ** self._gamma

        weighted_loss = focal * bce * weight_matrix
        return weighted_loss.mean()
