"""Mean average precision over keypoints, matched by object keypoint
similarity instead of IoU.
"""

from typing import Annotated, Literal

import torch
from faster_coco_eval.core import COCO, COCOeval_faster
from torch import Tensor
from torchvision.ops import box_convert
from typeguard import typechecked
from typing_extensions import override

from luxonis_train.attached_modules.metrics import BaseMetric, MetricState
from luxonis_train.attached_modules.metrics.mean_average_precision.utils import (
    add_f1_metrics,
    postprocess_metrics,
)
from luxonis_train.attached_modules.metrics.utils import (
    fix_empty_tensor,
    merge_bbox_kpt_targets,
)
from luxonis_train.tasks import Tasks
from luxonis_train.utils import get_sigmas, get_with_default


class MeanAveragePrecisionKeypoints(BaseMetric):
    r"""Mean average precision metric for keypoint detections.

    The metric matches predictions to targets by the object keypoint
    similarity (OKS) instead of the IoU. `update` stores the
    predictions and targets of each image. `compute` evaluates all of
    them with the COCO keypoint evaluation of ``faster_coco_eval``.

    Inputs:
        - ``keypoints`` (``list[Tensor]``): :math:`\left[M_i,
          n_{keypoints}, 3\right]` per image, ``(x, y, conf)``, pixels
        - ``boundingbox`` (``list[Tensor]``): :math:`\left[M_i,
          6\right]` per image, ``[x1, y1, x2, y2, conf, class]``, pixels
        - ``target_keypoints`` (``Tensor``): :math:`\left[N, 1 + 3 *
          n_{keypoints}\right]`, ``[batch, x, y, v, ...]``, normalized
        - ``target_boundingbox`` (``Tensor``): :math:`\left[N,
          6\right]`, ``[batch, class, x, y, w, h]``, ``xywh`` normalized

    Outputs:
        - ``kpt_map`` (``Tensor``): scalar, the main metric
        - ``dict[str, Tensor]``: the other keypoint AP, AR, and F1
          values, see `compute`

    Formula:
        For a target and a prediction of the same class, the OKS is a
        mean over the visible target keypoints :math:`V`:

        .. math::

            \text{OKS} = \frac{1}{|V|} \sum_{i \in V} \exp\left(-\frac{d_i^2}{2 \, (2 \sigma_i)^2 \, A}\right)

        :math:`d_i` is the distance between the two keypoints :math:`i`,
        and :math:`\sigma_i` is the sigma of keypoint :math:`i`.
        :math:`A` is the area of the target box, multiplied by
        ``area_factor``. The AP and the AR then follow the COCO
        evaluation, with the OKS in place of the IoU. The OKS
        thresholds are :math:`0.5, 0.55, \ldots, 0.95`.

    References:
        - Source: Adapted from the `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics/blob/v1.0.1/src/torchmetrics/detection/mean_ap.py>`_
          mean average precision metric.
        - License: Apache-2.0

    Notes:
        The evaluation keeps at most ``max_dets`` predictions of each
        class in each image, the ones with the highest scores. It
        ignores a target when all its keypoints have the visibility
        ``0``. The size ranges are ``medium``, an area from
        :math:`32^2` to :math:`96^2` pixels, and ``large``, an area
        above :math:`96^2` pixels. The area of an object is its box area
        multiplied by ``area_factor``, so ``area_factor`` also changes
        the size range of an object. `update` truncates the target boxes
        and keypoints to integer pixels.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientKeypointBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientKeypointBBoxHead
              inputs: [RepPANNeck]
              metrics:
                - name: MeanAveragePrecisionKeypoints

    Compatible with:
        - Nodes: `EfficientKeypointBBoxHead`

    """

    supported_tasks = [
        Tasks.INSTANCE_KEYPOINTS,
        Tasks.INSTANCE_SEGMENTATION_KEYPOINTS,
    ]

    pred_bboxes: Annotated[list[Tensor], MetricState()]
    pred_scores: Annotated[list[Tensor], MetricState()]
    pred_classes: Annotated[list[Tensor], MetricState()]
    pred_keypoints: Annotated[list[Tensor], MetricState()]

    target_bboxes: Annotated[list[Tensor], MetricState()]
    target_classes: Annotated[list[Tensor], MetricState()]
    target_keypoints: Annotated[list[Tensor], MetricState()]

    @typechecked
    def __init__(
        self,
        sigmas: list[float] | None = None,
        area_factor: float | None = None,
        max_dets: int = 20,
        box_format: Literal["xyxy", "xywh", "cxcywh"] = "xyxy",
        class_metrics: bool = False,
        **kwargs,
    ):
        """Initialize the keypoint mean average precision metric.

        The ``typechecked`` decorator checks the types of the arguments.
        An argument of a wrong type raises ``typeguard.TypeCheckError``.

        Args:
            sigmas (list[float] | None): The OKS sigma of each keypoint,
                see the formula of the class. A larger sigma tolerates a
                larger distance. ``None`` selects the defaults of
                `get_sigmas`: the COCO sigmas for ``17`` keypoints, else
                ``0.04`` for each keypoint. `get_sigmas` then logs a
                warning for the COCO sigmas and an info message for
                ``0.04``. A list with a length other than
                ``n_keypoints`` makes `get_sigmas` raise ``ValueError``.
            area_factor (float | None): The factor that scales the area
                of a box to the area of the object. ``None`` selects
                ``0.53`` and logs an info message.
            max_dets (int): The maximum number of predictions of one
                class in one image that the evaluation keeps, the ones
                with the highest scores.
            box_format (``Literal["xyxy", "xywh", "cxcywh"]``): The
                format that `update` converts to ``xywh``, for both the
                predicted and the target boxes. `update` gives the
                target boxes in the ``xyxy`` format, so only ``"xyxy"``
                gives correct target boxes.
            class_metrics (bool): Whether `compute` also returns the AP,
                the AR, and the F1 score of each class. The predefined
                model parameter ``per_class_metrics`` sets it.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseMetric`, such as ``node``. The method reads
                ``n_keypoints`` from the node, so it raises
                ``RuntimeError`` when ``node`` is not given.

        """
        super().__init__(**kwargs)

        self.sigmas = get_sigmas(sigmas, self.n_keypoints, self.name)
        self.area_factor = get_with_default(
            area_factor, "bbox area scaling", self.name, default=0.53
        )
        self.max_dets = max_dets
        self.box_format = box_format
        self.class_metrics = class_metrics

    @override
    def update(
        self,
        keypoints: list[Tensor],
        boundingbox: list[Tensor],
        target_keypoints: Tensor,
        target_boundingbox: Tensor,
    ) -> None:
        """Store the predictions and the targets of one batch.

        `merge_bbox_kpt_targets` merges the two labels into one tensor
        with ``xyxy`` boxes. For each image ``i`` of the batch, the
        method appends one entry to each metric state:

        - ``pred_bboxes``: the first four box columns, converted from
          ``box_format`` to ``xywh``.
        - ``pred_scores`` and ``pred_classes``: the fifth box column,
          and the sixth box column as ``int32``.
        - ``pred_keypoints``: the keypoints, of shape
          ``[M_i, 3 * n_keypoints]``.
        - ``target_classes``: the classes of the targets of the image,
          as ``int32``.
        - ``target_bboxes`` and ``target_keypoints``: the boxes and the
          keypoints of the targets of the image. The method scales them
          to pixels with the height and width of
          `BaseAttachedModule.original_in_shape`, and truncates them to
          integers. It converts the boxes from ``box_format`` to
          ``xywh``.

        Args:
            keypoints (``list[Tensor]``): The predicted keypoints of each
                image, of shape ``[M_i, n_keypoints, 3]``, as
                ``(x, y, score)`` in pixels.
            boundingbox (``list[Tensor]``): The predicted boxes of each
                image, of shape ``[M_i, 6]``, as
                ``[x1, y1, x2, y2, score, class]`` in pixels.
            target_keypoints (``Tensor``): The ``keypoints`` label of the
                batch, of shape ``[N, 1 + 3 * n_keypoints]``, as
                ``[batch_index, x, y, visibility, ...]``, normalized.
            target_boundingbox (``Tensor``): The ``boundingbox`` label of
                the batch, of shape ``[N, 6]``, as
                ``[batch_index, class, x, y, w, h]``, normalized, in the
                row order of ``target_keypoints``.

        """
        targets = merge_bbox_kpt_targets(
            target_boundingbox, target_keypoints, device=self.device
        )

        h, w = self.original_in_shape[1:]

        for i in range(len(keypoints)):
            self.pred_bboxes.append(
                self._convert_bboxes(boundingbox[i][:, :4])
            )
            self.pred_scores.append(boundingbox[i][:, 4])
            self.pred_classes.append(boundingbox[i][:, 5].int())
            self.pred_keypoints.append(
                fix_empty_tensor(
                    keypoints[i].reshape(-1, self.n_keypoints * 3)
                )
            )

            target = targets[targets[:, 0] == i]
            self.target_classes.append(target[:, 1].int())

            bboxes = target[:, 2:6]
            bboxes[:, 0::2] *= w
            bboxes[:, 1::2] *= h
            self.target_bboxes.append(self._convert_bboxes(bboxes.int()))

            kpts = target[:, 6:]
            kpts[:, 0::3] *= w
            kpts[:, 1::3] *= h
            self.target_keypoints.append(fix_empty_tensor(kpts.int()))

    @override
    def compute(self) -> tuple[Tensor, dict[str, Tensor]]:
        """Evaluate the stored keypoints with the COCO evaluation.

        The method builds one ``COCO`` object for the targets and one
        for the predictions. It runs ``COCOeval_faster`` with
        ``iouType="keypoints"``, the sigmas of the metric, and
        ``maxDets`` set to ``[max_dets]``. It keeps the evaluation
        object in the attribute ``coco_eval``. A value is ``-1`` when it
        has no data, for example ``kpt_map_large`` when no target is
        large.

        With ``class_metrics``, the method also reads the precision and
        recall arrays of the evaluation, for the area range ``"all"``.
        These arrays hold only the classes of the stored targets. The AP
        of a class is the mean over the OKS and recall thresholds. The AR
        of a class is the mean over the OKS thresholds. Both means skip
        the entries ``-1``, and a class with only ``-1`` entries gets
        ``0``.
        `luxonis_train.attached_modules.metrics.mean_average_precision.utils.postprocess_metrics`
        then splits these values per class.

        Returns:
            ``tuple[Tensor, dict[str, Tensor]]``: The scalar ``kpt_map``
            and a dictionary of the other values:

            - ``kpt_map_50`` and ``kpt_map_75``: the AP at the OKS
              thresholds ``0.5`` and ``0.75``.
            - ``kpt_map_medium`` and ``kpt_map_large``: the AP for
              medium and large objects.
            - ``kpt_mar``, ``kpt_mar_50``, ``kpt_mar_75``,
              ``kpt_mar_medium``, and ``kpt_mar_large``: the AR at the
              same settings as the AP.
            - ``kpt_f1``, ``kpt_f1_50``, ``kpt_f1_75``,
              ``kpt_f1_medium``, and ``kpt_f1_large``: the F1 score of
              each pair of AP and AR.
            - ``kpt_map_per_class_<class name>``,
              ``kpt_mar_per_class_<class name>``, and
              ``kpt_f1_per_class_<class name>``: the values of each
              class of the targets. They are present only with
              ``class_metrics`` and more than one class in the targets.

        """
        coco_target = self._get_coco(
            self.target_bboxes,
            self.target_keypoints,
            self.target_classes,
        )
        coco_preds = self._get_coco(
            self.pred_bboxes,
            self.pred_keypoints,
            self.pred_classes,
            self.pred_scores,
        )

        self.coco_eval = COCOeval_faster(
            coco_target, coco_preds, iouType="keypoints"
        )
        self.coco_eval.params.kpt_oks_sigmas = self.sigmas.cpu().numpy()
        self.coco_eval.params.maxDets = [self.max_dets]

        self.coco_eval.run()

        stats = torch.tensor(
            self.coco_eval.stats, dtype=torch.float32, device=self.device
        )

        metrics = {
            "kpt_map": stats[0],
            "kpt_map_50": stats[1],
            "kpt_map_75": stats[2],
            "kpt_map_medium": stats[3],
            "kpt_map_large": stats[4],
            "kpt_mar": stats[5],
            "kpt_mar_50": stats[6],
            "kpt_mar_75": stats[7],
            "kpt_mar_medium": stats[8],
            "kpt_mar_large": stats[9],
        }

        if self.class_metrics:
            metrics.update(self._compute_class_metrics())
            return postprocess_metrics(
                metrics,
                self.classes.inverse,
                "kpt_map",
                self.device,
            )

        metrics = add_f1_metrics(metrics)
        main_metric_value = metrics.pop("kpt_map", stats[0])
        return (
            main_metric_value,
            metrics,
        )

    def _compute_class_metrics(self) -> dict[str, Tensor]:
        eval_metrics = self.coco_eval.eval
        precision = torch.as_tensor(
            eval_metrics["precision"], dtype=torch.float32, device=self.device
        )
        recall = torch.as_tensor(
            eval_metrics["recall"], dtype=torch.float32, device=self.device
        )
        classes = torch.as_tensor(
            self.coco_eval.params.catIds,
            dtype=torch.int64,
            device=self.device,
        )

        precision = precision[..., 0, 0]
        recall = recall[..., 0, 0]

        kpt_map_per_class = self._mean_valid(precision, dim=(0, 1))
        kpt_mar_per_class = self._mean_valid(recall, dim=0)

        return {
            "classes": classes,
            "kpt_map_per_class": kpt_map_per_class,
            "kpt_mar_per_class": kpt_mar_per_class,
        }

    def _mean_valid(
        self, values: Tensor, dim: int | tuple[int, ...]
    ) -> Tensor:
        valid = values > -1
        counts = valid.sum(dim=dim)
        summed = values.masked_fill(~valid, 0).sum(dim=dim)
        return torch.where(
            counts > 0,
            summed / counts.clamp_min(1),
            torch.zeros_like(summed),
        )

    def _get_coco(
        self,
        bboxes_list: list[Tensor],
        keypoints_list: list[Tensor],
        classes_list: list[Tensor],
        scores_list: list[Tensor] | None = None,
    ) -> COCO:
        """Convert stored targets or predictions to a ``COCO`` object.

        The `COCO data format <https://cocodataset.org/#format-data>`_
        defines the annotations. Each item of the lists is one image,
        with the image ID equal to its index. Each object of an image
        gets one annotation. Its ``area`` is the box width times the box
        height times ``area_factor``. Its ``num_keypoints`` is the count
        of keypoints with a third value other than ``0``. The keypoint
        evaluation ignores a target with ``num_keypoints`` equal to
        ``0``. The categories are the classes of all stored predictions
        and targets.

        Args:
            bboxes_list (``list[Tensor]``): The boxes of each image, of
                shape ``[M_i, 4]``, in the ``xywh`` format.
            keypoints_list (``list[Tensor]``): The keypoints of each
                image, of shape ``[M_i, 3 * n_keypoints]``.
            classes_list (``list[Tensor]``): The class of each object,
                of shape ``[M_i]``, for each image.
            scores_list (``list[Tensor] | None``): The score of each
                predicted object, of shape ``[M_i]``, for each image.
                ``None`` for the targets, which have no scores.

        Returns:
            ``COCO``: The indexed ``COCO`` object with the annotations,
            the images, and the categories.

        """
        annotations = []

        for i, (bboxes, keypoints, classes) in enumerate(
            zip(bboxes_list, keypoints_list, classes_list, strict=True)
        ):
            for j, (bbox, kpts, class_id) in enumerate(
                zip(bboxes, keypoints, classes, strict=False)
            ):
                annotation = {
                    "id": len(annotations) + 1,
                    "image_id": i,
                    "bbox": bbox.cpu().tolist(),
                    "area": (bbox[2] * bbox[3] * self.area_factor).item(),
                    "category_id": class_id.item(),
                    "keypoints": kpts.cpu().tolist(),
                    "num_keypoints": kpts[2::3].ne(0).sum().item(),
                    "iscrowd": 0,
                }

                if scores_list is not None:
                    annotation["score"] = scores_list[i][j].item()

                annotations.append(annotation)

        coco = COCO()
        coco.dataset = {  # type: ignore
            "annotations": annotations,
            "images": [{"id": i} for i in range(len(bboxes_list))],
            "categories": self._get_classes(),  # type: ignore
        }
        coco.createIndex()
        return coco

    def _get_classes(self) -> list[dict]:
        """Return the classes of the stored objects as COCO categories.

        Returns:
            list[dict]: One category for each unique class of the
            stored predictions and targets, sorted by class, as
            ``{"id": class, "name": str(class)}``.

        """
        return [
            {"id": i, "name": str(i)}
            for i in torch.cat(self.pred_classes + self.target_classes)
            .unique()
            .tolist()
        ]

    def _convert_bboxes(self, bboxes: Tensor) -> Tensor:
        bboxes = fix_empty_tensor(bboxes)
        if bboxes.numel() > 0:
            bboxes = box_convert(
                bboxes, in_fmt=self.box_format, out_fmt="xywh"
            )
        return bboxes
