"""The factory that returns the mean average precision metric for the
task of a node.
"""

from luxonis_train.nodes import BaseNode
from luxonis_train.registry import METRICS
from luxonis_train.tasks import Task, Tasks

from .mean_average_precision_bbox import MeanAveragePrecisionBBox
from .mean_average_precision_keypoints import MeanAveragePrecisionKeypoints
from .mean_average_precision_segmentation import (
    MeanAveragePrecisionSegmentation,
)


@METRICS.register()  # type: ignore
class MeanAveragePrecision:
    """Factory class for Mean Average Precision (mAP) metrics.

    Creates the appropriate mAP metric based on the task of the node.

    Inputs:
        - the attached node and the metric parameters

    Outputs:
        - the mAP metric for the node's task

    References:
        - Source: This project.
        - License: Apache-2.0 (this project)

    Notes:
        Registry-facing factory that returns the concrete mAP
        implementation for the attached node task.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``EfficientBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: EfficientBBoxHead
              inputs: [RepPANNeck]
              metrics:
                - name: MeanAveragePrecision

    Compatible with:
        - Used by: `DetectionModel`, `InstanceSegmentationModel`,
          `KeypointDetectionModel`
        - Nodes: `EfficientBBoxHead`, `EfficientKeypointBBoxHead`,
          `PrecisionBBoxHead`, `PrecisionSegmentBBoxHead`

    """

    @classmethod
    def get_predefined_model_params_aliases(
        cls, task: Task | None = None
    ) -> dict[str, str]:
        if task in {
            Tasks.BOUNDINGBOX,
            Tasks.INSTANCE_KEYPOINTS,
            Tasks.INSTANCE_SEGMENTATION,
            Tasks.INSTANCE_SEGMENTATION_KEYPOINTS,
        }:
            return {"per_class_metrics": "class_metrics"}
        return {}

    def __new__(
        cls, node: BaseNode, **kwargs
    ) -> (
        MeanAveragePrecisionBBox
        | MeanAveragePrecisionSegmentation
        | MeanAveragePrecisionKeypoints
    ):
        match node.task:
            case None:  # pragma: no cover
                raise ValueError(
                    f"Node {node.name} does not have the 'task' parameter set"
                )
            case Tasks.BOUNDINGBOX:
                return MeanAveragePrecisionBBox(
                    node=node, backend="faster_coco_eval", **kwargs
                )
            case Tasks.INSTANCE_SEGMENTATION:
                return MeanAveragePrecisionSegmentation(
                    node=node, backend="faster_coco_eval", **kwargs
                )
            case Tasks.INSTANCE_KEYPOINTS:
                return MeanAveragePrecisionKeypoints(node=node, **kwargs)
            case Tasks.INSTANCE_SEGMENTATION_KEYPOINTS:
                return MeanAveragePrecisionKeypoints(node=node, **kwargs)
            case _:  # pragma: no cover
                raise ValueError(
                    f"'MeanAveragePrecision' does not support task '{node.task.name}'"
                )
