"""Mean average precision over instance masks."""

from torch import Tensor
from torchmetrics.detection import MeanAveragePrecision
from typing_extensions import override

from luxonis_train.attached_modules.metrics import BaseMetric
from luxonis_train.tasks import Tasks

from .utils import compute_metric_lists, postprocess_metrics


class MeanAveragePrecisionSegmentation(MeanAveragePrecision, BaseMetric):
    r"""Mean average precision for instance segmentation masks.

    Inputs:
        - ``boundingbox`` (``list[Tensor]``): :math:`\left[M_i,
          6\right]` per image, ``[x1, y1, x2, y2, conf, class]``, pixels
        - ``instance_segmentation`` (``list[Tensor]``):
          :math:`\left[M_i, H, W\right]` per image, binary
        - ``target_boundingbox`` (``Tensor``): :math:`\left[N,
          6\right]`, ``[batch, class, x, y, w, h]``, ``xywh`` normalized
        - ``target_instance_segmentation`` (``Tensor``): :math:`\left[N,
          H, W\right]`, one per target box

    Outputs:
        - ``segm_map`` (``Tensor``): scalar, the main metric
        - ``dict[str, Tensor]``: box and mask AP, AR and F1

    Formula:
        Converts predictions and targets into torchmetrics detection lists and
        evaluates bbox and segmentation mAP/mAR.

    References:
        - Source: Wraps `torchmetrics
          <https://github.com/Lightning-AI/torchmetrics>`_ (Apache-2.0).
        - License: Apache-2.0 (this project)

    Notes:
        Uses ``iou_type=("bbox", "segm")`` and postprocesses
        segmentation metrics with dataset class names.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        Attached to a ``PrecisionSegmentBBoxHead`` in ``model.nodes``:

        .. code-block:: yaml

            - name: PrecisionSegmentBBoxHead
              inputs: [RepPANNeck]
              metrics:
                - name: MeanAveragePrecisionSegmentation

    Compatible with:
        - Nodes: ``PrecisionSegmentBBoxHead``

    """

    supported_tasks = [
        Tasks.INSTANCE_SEGMENTATION,
        Tasks.INSTANCE_SEGMENTATION_KEYPOINTS,
    ]

    def __init__(self, **kwargs):
        super().__init__(iou_type=("bbox", "segm"), **kwargs)

    @override
    def update(
        self,
        boundingbox: list[Tensor],
        instance_segmentation: list[Tensor],
        target_boundingbox: Tensor,
        target_instance_segmentation: Tensor,
    ) -> None:
        super().update(
            *compute_metric_lists(
                boundingbox,
                target_boundingbox,
                *self.original_in_shape[1:],
                masks=instance_segmentation,
                target_masks=target_instance_segmentation,
            )
        )

    @override
    def compute(self) -> tuple[Tensor, dict[str, Tensor]]:
        metrics = {k: v.to(self.device) for k, v in super().compute().items()}
        return postprocess_metrics(
            metrics, self.classes.inverse, "segm_map", self.device
        )
