"""The semantic segmentation model."""

from luxonis_ml.typing import Params
from typing_extensions import override

from luxonis_train.config import LossModuleConfig, NodeConfig
from luxonis_train.config.predefined_models.base_predefined_model import (
    SimplePredefinedModel,
)


class SegmentationModel(SimplePredefinedModel):
    """Semantic segmentation, which predicts a class for each pixel.

    Throughput:
        Frames per second at 384x512.

        - ``light``: 43 on RVC2, 75 on RVC4
        - ``heavy``: 14 on RVC2, 48 on RVC4

    Notes:
        `JaccardIndex` and `F1Score` wrap ``torchmetrics`` and read a
        ``task`` key from ``metrics_params``. Set it to ``"binary"`` for
        one class and to ``"multiclass"`` otherwise. Without ``task``, a
        metric takes ``"binary"`` for one class and ``"multiclass"``
        otherwise, and logs a warning.

        By default, the model attaches an auxiliary head to an earlier
        output of the backbone. The loss of the auxiliary head adds to
        the total loss with weight ``0.4``. The export removes the
        auxiliary head.

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        The ``model`` section of a config:

        .. code-block:: yaml

            model:
              predefined_model:
                name: SegmentationModel
                params:
                  variant: light

    Components:
        - Nodes: `DDRNet` -> `DDRNetSegmentationHead` ->
          `DDRNetSegmentationHead`
        - Losses: `OHEMLoss`
        - Metrics:

          - `ConfusionMatrix`
          - `F1Score`
          - `JaccardIndex`

        - Visualizers: `SegmentationVisualizer`
        - Main metric: `JaccardIndex`
        - Variants:

          - ``light``
          - ``heavy``

    """

    def __init__(
        self,
        use_aux_head: bool = True,
        aux_head_params: Params | None = None,
        **kwargs,
    ):
        """Initialize the model with its default components.

        The constructor sets ``attach_index`` to ``-1`` in
        ``head_params``, unless ``head_params`` holds an ``aux_head``
        key. This value replaces an ``attach_index`` that
        ``head_params`` sets.

        Args:
            use_aux_head (bool): Add the auxiliary head to the node graph.
                See `nodes`.
            aux_head_params (``Params | None``): The constructor
                parameters of the auxiliary head. The constructor edits
                a given non-empty dictionary in place:

                - It sets ``attach_index`` to ``-2`` when the dictionary
                  does not hold the key. The auxiliary head then reads
                  the second-to-last output of the backbone. For
                  `DDRNet` with its default ``use_aux_heads``, that
                  output holds the high-resolution features.
                - It removes the ``use_aux_heads`` key, and uses its
                  value as ``remove_on_export`` of the auxiliary head.
                  Without the key, the value is ``True``.

            **kwargs (``Any``): Keyword arguments for
                `SimplePredefinedModel.__init__`.

        Raises:
            TypeError: When the ``use_aux_heads`` value in
                ``aux_head_params`` is not a bool.

        """
        super().__init__(
            **{
                "backbone": "DDRNet",
                "head": "DDRNetSegmentationHead",
                "loss": "OHEMLoss",
                "metrics": ["JaccardIndex", "F1Score"],
                "confusion_matrix_available": True,
                "main_metric": "JaccardIndex",
                "visualizer": "SegmentationVisualizer",
            }
            | kwargs
        )

        self._use_aux_heads = use_aux_head

        self._aux_head_params = aux_head_params or {}
        if "attach_index" not in self._aux_head_params:
            self._aux_head_params["attach_index"] = -2
        if "aux_head" not in self._head_params:
            self._head_params["attach_index"] = -1

        remove_aux_on_export = self._aux_head_params.pop("use_aux_heads", True)
        if not isinstance(remove_aux_on_export, bool):
            raise TypeError(
                "The `aux_head_params.remove_on_export` parameter "
                f"must be a boolean. Got `{remove_aux_on_export}`."
            )
        self._remove_aux_on_export = remove_aux_on_export

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Params]]:
        """Get the default variant name and the available variants.

        The default is ``light``. Both variants set ``backbone`` to
        ``"DDRNet"`` and ``head`` to ``"DDRNetSegmentationHead"``. They
        differ in the backbone:

        - ``light``: the ``"23-slim"`` variant of `DDRNet`, with
          ``weights`` set to ``"download"`` in ``backbone_params``;
        - ``heavy``: the ``"23"`` variant of `DDRNet`, without
          ``backbone_params``, so the backbone loads no checkpoint.

        Both variants set ``weights`` to ``"download"`` in
        ``head_params``, so the head loads its COCO checkpoint. A
        ``backbone_params`` or ``head_params`` given in the config
        replaces the whole dictionary of the variant. The auxiliary head
        loads no checkpoint.

        Returns:
            ``tuple[str, dict[str, Params]]``: ``"light"`` and the two
            variants with their constructor arguments.

        Example:
            >>> default, variants = SegmentationModel.get_variants()
            >>> default, variants["heavy"]["backbone_variant"]
            ('light', '23')
            >>> "backbone_params" in variants["heavy"]
            False

        """
        return "light", {
            "light": {
                "backbone": "DDRNet",
                "backbone_params": {"weights": "download"},
                "backbone_variant": "23-slim",
                "head": "DDRNetSegmentationHead",
                "head_params": {"weights": "download"},
            },
            "heavy": {
                "backbone": "DDRNet",
                "backbone_variant": "23",
                "head": "DDRNetSegmentationHead",
                "head_params": {"weights": "download"},
            },
        }

    @property
    @override
    def nodes(self) -> list[NodeConfig]:
        """The backbone, the head, and the auxiliary head, as configs.

        The first configs come from `SimplePredefinedModel.nodes`. When
        ``use_aux_head`` is ``True``, the property appends a second
        config of the ``head`` class with these fields:

        - ``alias``: the class name with the suffix ``_aux``;
        - ``inputs``: the backbone;
        - ``params``: ``aux_head_params``;
        - ``task_name``: the ``task_name`` of the model;
        - ``remove_on_export``: the ``use_aux_heads`` value of
          ``aux_head_params``, ``True`` by default;
        - ``losses``: the ``loss`` of the model with weight ``0.4``,
          without ``loss_params``.

        The auxiliary head has no metrics, no visualizer, and no
        freezing. Its ``variant`` keeps the `NodeConfig` default
        ``"default"``. `DDRNetSegmentationHead` declares no variants, so
        the build of the node logs a warning and uses no variant
        parameters.

        Example:
            >>> from luxonis_train.config.predefined_models import (
            ...     SegmentationModel,
            ... )
            >>> model = SegmentationModel(variant="light")
            >>> [(node.identifier, node.inputs) for node in model.nodes]
            [('DDRNet', []),
             ('DDRNetSegmentationHead', ['DDRNet']),
             ('DDRNetSegmentationHead_aux', ['DDRNet'])]
            >>> aux_head = model.nodes[-1]
            >>> aux_head.params, aux_head.remove_on_export
            ({'attach_index': -2}, True)
            >>> [(loss.name, loss.weight) for loss in aux_head.losses]
            [('OHEMLoss', 0.4)]

        """
        nodes = super().nodes
        if self._use_aux_heads:
            nodes.append(
                NodeConfig(
                    name=self._head,
                    alias=f"{self._head}_aux",
                    inputs=[self._backbone],
                    params=self._aux_head_params,
                    task_name=self._task_name,
                    remove_on_export=self._remove_aux_on_export,
                    losses=[
                        LossModuleConfig(
                            name=self._loss,
                            weight=0.4,
                        )
                    ],
                )
            )
        return nodes
