model:
  name: AnomalyDetecion
  predefined_model:
    name: AnomalyDetectionModel
    variant: light

loader:
  name: LuxonisLoaderPerlinNoise
  params:
    dataset_name: mvtec_v2
    anomaly_source_path:  "../data/dtd/images/"

trainer:
  preprocessing:
    train_image_size: [256, 256]
    keep_aspect_ratio: False
    normalize:
      active: True

  batch_size: 4
  epochs: 300
  n_workers: 4
  validation_interval: 10
  n_log_images: 8
