# Example configuration for training a predefined light classification model

model:
  name: classification_light
  predefined_model:
    name: ClassificationModel
    variant: light

loader:
  params:
    dataset_name: cifar10_test

trainer:
  preprocessing:
    train_image_size: [384, 512]
    keep_aspect_ratio: true
    normalize:
      active: true

  batch_size: 8
  epochs: 200
  n_workers: 4
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: Adam
    params:
      lr: 0.003

  scheduler:
    name: ConstantLR
