# Example configuration for training a predefined segmentation model

model:
  name: cifar10_classification
  predefined_model:
    name: ClassificationModel
    params:
      variant: "light"
      visualizer_params:
        font_scale: 0.5
        color: [255, 0, 0]
        thickness: 2
        include_plot: True

loader:
  params:
    dataset_name: cifar10_test

trainer:
  preprocessing:
    train_image_size: [&height 384, &width 512]
    keep_aspect_ratio: True
    normalize:
      active: True

  batch_size: 4
  epochs: &epochs 200
  n_workers: 4
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: Adam
    params:
      lr: 0.003

  scheduler:
    name: ConstantLR
