# Example configuration for training a predefined segmentation model

model:
  name: ddrnet_segmentation
  predefined_model:
    name: DDRNetSegmentationModel
    params:
      backbone: DDRNet
      task: multiclass
      backbone_params:
        use_aux_heads: True # set to False to disable auxiliary heads (for export)
       
      head_params:
        in_planes: 128
        num_classes: 80 # number of classes
        attach_index: 0
      aux_head_params: # ignored if use_aux_heads is False
        in_planes: 64
        num_classes: 80 # number of classes
        attach_index: 1


loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [&height 256, &width 320] # [512, 512]
    keep_aspect_ratio: False
    normalize:
      active: True

  batch_size: 4 # 32
  epochs: &epochs 1 # 500
  num_workers: 4
  validation_interval: 10
  num_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0005

  scheduler:
    name: PolynomialLR
