# Example configuration for training a predefined light detection model

model:
  name: detection_light
  predefined_model:
    name: DetectionModel
    params:
      variant: light

loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [&height 384, &width 512]
    keep_aspect_ratio: True
    normalize:
      active: True

  batch_size: 8
  epochs: &epochs 200
  n_workers: 8
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD
    params:
      lr: 0.02             
      momentum: 0.937    
      weight_decay: 0.0005   
      dampening: 0.0       
      nesterov: true     

  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: *epochs   
      eta_min: 0.0002 
      last_epoch: -1        
