# Example configuration for training a predefined light detection model
# NOTE: This example downloads pretrained COCO weights and training parameters are already prepared for fine tuning

model:
  name: detection_light
  predefined_model:
    name: DetectionModel
    params:
      variant: light
      loss_params:
        iou_type: "siou"
        n_warmup_epochs: 0 # No assigner warmup
        iou_loss_weight: 20 # Should be 2.5 * accumulate_grad_batches for best results
        class_loss_weight: 8 # Should be 1 * accumulate_grad_batches for best results

loader:
  params:
    dataset_name: coco_test

trainer:
  precision: "16-mixed"
  preprocessing:
    train_image_size: [384, 512]
    keep_aspect_ratio: true
    normalize:
      active: true
      params:
        mean: [0., 0., 0.]
        std: [1, 1, 1]

  batch_size: 8
  epochs: &epochs 300
  accumulate_grad_batches: 8 # For best results, always accumulate gradients to effectively use 64 batch size
  n_workers: 8
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: EMACallback
      params:
        decay: 0.9999
        use_dynamic_decay: True
        decay_tau: 2000
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  training_strategy: # Fine tuning params
    name: "TripleLRSGDStrategy"
    params:
      warmup_epochs: 2
      warmup_bias_lr: 0.05
      warmup_momentum: 0.5
      lr: 0.0032
      lre: 0.000384
      momentum: 0.843
      weight_decay: 0.00036
      nesterov: True
