# Example configuration for training a predefined fomo light detection model

model:
  name: fomo_detection_light
  predefined_model:
    name: FOMOModel
    params:
      variant: light

loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [384, 512]
    keep_aspect_ratio: true
    normalize:
      active: true

  batch_size: 8
  epochs: &epochs 200
  n_workers: 8
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: "Adam"
    params:
      lr: 0.001

  callbacks:
    - name: EMACallback
      params:
        decay: 0.9999 
        use_dynamic_decay: True 
        decay_tau: 2000