# Example configuration for training a predefined light detection model
# NOTE: This example downloads pretrained COCO weights and training parameters are already prepared for fine tuning

model:
  name: detection_light
  predefined_model:
    name: DetectionModel
    params:
      variant: light

loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [384, 512]
    keep_aspect_ratio: true
    normalize:
      active: true

  batch_size: 8
  epochs: &epochs 200
  n_workers: 8
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD
    params:
      lr: 0.0032           
      momentum: 0.843      
      weight_decay: 0.00036 
      dampening: 0.0        
      nesterov: true    

  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: *epochs         
      eta_min: 0.000384

  callbacks:
    - name: EMACallback
      params:
        decay: 0.9999 
        use_dynamic_decay: True 
        decay_tau: 2000
