model:
  name: dino_model
  nodes:
    - name: DinoV3
      params:
        weights_link: "REDACTED"
        return_sequence: false  # this will change the encoder output to a feature map

    - name: ClassificationHead
      inputs:
        - DinoV3

      losses:
        - name: CrossEntropyLoss

      metrics:
        - name: Accuracy
          is_main_metric: true

loader:
  params:
    dataset_name: bean_classification_dataset

trainer:
  preprocessing:
    train_image_size: [500, 500]
    keep_aspect_ratio: true
    normalize:
      active: true

  batch_size: 16
  epochs: &epochs 10
  n_workers: 8
  validation_interval: 5
  n_log_images: 8

  optimizer:
    name: Adam
    params:
      lr: 0.0003

  scheduler:
    name: ConstantLR