model:
  name: dino_model
  nodes:
    - name: DinoV3
      params:
        weights_link: "REDACTED"
        return_sequence: true # this will return patch-level embeddings to send to the transformer head

    - name: TransformerClassificationHead
      inputs:
        - DinoV3

      losses:
        - name: CrossEntropyLoss

      metrics:
        - name: Accuracy
          is_main_metric: true

      visualizers:
        - name: ClassificationVisualizer

loader:
  params:
    dataset_name: bean_classification_dataset

exporter:
  onnx:
    opset_version: 16

trainer:
  preprocessing:
    train_image_size: [ 384, 384 ]
    keep_aspect_ratio: true
    normalize:
      active: true

  batch_size: 16
  epochs: 10
  n_workers: 8
  validation_interval: 5
  n_log_images: 8

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: Adam
    params:
      lr: 0.0003

  scheduler:
    name: ConstantLR