model:
  name: reid_test
  predefined_model:
    name: EmbeddingsModel

loader:
  params:
    dataset_name: ParkingLot

trainer:
  preprocessing:
    train_image_size: [256, 256]

  batch_size: 16
  epochs: 100
  validation_interval: 10
  n_log_images: 8

  callbacks:
    - name: ConvertOnTrainEnd
