# Example configuration for exporting a predefined segmentation model

model:
  name: coco_segmentation
  weights: null  # specify a path to the weights here
  predefined_model:
    name: DetectionModel
    variant: light

loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [&height 384, &width 512]
    keep_aspect_ratio: True
    normalize:
      active: True

  batch_size: 8
  epochs: &epochs 200
  n_workers: 4
  validation_interval: 10
  n_log_images: 8

  optimizer:
    name: SGD

  scheduler:
    name: ConstantLR

exporter:
  onnx:
    opset_version: 11
  blobconverter:
    active: True
    shaves: 8
