loader:
  name: CustomMultiInputLoader  # Yields "left", "right", "disparity", and "pointcloud" inputs

use_rich_text: True

model:
  name: example_multi_input
  nodes:
    - name: FullBackbone
      alias: full_backbone

    - name: RGBDBackbone
      alias: rgbd_backbone
      input_sources:
        - left
        - right
        - disparity

    - name: PointcloudBackbone
      alias: pointcloud_backbone
      input_sources:
        - pointcloud

    - name: FusionNeck
      alias: fusion_neck
      inputs:
        - rgbd_backbone
        - pointcloud_backbone
      input_sources:
        - disparity

    - name: FusionNeck2
      alias: fusion_neck_2
      inputs:
        - rgbd_backbone
        - pointcloud_backbone
        - full_backbone
    
    - name: CustomSegHead1
      alias: head_1
      inputs:
        - fusion_neck

    - name: CustomSegHead2
      alias: head_2
      inputs:
        - fusion_neck
        - fusion_neck_2
      input_sources:
        - disparity

  losses:
    - name: BCEWithLogitsLoss
      alias: loss_1
      attached_to: head_1

    - name: BCEWithLogitsLoss
      alias: loss_2
      attached_to: head_2

  metrics:
    - name: JaccardIndex
      alias: jaccard_index_1
      attached_to: head_1
      is_main_metric: True
      params:
        task: binary

    - name: JaccardIndex
      alias: jaccard_index_2
      attached_to: head_2
      params:
        task: binary

trainer:
  batch_size: 8
  epochs: &epochs 3
  num_workers: 4
  validation_interval: 3
  num_log_images: -1

  callbacks:
    - name: ExportOnTrainEnd
  
  optimizer:
    name: Adam
    params:
      lr: 0.01

exporter:
  onnx:
    opset_version: 11

# tracker:
#   project_name: ace_reid_spot_segmentation
#   save_directory: output
#   is_tensorboard: True
#   is_wandb: False
#   wandb_entity: luxonis
#   is_mlflow: False
