# Example configuration for exporting a predefined
# light detection model to ONNX and BLOB formats.

model:
  name: detection_light

  # NOTE: Specify a path or URL to the weights here
  # Alternatively, use the `--weights` argument
  # if you are using the `luxonis_train` CLI tool.
  weights: null

  predefined_model:
    name: DetectionModel
    variant: light
    params:
      head_params:
        # Specify custom output names of the exported ONNX model.
        #
        # NOTE: These are actually the default names for the
        # `EfficientBBoxHead` node used in the light detection model.
        export_output_names:
          - output1_yolov6r2
          - output2_yolov6r2
          - output3_yolov6r2

loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [384, 512]

  batch_size: 8

exporter:
  onnx:
    # Override the default ONNX opset version if needed
    opset_version: 11
  # Additioanlly compile to BLOB for use with RVC2 devices
  blobconverter:
    active: true
    shaves: 8
