# Example configuration for exporting a predefined light detection model

model:
  name: detection_light
  weights: null  # TODO: Specify a path to the weights here
  predefined_model:
    name: DetectionModel
    variant: light
    params:
      head_params:
        export_output_names:
          - output1_yolov6r2
          - output2_yolov6r2
          - output3_yolov6r2

loader:
  params:
    dataset_name: coco_test

trainer:
  preprocessing:
    train_image_size: [384, 512]
    keep_aspect_ratio: true
    normalize:
      active: true

  batch_size: 8
  epochs: &epochs 200
  n_workers: 4
  validation_interval: 10
  n_log_images: 8

  optimizer:
    name: SGD
    params:
      lr: 0.02
      momentum: 0.937
      weight_decay: 0.0005
      dampening: 0.0
      nesterov: true

  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: *epochs
      eta_min: 0.0002
      last_epoch: -1

exporter:
  onnx:
    opset_version: 11
  blobconverter:
    active: true
    shaves: 8
