# Example configuration for training a predefined obb (oriented bounding box) detection model

model:
  name: obb_detection
  predefined_model:
    name: OBBDetectionModel
    params:
      use_neck: True

loader:
  # name: OBBLoaderTorch
  train_view: train
  val_view: val
  # test_view: train

  params:
    dataset_name: obb_test
    # dataset_dir: "../dota8"
    dataset_dir: "../DOTA"
    dataset_type: YOLOV6OBB

trainer:
  # preprocessing:
    # train_image_size: [&height 512, &width 512]
    # normalize:
    #   active: True
  #   keep_aspect_ratio: False
  #   normalize:
  #     active: True

  batch_size: 8
  epochs: &epochs 10
  num_workers: 4
  validation_interval: 10
  num_log_images: 8

  callbacks:
    # - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: Adam
    params:
      lr: 0.001

  # scheduler:
  #   name: ConstantLR

