
model:
  name: resnet50_classification
  nodes:
    - name: ResNet
      params:
        variant: "50"
        download_weights: True

    - name: ClassificationHead
      alias: ClassificationHead_1
      task: classification_1
      inputs:
        - ResNet

    - name: ClassificationHead
      alias: ClassificationHead_2
      task: classification_2
      inputs:
        - ResNet

    - name: ClassificationHead
      alias: ClassificationHead_3
      task: classification_3
      inputs:
        - ResNet

  losses:
    - name: CrossEntropyLoss
      alias: CrossEntropyLoss_1
      attached_to: ClassificationHead_1

    - name: CrossEntropyLoss
      alias: CrossEntropyLoss_2
      attached_to: ClassificationHead_2

    - name: CrossEntropyLoss
      alias: CrossEntropyLoss_3
      attached_to: ClassificationHead_3

  metrics:
    - name: Accuracy
      is_main_metric: true
      alias: Accuracy_1
      attached_to: ClassificationHead_1

    - name: Accuracy
      alias: Accuracy_2
      attached_to: ClassificationHead_2

    - name: Accuracy
      alias: Accuracy_3
      attached_to: ClassificationHead_3

  visualizers:
    - name: ClassificationVisualizer
      alias: ClassificationVisualizer_1
      attached_to: ClassificationHead_1
      params:
        font_scale: 0.5
        color: [255, 0, 0]
        thickness: 2
        include_plot: True

    - name: ClassificationVisualizer
      alias: ClassificationVisualizer_2
      attached_to: ClassificationHead_2
      params:
        font_scale: 0.5
        color: [255, 0, 0]
        thickness: 2
        include_plot: True

    - name: ClassificationVisualizer
      alias: ClassificationVisualizer_3
      attached_to: ClassificationHead_3
      params:
        font_scale: 0.5
        color: [255, 0, 0]
        thickness: 2
        include_plot: True

loader:
  params:
    dataset_name: cifar10_task_test

trainer:
  batch_size: 4
  epochs: &epochs 200
  num_workers: 4
  validation_interval: 10
  num_log_images: 8

  preprocessing:
    train_image_size: [&height 224, &width 224]
    keep_aspect_ratio: False
    normalize:
      active: True

  callbacks:
    - name: ExportOnTrainEnd
    - name: TestOnTrainEnd

  optimizer:
    name: SGD
    params:
      lr: 0.02

  scheduler:
    name: ConstantLR
