"""The MobileOne backbone, which trains with multiple branches and folds
the branches of each block into one convolution in export mode.
"""

from luxonis_ml.typing import Kwargs
from torch import Tensor, nn
from typeguard import typechecked
from typing_extensions import override

from luxonis_train.nodes.base_node import BaseNode
from luxonis_train.nodes.blocks import (
    GeneralReparameterizableBlock,
    SqueezeExciteBlock,
)
from luxonis_train.nodes.blocks.utils import forward_gather


class MobileOne(BaseNode):
    r"""MobileOne backbone for mobile devices.

    The backbone is a stem and four stages. The stem is a
    :math:`3 \times 3` `GeneralReparameterizableBlock` with a stride of
    ``2`` and one dense branch. The four stages have 2, 8, 10, and 1
    blocks. Each block is a :math:`3 \times 3` depthwise and a
    :math:`1 \times 1` pointwise `GeneralReparameterizableBlock`. Both
    have ``n_conv_branches`` dense branches. The first block of each
    stage has a stride of ``2``. In export mode, each
    `GeneralReparameterizableBlock` folds its branches into one
    convolution.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, H, W\right]`

    Outputs:
        - ``features`` (``list[Tensor]``): stem and four stages; strides
          2, 4, 8, 16, 32

    References:
        - Source: Adapted from `apple/ml-mobileone
          <https://github.com/apple/ml-mobileone>`_. Paper: `MobileOne:
          An Improved One millisecond Mobile Backbone
          <https://arxiv.org/abs/2206.04040>`_.
        - License: `Apple Software License Agreement
          <https://github.com/apple/ml-mobileone/blob/main/LICENSE>`_

    Notes:
        All variants use four dense branches. Only ``"s0"`` sets
        ``n_conv_branches``, and the constructor default is also ``4``.
        The ``"s4"`` variant **does not run**. Its ``use_se=True`` makes
        `forward` raise ``RuntimeError``. The ``use_se`` argument of
        ``__init__`` gives the cause.

    Variants:
        - ``"s0"``:
            - Default: yes
            - Aliases: None
            - Parameters:
                - ``width_multipliers``: ``(0.75, 1.0, 1.0, 2.0)``
                - ``n_conv_branches``: ``4``
                - ``use_se``: ``False``
        - ``"s1"``:
            - Default: no
            - Aliases: None
            - Parameters:
                - ``width_multipliers``: ``(1.5, 1.5, 2.0, 2.5)``
                - ``use_se``: ``False``
        - ``"s2"``:
            - Default: no
            - Aliases: None
            - Parameters:
                - ``width_multipliers``: ``(1.5, 2.0, 2.5, 4.0)``
                - ``use_se``: ``False``
        - ``"s3"``:
            - Default: no
            - Aliases: None
            - Parameters:
                - ``width_multipliers``: ``(2.0, 2.5, 3.0, 4.0)``
                - ``use_se``: ``False``
        - ``"s4"``:
            - Default: no
            - Aliases: None
            - Parameters:
                - ``width_multipliers``: ``(3.0, 3.5, 3.5, 4.0)``
                - ``use_se``: ``True``

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: MobileOne
              variant: s0

    Compatible with:
        - Attach index: ``-1``, the last output of the input node

    """

    in_channels: int

    @typechecked
    def __init__(
        self,
        width_multipliers: tuple[float, float, float, float] = (
            0.75,
            1.0,
            1.0,
            2.0,
        ),
        n_conv_branches: int = 4,
        use_se: bool = False,
        **kwargs,
    ):
        """Initialize the stem and the four stages.

        Args:
            width_multipliers (tuple[float, float, float, float]): The
                channel multipliers ``w`` of the four stages. The stages
                have ``int(64 * w[0])``, ``int(128 * w[1])``,
                ``int(256 * w[2])``, and ``int(512 * w[3])`` output
                channels. The stem has ``min(64, int(64 * w[0]))``
                output channels.
            n_conv_branches (int): The number of dense branches of each
                depthwise and pointwise convolution in the stages. The
                stem always has one dense branch.
            use_se (bool): Whether to add `SqueezeExciteBlock` layers.
                They go into the last 5 blocks of stage 3 and into the
                only block of stage 4. Each has ``int(256 * w[2]) // 16``
                hidden channels. The depthwise and the pointwise
                convolution of a block share one `SqueezeExciteBlock`.
                The pointwise convolution of stage 4 has
                ``int(512 * w[3])`` output channels. Thus `forward`
                raises ``RuntimeError`` unless that number is equal to
                ``int(256 * w[2])``.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseNode`.

        """
        super().__init__(**kwargs)

        self._n_blocks_per_stage = [2, 8, 10, 1]
        self._n_conv_branches = n_conv_branches

        self._in_channels = min(64, int(64 * width_multipliers[0]))

        self.stages = nn.ModuleList(
            [
                GeneralReparameterizableBlock(
                    in_channels=self.in_channels,
                    out_channels=self._in_channels,
                    kernel_size=3,
                    stride=2,
                    padding=1,
                ),
                self._make_stage(
                    int(64 * width_multipliers[0]),
                    self._n_blocks_per_stage[0],
                    n_se_blocks=0,
                ),
                self._make_stage(
                    int(128 * width_multipliers[1]),
                    self._n_blocks_per_stage[1],
                    n_se_blocks=0,
                ),
                self._make_stage(
                    int(256 * width_multipliers[2]),
                    self._n_blocks_per_stage[2],
                    n_se_blocks=self._n_blocks_per_stage[2] // 2
                    if use_se
                    else 0,
                ),
                self._make_stage(
                    int(512 * width_multipliers[3]),
                    self._n_blocks_per_stage[3],
                    n_se_blocks=self._n_blocks_per_stage[3] if use_se else 0,
                ),
            ]
        )

    def forward(self, inputs: Tensor) -> list[Tensor]:
        """Run the stem and the four stages on a batch of images.

        Args:
            inputs (``Tensor``): The input images, of shape
                ``[B, C, H, W]``.

        Returns:
            ``list[Tensor]``: Five feature maps: the output of the stem,
            then the output of each stage. Their strides are 2, 4, 8,
            16, and 32. For a height and a width that are multiples of
            ``32``, a map with the stride ``s`` has the height ``H / s``
            and the width ``W / s``. ``width_multipliers`` sets the
            channels.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes.backbones import MobileOne
            >>> shapes = [{"features": [Size([2, 3, 64, 64])]}]
            >>> node = MobileOne(input_shapes=shapes, variant="s0")
            >>> features = node(torch.zeros(2, 3, 64, 64))
            >>> [tuple(feature.shape) for feature in features]
            [(2, 48, 32, 32), (2, 48, 16, 16), (2, 128, 8, 8),
             (2, 256, 4, 4), (2, 1024, 2, 2)]

        """
        return forward_gather(inputs, self.stages)

    @override
    @staticmethod
    def get_variants() -> tuple[str, dict[str, Kwargs]]:
        """Return the default variant name and the five MobileOne variants.

        The variants ``"s0"`` to ``"s4"`` set ``width_multipliers`` and
        ``use_se``. Only ``"s0"`` sets ``n_conv_branches``. Only ``"s4"``
        sets ``use_se`` to ``True``. The ``Variants`` section of
        `MobileOne` lists all values. Each call builds new dictionaries.

        Returns:
            ``tuple[str, dict[str, Kwargs]]``: The name of the default
            variant, ``"s0"``, and a dictionary that maps each variant
            name to its constructor arguments.

        Example:
            >>> from luxonis_train.nodes.backbones import MobileOne
            >>> default, variants = MobileOne.get_variants()
            >>> default, sorted(variants)
            ('s0', ['s0', 's1', 's2', 's3', 's4'])
            >>> variants["s4"]
            {'width_multipliers': (3.0, 3.5, 3.5, 4.0), 'use_se': True}

        """
        return "s0", {
            "s0": {
                "width_multipliers": (0.75, 1.0, 1.0, 2.0),
                "n_conv_branches": 4,
                "use_se": False,
            },
            "s1": {
                "width_multipliers": (1.5, 1.5, 2.0, 2.5),
                "use_se": False,
            },
            "s2": {
                "width_multipliers": (1.5, 2.0, 2.5, 4.0),
                "use_se": False,
            },
            "s3": {
                "width_multipliers": (2.0, 2.5, 3.0, 4.0),
                "use_se": False,
            },
            "s4": {
                "width_multipliers": (3.0, 3.5, 3.5, 4.0),
                "use_se": True,
            },
        }

    def _make_stage(
        self, out_channels: int, n_blocks: int, n_se_blocks: int
    ) -> nn.Sequential:
        """Build one stage of depthwise and pointwise convolution pairs.

        The method sets ``_in_channels`` to ``out_channels`` after the
        first block.

        Args:
            out_channels (int): The number of output channels of the
                stage.
            n_blocks (int): The number of blocks. The first block has a
                stride of ``2``.
            n_se_blocks (int): The number of blocks, at the end of the
                stage, that get a `SqueezeExciteBlock`.

        Returns:
            ``nn.Sequential``: The depthwise and the pointwise
            convolution of each block, in order.

        Raises:
            ValueError: When ``n_se_blocks`` is larger than ``n_blocks``.

        """
        # Get strides for all layers
        strides = [2] + [1] * (n_blocks - 1)
        blocks: list[nn.Module] = []
        for ix, stride in enumerate(strides):
            if n_se_blocks > n_blocks:
                raise ValueError(
                    "Number of SE blocks cannot exceed number of layers."
                )
            if ix >= (n_blocks - n_se_blocks):
                refine_block = SqueezeExciteBlock(
                    in_channels=self._in_channels,
                    intermediate_channels=self._in_channels // 16,
                )
            else:
                refine_block = nn.Identity()

            # Depthwise conv
            blocks.append(
                GeneralReparameterizableBlock(
                    in_channels=self._in_channels,
                    out_channels=self._in_channels,
                    kernel_size=3,
                    stride=stride,
                    padding=1,
                    groups=self._in_channels,
                    n_branches=self._n_conv_branches,
                    refine_block=refine_block,
                    scale_layer_padding=0,
                )
            )
            # Pointwise conv
            blocks.append(
                GeneralReparameterizableBlock(
                    in_channels=self._in_channels,
                    out_channels=out_channels,
                    kernel_size=1,
                    stride=1,
                    padding=0,
                    groups=1,
                    n_branches=self._n_conv_branches,
                    refine_block=refine_block,
                    use_scale_layer=False,
                )
            )
            self._in_channels = out_channels
        return nn.Sequential(*blocks)
