#!/usr/bin/env bash

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

# Temporary files live next to their target so the final `mv` stays atomic,
# which also means an interrupted run would otherwise leave them behind.
temporary_files=()
cleanup() {
  if [ ${#temporary_files[@]} -gt 0 ]; then
    rm -f "${temporary_files[@]}"
  fi
}
trap cleanup EXIT
trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM

# `mktemp` creates files as 0600, but these are tracked, world-readable
# files; without this they would silently become owner-only.
file_mode="$(printf '%03o' "$((0666 & ~$(umask)))")"

# Keep the lockfile and pip compatibility exports in sync with pyproject.toml.
uv lock

export_requirements() {
  local output_file="$1"
  shift

  local temporary_file
  temporary_file="$(mktemp "${output_file}.XXXXXX")"
  temporary_files+=("$temporary_file")

  {
    printf '%s\n' '# This file is autogenerated by uv. Do not edit it manually.'
    printf '%s\n' '# Add or update dependencies in pyproject.toml, then run scripts/export_requirements.sh.'
    # `opencv-python-headless` is overridden to an unsatisfiable marker in
    # pyproject.toml, so it never installs; skip emitting the dead entry.
    uv export --locked --format requirements.txt --no-header \
      --no-annotate --no-emit-project \
      --no-emit-package opencv-python-headless "$@"
  } >"$temporary_file"

  chmod "$file_mode" "$temporary_file"
  mv "$temporary_file" "$output_file"
}

# Everything that resolves `torch` needs the PyTorch index, because the
# lock pins the `+cu130` local versions that only exist there. The
# config-test export contains no torch, so it stays on PyPI alone.
export_requirements requirements.txt --emit-index-url --no-default-groups
export_requirements requirements-dev.txt --emit-index-url --no-default-groups --group dev
export_requirements requirements-aimet.txt --emit-index-url --no-default-groups --extra aimet
export_requirements requirements-config.txt --only-group config-test
