"""Generate the ``Example`` and ``Compatible with`` docstring sections.

Both sections state facts the registry already knows: the config name of
a component, the parameters its constructor requires, and which modules
may attach to which node. Writing them by hand lets them drift, so this
script writes them instead, between the markers below.

Run it with ``--check`` to fail when a docstring is out of date. The
pre-commit hook does this. Run it without arguments to rewrite them.

"""

import argparse
import ast
import functools
import importlib
import inspect
import pathlib
import sys
import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from luxonis_train.config.config import NodeConfig

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

BEGIN = ".. Generated by scripts/gen_component_docs.py. Do not edit."
SECTIONS = ("Example", "Compatible with")
WIDTH = 72

# Fallback inputs for nodes that no predefined model uses.
FALLBACK_INPUT = {
    "RepPANNeck": "EfficientRep",
    "SVTRNeck": "PPLCNetV3",
    "EfficientBBoxHead": "RepPANNeck",
    "EfficientKeypointBBoxHead": "RepPANNeck",
    "PrecisionBBoxHead": "RepPANNeck",
    "PrecisionSegmentBBoxHead": "RepPANNeck",
    "SegmentationHead": "RepPANNeck",
    "BiSeNetHead": "ContextSpatial",
    "DDRNetSegmentationHead": "DDRNet",
    "ClassificationHead": "ResNet",
    "FOMOHead": "EfficientRep",
    "GhostFaceNetHead": "GhostFaceNet",
    "OCRCTCHead": "SVTRNeck",
    "DiscSubNetHead": "RecSubNet",
    "TransformerClassificationHead": "DinoV3",
    "TransformerSegmentationHead": "DinoV3",
}
# Values for the parameters that have no default.
REQUIRED_EXAMPLE = {
    "alphabet": '["a", "b", "c"]',
    "num_classes": "2",
    "weights_link": '"<path or URL to the DINOv3 weights>"',
}
# Filled from the predefined models, so the examples match the configs
# this project ships.
DEFAULT_INPUT: dict[str, str] = {}


def _instantiate(cls: type, variant: str) -> list | None:
    """Build the node graph of a predefined model at one variant."""
    _, variants = cls.get_variants()  # type: ignore[attr-defined]
    try:
        return cls(**variants[variant]).nodes  # type: ignore[attr-defined]
    except (TypeError, ValueError, KeyError) as error:  # pragma: no cover
        print(f"Skipping {cls.__name__}: {error}", file=sys.stderr)
        return None


@functools.cache
def _predefined_graph() -> dict[str, str]:
    """Which node feeds which, as the packaged models wire them up."""
    import importlib

    importlib.import_module("luxonis_train.config.predefined_models")
    from luxonis_train.registry import MODELS

    graph: dict[str, str] = {}
    for cls in dict.fromkeys(MODELS._module_dict.values()):
        default, _ = cls.get_variants()
        nodes = _instantiate(cls, default)
        if nodes is None:  # pragma: no cover
            continue
        for node in nodes:
            if node.inputs:
                graph.setdefault(node.name, node.inputs[0])
    return graph


@functools.cache
def _predefined_heads() -> list[str]:
    """Head names the packaged models use, most-used first."""
    import importlib
    from collections import Counter

    importlib.import_module("luxonis_train.config.predefined_models")
    from luxonis_train.registry import MODELS

    counter: Counter[str] = Counter()
    for cls in dict.fromkeys(MODELS._module_dict.values()):
        default, _ = cls.get_variants()
        nodes = _instantiate(cls, default)
        if nodes is None:  # pragma: no cover
            continue
        counter[nodes[-1].name] += 1
    return [name for name, _ in counter.most_common()]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report out-of-date docstrings instead of rewriting them.",
    )
    args = parser.parse_args()

    importlib.import_module("luxonis_train.nodes")
    importlib.import_module("luxonis_train.attached_modules")
    importlib.import_module("luxonis_train.config.predefined_models")

    blocks = _generate()
    stale: list[str] = []
    for path in sorted(
        list((ROOT / "luxonis_train" / "nodes").rglob("*.py"))
        + list((ROOT / "luxonis_train" / "attached_modules").rglob("*.py"))
        + list(
            (ROOT / "luxonis_train" / "config" / "predefined_models").rglob(
                "*.py"
            )
        )
    ):
        original = path.read_text(encoding="utf-8")
        updated = _apply(original, blocks)
        if updated == original:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(updated, encoding="utf-8")

    if stale:
        print(
            "Generated docstring sections are out of date in:", file=sys.stderr
        )
        for name in stale:
            print(f"  - {name}", file=sys.stderr)
        print(
            "\nRun `python scripts/gen_component_docs.py` to update them.",
            file=sys.stderr,
        )
        return 1
    return 0


def _generate() -> dict[str, list[str]]:
    """Build the generated lines for every registered component."""
    from luxonis_train.registry import (
        LOSSES,
        METRICS,
        MODELS,
        NODES,
        VISUALIZERS,
    )

    DEFAULT_INPUT.update(FALLBACK_INPUT)
    DEFAULT_INPUT.update(dict(_predefined_graph()))

    heads = _heads()
    attached = {
        "Losses": _by_class(LOSSES),
        "Metrics": _by_class(METRICS),
        "Visualizers": _by_class(VISUALIZERS),
    }
    node_names = _by_class(NODES)

    blocks: dict[str, list[str]] = {}
    for cls, names in node_names.items():
        blocks[cls.__name__] = _node_block(cls, names, heads, attached)
    for kind, by_class in attached.items():
        for cls, names in by_class.items():
            blocks[cls.__name__] = _attached_block(cls, names, kind, heads)
    for cls, names in _by_class(MODELS).items():
        blocks[cls.__name__] = _model_block(cls, min(names))
    return blocks


def _model_block(cls: type, name: str) -> list[str]:
    """Build the components a predefined model contributes."""
    default, variants = cls.get_variants()  # type: ignore[attr-defined]
    return [
        "Example:",
        *_indent(_model_yaml(name, default)),
        "",
        "Components:",
        *_indent(_model_components(cls, default, list(variants))),
    ]


def _model_yaml(name: str, variant: str) -> list[str]:
    return [
        "The ``model`` section of a config:",
        "",
        ".. code-block:: yaml",
        "",
        *_indent(
            [
                "model:",
                "  predefined_model:",
                f"    name: {name}",
                "    params:",
                f"      variant: {variant}",
            ]
        ),
    ]


def _model_components(
    cls: type, default: str, variants: list[str]
) -> list[str]:
    nodes = _instantiate(cls, default)
    if nodes is None:  # pragma: no cover
        return _wrap_list("Variants", variants)
    chain = " -> ".join(f"``{node.name}``" for node in nodes)
    out = textwrap.wrap(
        f"- Nodes: {chain}",
        WIDTH,
        subsequent_indent="  ",
        break_long_words=False,
        break_on_hyphens=False,
    )
    for label, key in (
        ("Losses", "losses"),
        ("Metrics", "metrics"),
        ("Visualizers", "visualizers"),
    ):
        names = sorted(
            {module.name for node in nodes for module in getattr(node, key)}
        )
        if names:
            out += _wrap_list(label, names)
    main = next(
        (
            metric.name
            for node in nodes
            for metric in node.metrics
            if metric.is_main_metric
        ),
        None,
    )
    if main is not None:
        out.append(f"- Main metric: ``{main}``")
    return out + _wrap_list("Variants", variants)


def _node_block(
    cls: type,
    names: list[str],
    heads: list[type],
    attached: dict[str, dict[type, list[str]]],
) -> list[str]:
    lines = ["Example:", *_indent(_node_yaml(cls, min(names)))]
    compatible = _node_compatible(cls)
    if compatible:
        lines += ["", "Compatible with:", *_indent(compatible)]
    return lines


def _attached_block(
    cls: type, names: list[str], kind: str, heads: list[type]
) -> list[str]:
    usable = [head for head in heads if _attaches(cls, head)]
    preferred = _predefined_heads()
    primary = (getattr(cls, "supported_tasks", None) or [None])[0]
    head = min(
        usable,
        key=lambda h: (
            getattr(h, "task", None) != primary,
            preferred.index(h.__name__)
            if h.__name__ in preferred
            else len(preferred),
            h.__name__,
        ),
        default=None,
    )
    example_name = min(names)
    lines = [
        "Example:",
        *_indent(_attached_yaml(cls, example_name, kind, head)),
    ]
    compatible = _wrap_list("Used by", _used_by().get(example_name, []))
    if usable:
        compatible += _wrap_list(
            "Nodes", sorted(head.__name__ for head in usable)
        )
    if len(names) > 1:
        compatible += _wrap_list("Registered under", sorted(names))
    if compatible:
        lines += ["", "Compatible with:", *_indent(compatible)]
    return lines


def _node_yaml(cls: type, name: str) -> list[str]:
    entry = [f"- name: {name}"]
    source = DEFAULT_INPUT.get(name)
    if source is not None:
        entry.append(f"  inputs: [{source}]")
    variant = _default_variant(cls)
    if variant is not None:
        entry.append(f"  variant: {variant}")
    required = _required(cls)
    if required:
        entry.append("  params:")
        entry += [f"    {key}: {value}" for key, value in required.items()]
    return [
        "A node entry in the ``model.nodes`` section of a config:",
        "",
        ".. code-block:: yaml",
        "",
        *_indent(entry),
    ]


def _attached_yaml(
    cls: type, name: str, kind: str, head: type | None
) -> list[str]:
    key = {
        "Losses": "losses",
        "Metrics": "metrics",
        "Visualizers": "visualizers",
    }[kind]
    entry = [f"- name: {name}"]
    required = _required(cls)
    if required:
        entry.append("  params:")
        entry += [f"    {key_}: {value}" for key_, value in required.items()]
    if head is None:
        return [
            f"An entry in the ``{key}`` list of a node:",
            "",
            ".. code-block:: yaml",
            "",
            *_indent(entry),
        ]
    return [
        f"Attached to a ``{head.__name__}`` in ``model.nodes``:",
        "",
        ".. code-block:: yaml",
        "",
        *_indent(
            [
                f"- name: {head.__name__}",
                *(
                    [f"  inputs: [{DEFAULT_INPUT[head.__name__]}]"]
                    if head.__name__ in DEFAULT_INPUT
                    else []
                ),
                f"  {key}:",
                *[f"    {line}" for line in entry],
            ]
        ),
    ]


def _required_labels(cls: type) -> list[str]:
    """List the dataset annotations a head needs to train."""
    task = getattr(cls, "task", None)
    if task is None:
        return []
    labels = sorted(str(label) for label in task.required_labels)
    return _wrap_list("Required labels", labels) if labels else []


@functools.cache
def _used_by() -> dict[str, list[str]]:
    """Map each component to the predefined models that name it."""
    import importlib

    importlib.import_module("luxonis_train.config.predefined_models")
    from luxonis_train.registry import MODELS

    used: dict[str, set[str]] = {}
    for model in dict.fromkeys(MODELS._module_dict.values()):
        default, _ = model.get_variants()
        nodes = _instantiate(model, default) or []
        for name in {n for node in nodes for n in _member_names(node)}:
            used.setdefault(name, set()).add(model.__name__)
    return {name: sorted(models) for name, models in used.items()}


def _member_names(node: "NodeConfig") -> list[str]:
    """Name a node and every module attached to it."""
    attached = (*node.losses, *node.metrics, *node.visualizers)
    return [node.name, *(module.name for module in attached)]


def _attachment_lines(head: type) -> list[str]:
    """Build the attachments an example head config needs."""
    from luxonis_train.registry import LOSSES, METRICS, VISUALIZERS

    lines: list[str] = []
    for key, registry in (
        ("losses", LOSSES),
        ("metrics", METRICS),
        ("visualizers", VISUALIZERS),
    ):
        hidden = _hidden_by_factory(registry, head)
        names = sorted(
            name
            for name, cls in registry._module_dict.items()
            if _attaches(cls, head) and name not in hidden
        )
        if not names:
            continue
        lines.append(f"  {key}:")
        primary = min(names, key=lambda n: ("ConfusionMatrix" in n, n))
        lines.append(f"    - name: {primary}")
    return lines


def _node_compatible(cls: type) -> list[str]:
    lines = _required_labels(cls) + _wrap_list(
        "Used by", _used_by().get(cls.__name__, [])
    )
    if _is_head(cls):
        from luxonis_train.registry import LOSSES, METRICS, VISUALIZERS

        for label, registry in (
            ("Losses", LOSSES),
            ("Metrics", METRICS),
            ("Visualizers", VISUALIZERS),
        ):
            hidden = _hidden_by_factory(registry, cls)
            names = sorted(
                name
                for name, module in registry._module_dict.items()
                if _attaches(module, cls) and name not in hidden
            )
            if names:
                lines += _wrap_list(label, names)
        parser = getattr(cls, "parser", "")
        if parser:
            lines += _wrap_list("Export parser", [parser])
    if "get_weights_url" in cls.__dict__:
        lines.append(
            "- Pretrained weights: available through ``weights: download``"
        )
    return lines


def _wrap_list(label: str, names: list[str]) -> list[str]:
    if not names:
        return []
    joined = ", ".join(f"``{name}``" for name in names)
    return textwrap.wrap(
        f"- {label}: {joined}",
        WIDTH,
        subsequent_indent="  ",
        break_long_words=False,
        break_on_hyphens=False,
    )


def _attaches(module: type, head: type) -> bool:
    """Whether ``module`` may be attached to the ``head`` node."""
    task = getattr(head, "task", None)
    required = module.__annotations__.get("node")
    if isinstance(required, type) and not issubclass(head, required):
        return False
    tasks = getattr(module, "supported_tasks", None) or _factory_tasks(module)
    if tasks is None:
        # Constrained only by the node type, if at all.
        return required is not None
    return task is not None and task in tasks


@functools.cache
def _factory_tasks(cls: type) -> tuple | None:
    """Tasks a registry factory dispatches on, from its ``Tasks.X``
    uses.

    A factory is registered under the name users write in a config, but
    returns one of several concrete modules depending on the node's
    task, so it declares no ``supported_tasks`` of its own.

    """
    from luxonis_train.tasks import Tasks

    try:
        source = inspect.getsource(cls)
    except (OSError, TypeError):  # pragma: no cover
        return None
    names = {
        node.attr
        for node in ast.walk(ast.parse(textwrap.dedent(source)))
        if isinstance(node, ast.Attribute)
        and isinstance(node.value, ast.Name)
        and node.value.id == "Tasks"
    }
    tasks = tuple(getattr(Tasks, name) for name in sorted(names))
    return tasks or None


def _hidden_by_factory(registry: object, head: type) -> set[str]:
    """Concrete modules a compatible factory already covers."""
    hidden: set[str] = set()
    for name, cls in registry._module_dict.items():  # type: ignore[attr-defined]
        if getattr(cls, "supported_tasks", None) is not None:
            continue
        if _factory_tasks(cls) is None or not _attaches(cls, head):
            continue
        module = sys.modules[cls.__module__]
        hidden |= {
            other
            for other, other_cls in registry._module_dict.items()  # type: ignore[attr-defined]
            if other != name
            and other_cls.__name__ in dir(module)
            and getattr(other_cls, "supported_tasks", None) is not None
        }
    return hidden


def _required(cls: type) -> dict[str, str]:
    values: dict[str, str] = {}
    for name, parameter in inspect.signature(cls.__init__).parameters.items():
        if name in {"self", "node"} or parameter.kind in {
            parameter.VAR_KEYWORD,
            parameter.VAR_POSITIONAL,
        }:
            continue
        if parameter.default is not parameter.empty:
            continue
        if name in REQUIRED_EXAMPLE:
            values[name] = REQUIRED_EXAMPLE[name]
        elif _default_variant(cls) is None:
            values[name] = "..."
    return values


def _default_variant(cls: type) -> str | None:
    get_variants = getattr(cls, "get_variants", None)
    if get_variants is None:
        return None
    try:
        default, _ = get_variants()
    except NotImplementedError:
        return None
    return default


def _is_head(cls: type) -> bool:
    from luxonis_train.nodes.heads import BaseHead

    return issubclass(cls, BaseHead)


def _heads() -> list[type]:
    from luxonis_train.registry import NODES

    return [
        cls
        for cls in _by_class(NODES)
        if _is_head(cls) and getattr(cls, "task", None) is not None
    ]


def _by_class(registry: object) -> dict[type, list[str]]:
    """Registry contents as ``class -> registered names``.

    Classes created on the fly, such as the one wrapper per pytorch-
    metric-learning loss, share the source class they come from. They
    are grouped under it, so its docstring lists every name.

    """
    by_key: dict[tuple[str, str], tuple[type, list[str]]] = {}
    for name, cls in registry._module_dict.items():  # type: ignore[attr-defined]
        key = (cls.__module__, cls.__name__)
        _, names = by_key.setdefault(key, (cls, []))
        names.append(name)
    return dict(by_key.values())


def _indent(lines: list[str], amount: int = 4) -> list[str]:
    pad = " " * amount
    return [pad + line if line else "" for line in lines]


def _apply(source: str, blocks: dict[str, list[str]]) -> str:
    tree = ast.parse(source)
    spans: list[tuple[int, int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef) or node.name not in blocks:
            continue
        doc = ast.get_docstring(node)
        if doc is None:
            continue
        if "References:" not in doc and BEGIN not in doc:
            continue
        first = node.body[0]
        assert isinstance(first, ast.Expr)
        assert first.end_lineno is not None
        spans.append((first.lineno - 1, first.end_lineno, node.name))

    lines = source.split("\n")
    for start, end, name in sorted(spans, reverse=True):
        lines = _replace(lines, start, end, blocks[name])
    return "\n".join(lines)


def _replace(
    lines: list[str], start: int, end: int, block: list[str]
) -> list[str]:
    indent = " " * (len(lines[start]) - len(lines[start].lstrip()))
    body = [
        indent + BEGIN,
        "",
        *(indent + line if line else "" for line in block),
    ]

    marker = next(
        (i for i in range(start, end) if lines[i].strip() == BEGIN), None
    )
    if marker is not None:
        return lines[:marker] + body + [""] + lines[_closing(lines, end) :]

    close = _closing(lines, end)
    return lines[:close] + body + [""] + lines[close:]


def _closing(lines: list[str], end: int) -> int:
    """Index of the docstring's closing quotes."""
    for i in range(end - 1, -1, -1):
        if lines[i].strip() == '"""':
            return i
    raise SystemExit("docstring does not close on its own line")


if __name__ == "__main__":
    raise SystemExit(main())
