"""The EfficientRep backbone of YOLOv6, built from reparameterizable
blocks that fold into plain convolutions for export.
"""

from typing import Literal, cast

from luxonis_ml.typing import Kwargs
from torch import Tensor, nn
from typing_extensions import override

from luxonis_train.nodes.base_node import BaseNode
from luxonis_train.nodes.blocks import (
    BlockRepeater,
    CSPStackRepBlock,
    GeneralReparameterizableBlock,
    SpatialPyramidPoolingBlock,
)
from luxonis_train.utils import make_divisible
from luxonis_train.variants import add_variant_aliases


class EfficientRep(BaseNode):
    r"""EfficientRep backbone for object detection.

    EfficientRep is a YOLOv6-style convolutional feature extractor with
    scalable depth, width, and block type presets. A stride-2 stem feeds
    four stages. Each stage starts with a stride-2
    `GeneralReparameterizableBlock`, and the blocks that ``block``
    selects follow it. The last stage ends with a
    `SpatialPyramidPoolingBlock`.

    Inputs:
        - ``inputs`` (``Tensor``): :math:`\left[B, C, H, W\right]`

    Outputs:
        - ``features`` (``list[Tensor]``): strides 4, 8, 16, 32;
          channels ``channels_list[1:] * width_multiplier``, rounded up
          to multiples of 8

    References:
        - Source: Reimplemented from `YOLOv6: A Single-Stage Object
          Detection Framework for Industrial Applications
          <https://arxiv.org/abs/2209.02976>`_.
        - License: Apache-2.0 (this project)

    Notes:
        Builds local YOLOv6-style stages with configurable ``RepBlock``
        or ``CSPStackRepBlock`` blocks.

    Variants:
        - ``"n"``:
            - Default: yes
            - Aliases: ``"nano"``
            - Parameters:
                - ``depth_multiplier``: ``0.33``
                - ``width_multiplier``: ``0.25``
                - ``block``: ``"RepBlock"``
                - ``csp_e``: ``None``
        - ``"s"``:
            - Default: no
            - Aliases: ``"small"``
            - Parameters:
                - ``depth_multiplier``: ``0.33``
                - ``width_multiplier``: ``0.50``
                - ``block``: ``"RepBlock"``
                - ``csp_e``: ``None``
        - ``"m"``:
            - Default: no
            - Aliases: ``"medium"``
            - Parameters:
                - ``depth_multiplier``: ``0.60``
                - ``width_multiplier``: ``0.75``
                - ``block``: ``"CSPStackRepBlock"``
                - ``csp_e``: ``2 / 3``
        - ``"l"``:
            - Default: no
            - Aliases: ``"large"``
            - Parameters:
                - ``depth_multiplier``: ``1.0``
                - ``width_multiplier``: ``1.0``
                - ``block``: ``"CSPStackRepBlock"``
                - ``csp_e``: ``1 / 2``

    .. Generated by scripts/gen_component_docs.py. Do not edit.

    Example:
        A node entry in the ``model.nodes`` section of a config:

        .. code-block:: yaml

            - name: EfficientRep
              variant: n

    Compatible with:
        - Attach index: ``-1``, the last output of the input node
        - Used by:

          - `DetectionModel`
          - `FOMOModel`
          - `InstanceSegmentationModel`
          - `KeypointDetectionModel`

        - Pretrained weights: available through ``weights: download``

    """

    in_channels: int

    def __init__(
        self,
        channels_list: list[int] | None = None,
        n_repeats: list[int] | None = None,
        depth_multiplier: float = 0.33,
        width_multiplier: float = 0.25,
        block: Literal["RepBlock", "CSPStackRepBlock"] = "RepBlock",
        csp_e: float = 0.5,
        weights: str = "yolo",
        **kwargs,
    ):
        """Build the stem, the four stages, and the pooling block.

        The constructor multiplies each entry of ``channels_list`` by
        ``width_multiplier`` and rounds it up to a multiple of 8. It
        multiplies each entry of ``n_repeats`` above ``1`` by
        ``depth_multiplier`` and rounds it to the nearest integer, with a
        minimum of ``1``. Entries of ``1`` or less stay unchanged. An
        explicit argument replaces the value that a variant sets.

        Args:
            channels_list (list[int] | None): The output channels of the
                stem and the four stages, before ``width_multiplier``.
                ``None`` or an empty list selects
                ``[64, 128, 256, 512, 1024]``.
            n_repeats (list[int] | None): The block counts of the stem
                and the four stages, before ``depth_multiplier``. The
                stem does not use its entry. ``None`` or an empty list
                selects ``[1, 6, 12, 18, 6]``.
            depth_multiplier (float): The scale of the block counts.
            width_multiplier (float): The scale of the channel counts.
            block (``Literal["RepBlock", "CSPStackRepBlock"]``): The
                block type of the stages. ``"RepBlock"`` stacks as many
                `GeneralReparameterizableBlock` blocks as the block
                count. ``"CSPStackRepBlock"`` uses one `CSPStackRepBlock`
                with the block count as ``n_blocks``.
            csp_e (float): The fraction of the output channels on each
                of the two paths of a `CSPStackRepBlock`. ``"RepBlock"``
                does not use it.
            weights (str): The weights argument of `BaseNode`.
                ``"yolo"`` applies the YOLO initialization. ``"download"``
                loads the COCO weights from `get_weights_url`.
            **kwargs (``Any``): Keyword arguments forwarded to
                `BaseNode`.

        """
        super().__init__(weights=weights, **kwargs)

        channels_list = channels_list or [64, 128, 256, 512, 1024]
        n_repeats = n_repeats or [1, 6, 12, 18, 6]
        channels_list = [
            make_divisible(i * width_multiplier, 8) for i in channels_list
        ]
        n_repeats = [
            (max(round(i * depth_multiplier), 1) if i > 1 else i)
            for i in n_repeats
        ]

        self.repvgg_encoder = GeneralReparameterizableBlock(
            in_channels=self.in_channels,
            out_channels=channels_list[0],
            kernel_size=3,
            stride=2,
        )

        self.blocks = cast(list[nn.Sequential], nn.ModuleList())
        for i in range(4):
            curr_block = nn.Sequential(
                GeneralReparameterizableBlock(
                    in_channels=channels_list[i],
                    out_channels=channels_list[i + 1],
                    kernel_size=3,
                    stride=2,
                ),
                (
                    BlockRepeater(
                        GeneralReparameterizableBlock,
                        in_channels=channels_list[i + 1],
                        out_channels=channels_list[i + 1],
                        n_repeats=n_repeats[i + 1],
                    )
                    if block == "RepBlock"
                    else CSPStackRepBlock(
                        in_channels=channels_list[i + 1],
                        out_channels=channels_list[i + 1],
                        n_blocks=n_repeats[i + 1],
                        e=csp_e,
                    )
                ),
            )
            self.blocks.append(curr_block)

        self.blocks[-1].append(
            SpatialPyramidPoolingBlock(
                in_channels=channels_list[4],
                out_channels=channels_list[4],
                kernel_size=5,
            )
        )

    def forward(self, inputs: Tensor) -> list[Tensor]:
        """Run the stem and return the output of each stage.

        Args:
            inputs (``Tensor``): Image batch of shape
                ``[B, in_channels, H, W]``.

        Returns:
            ``list[Tensor]``: The outputs of the four stages, at the
            strides 4, 8, 16, and 32. Their channels are the last four
            entries of the scaled ``channels_list``.

        Example:
            >>> import torch
            >>> from torch import Size
            >>> from luxonis_train.nodes import EfficientRep
            >>> shapes = [{"features": [Size([2, 3, 64, 64])]}]
            >>> node = EfficientRep(variant="n", input_shapes=shapes)
            >>> [tuple(t.shape) for t in node(torch.zeros(1, 3, 64, 64))]
            [(1, 32, 16, 16), (1, 64, 8, 8), (1, 128, 4, 4), (1, 256, 2, 2)]

        """
        outputs: list[Tensor] = []
        x = self.repvgg_encoder(inputs)
        for block in self.blocks:
            x = block(x)
            outputs.append(x)
        return outputs

    @override
    def get_weights_url(self) -> str:
        return f"{{github}}/efficientrep_{self.variant[0]}_coco.ckpt"

    @staticmethod
    @override
    def get_variants() -> tuple[str, dict[str, Kwargs]]:
        """Return the default variant name and the four EfficientRep sizes.

        Each variant sets ``depth_multiplier``, ``width_multiplier``,
        ``block``, and ``csp_e``. ``"n"`` and ``"s"`` use ``"RepBlock"``.
        ``"m"`` and ``"l"`` use ``"CSPStackRepBlock"``. The aliases
        ``"nano"``, ``"small"``, ``"medium"``, and ``"large"`` map to the
        same dictionaries as ``"n"``, ``"s"``, ``"m"``, and ``"l"``.

        Returns:
            ``tuple[str, dict[str, Kwargs]]``: The name ``"n"``, and a
            dictionary that maps each variant name and alias to its
            constructor arguments.

        Example:
            >>> from luxonis_train.nodes import EfficientRep
            >>> default, variants = EfficientRep.get_variants()
            >>> default, list(variants)
            ('n', ['n', 's', 'm', 'l', 'nano', 'small', 'medium', 'large'])
            >>> variants["nano"] is variants["n"]
            True

        """
        return "n", add_variant_aliases(
            {
                "n": {
                    "depth_multiplier": 0.33,
                    "width_multiplier": 0.25,
                    "block": "RepBlock",
                    "csp_e": None,
                },
                "s": {
                    "depth_multiplier": 0.33,
                    "width_multiplier": 0.50,
                    "block": "RepBlock",
                    "csp_e": None,
                },
                "m": {
                    "depth_multiplier": 0.60,
                    "width_multiplier": 0.75,
                    "block": "CSPStackRepBlock",
                    "csp_e": 2 / 3,
                },
                "l": {
                    "depth_multiplier": 1.0,
                    "width_multiplier": 1.0,
                    "block": "CSPStackRepBlock",
                    "csp_e": 1 / 2,
                },
            }
        )
