name: GitHub Actions Version Updater

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-github-actions:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-actions-update.yaml@1556182be18dd350dbeb5b07bc7282e17828b655
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
