name: GitHub Actions Version Updater

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-github-actions:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-actions-update.yaml@59ca6fe93e5c854289dba1e4dede0700ee57d658
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
