name: GitHub Actions Version Updater

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-github-actions:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-actions-update.yaml@90b4157a4040727fe38905acecb02d75f2f9d768
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
