name: Metadata

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  metadata:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-metadata.yaml@90b4157a4040727fe38905acecb02d75f2f9d768
