name: Metadata

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  metadata:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-metadata.yaml@1556182be18dd350dbeb5b07bc7282e17828b655
