name: Metadata

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  metadata:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-metadata.yaml@59ca6fe93e5c854289dba1e4dede0700ee57d658
