name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "requirements.txt"
      - "pyproject.toml"
      - "luxonis_train/**"
      - "tests/**"
      - ".github/workflows/ci.yaml"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  checks: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}

      - name: Install pre-commit
        run: python -m pip install 'pre-commit<4.0.0'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  docs:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: pip install pydoctor

      - name: Build docs
        run: pydoctor --docformat=epytext luxonis_train

  type-check:
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: pip install -e .[dev,aimet] --extra-index-url https://download.pytorch.org/whl/cu130

      - name: Install dev version of LuxonisML
        if: startsWith(github.head_ref, 'release/') == false
        run: |
          pip uninstall luxonis-ml -y
          pip install "luxonis-ml[data,tracker] @ git+https://github.com/luxonis/luxonis-ml.git@main"

      - name: Pyright check
        uses: jakebailey/pyright-action@8ec14b5cfe41f26e5f41686a31eb6012758217ef
        with:
          level: warning
          warnings: true
          python-version: "3.10"
          project: pyproject.toml

  # Tests that the `luxonis-train.config.Config` works
  # even when the dependencies of `luxonis-train` are
  # not installed.
  config-test:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - type-check
      - docs

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"
          cache: pip

      - name: Install released version of LuxonisML
        if: startsWith(github.head_ref, 'release/') == true
        run: pip install luxonis-ml[utils]

      - name: Install dev version of LuxonisML
        if: startsWith(github.head_ref, 'release/') == false
        run: |
          pip install "luxonis-ml[utils] @ git+https://github.com/luxonis/luxonis-ml.git@main"

      - name: Install dependencies for config test
        run: |
          pip install pytest-cov semver~=3.0
          pip install -e . --no-deps

      - name: Test config without dependencies
        run: |
          pytest -x tests/unittests/test_config.py \
            --confcutdir=tests/unittests \
            --cov=luxonis_train/config \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-fail-under=100 \
            --junitxml=junit.xml \
            -o junit_family=legacy

  tests:
    needs:
      - config-test

    strategy:
      matrix:
        suite: [unit, predefined, combinations, misc]

    runs-on: ${{ matrix.suite == 'unit' && 'ubuntu-latest' || 'ubuntu-t4-4core' }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: pip install -e .[dev,aimet] --extra-index-url https://download.pytorch.org/whl/cu130

      - name: Install dev version of LuxonisML
        if: startsWith(github.head_ref, 'release/') == false
        run: |
          pip uninstall luxonis-ml -y
          pip install "luxonis-ml[data,tracker] @ git+https://github.com/luxonis/luxonis-ml.git@main"

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true
          token_format: access_token

      - name: Run pytest
        env:
          LUXONISML_BUCKET: luxonis-test-bucket
          SUITE: ${{ matrix.suite }}
          HUBAI_API_KEY: ${{ secrets.HUBAI_API_KEY }}
        run: pytest -x --cov --junitxml=junit.xml -o junit_family=legacy -m "${SUITE}"

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          flags: ${{ matrix.suite }}

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          flags: ${{ matrix.suite }}

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: coverage-${{ matrix.suite }}
          path: coverage.xml
          overwrite: true
