name: Python Dependencies Updater

on:
  schedule:
    - cron: "0 1 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-python-dependencies:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-dependencies-update.yaml@59ca6fe93e5c854289dba1e4dede0700ee57d658
    with:
      export-script: scripts/export_requirements.sh
      uv-version: "0.11.28"
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
