name: Release Tag

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: >-
      github.event.pull_request.merged &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    uses: luxonis/luxonis-ml/.github/workflows/reusable-release-tag.yaml@cdfb00741162eb84ea9575881d412e420203e66f
    with:
      version-file: luxonis_train/__init__.py
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
