name: Semgrep SAST Scan

on:
  pull_request:

permissions:
  contents: read

jobs:
  semgrep:
    uses: luxonis/luxonis-ml/.github/workflows/reusable-semgrep.yaml@90b4157a4040727fe38905acecb02d75f2f9d768
