name: Run tests

on:
  workflow_dispatch:
    inputs:
      ml_ref:
        description: "luxonis-ml version (branch/tag/SHA)"
        required: true
        default: main
      train_ref:
        description: "luxonis-train version (branch/tag/SHA)"
        required: true
        default: main

  workflow_call:
    inputs:
      ml_ref:
        description: "luxonis-ml version (branch/tag/SHA)"
        required: true
        type: string
      train_ref:
        description: "luxonis-train version (branch/tag/SHA)"
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        description: "GCP service-account JSON"
        required: true
      CODECOV_TOKEN:
        description: "Codecov upload token"
        required: true
      HUBAI_API_KEY:
        description: "HubAI API key"
        required: true

permissions:
  pull-requests: write
  contents: write
  checks: write

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-t4-4core, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          repository: Luxonis/luxonis-train
          ref: ${{ inputs.train_ref }}
          path: luxonis-train

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        working-directory: luxonis-train
        run: pip install -e .[dev,aimet] --extra-index-url https://download.pytorch.org/whl/cu130

      - name: Install specified luxonis-ml
        shell: bash
        env:
          ML_REF: ${{ inputs.ml_ref }}
        run: |
          pip uninstall luxonis-ml -y
          pip install \
            "luxonis-ml[data,tracker] @ git+https://github.com/luxonis/luxonis-ml.git@${ML_REF}" \
            --upgrade --force-reinstall

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true
          token_format: access_token

      - name: Run pytest
        working-directory: luxonis-train
        env:
          LUXONISML_BUCKET: luxonis-test-bucket
          HUBAI_API_KEY: ${{ secrets.HUBAI_API_KEY }}
        run: pytest --cov --junitxml=junit.xml -o junit_family=legacy

      - name: Upload test results to Codecov
        if: matrix.os == 'ubuntu-t4-4core'
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Upload coverage results to Codecov
        if: matrix.os == 'ubuntu-t4-4core'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
